### ISSUE TITLE
Hook to modify additionalParameters of OAuth2AccessTokenAuthenticationToken

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [spring-projects/spring-authorization-server#1000]
It would be useful to be able to modify the `additionalParameters` passed into `OAuth2AccessTokenAuthenticationToken`. This would allow you to use information from, for example, `OAuth2Authorization` to generate the final access token response.

As it stands, if you want to add info from `OAuth2Authorization` to access token response, you have to copy the entirety of `OAuth2AuthorizationCodeAuthenticationProvider` and add what you need to the `additionalParameters`. You can't use a custom access token response handler as you don't have access to the `OAuth2Authorization` in there.

**Comment by jgrandja** [comment]
@Sm0keySa1m0n I don't feel another lookup is a workaround, however, I agree a secondary call to `OAuth2AuthorizationService` is not ideal.

There is a related issue in gh-925. Can you please log your specific use case there and then we can consider a holistic solution to address both uses cases. Thanks.
