### ISSUE TITLE
Allow wildcards in redirectUris

### ISSUE THREAD

**Issue by michael-ylb** [spring-projects/spring-authorization-server#1001]
**Expected Behavior**

Wildcards in `redirectUris` of a `RegisteredClient` should be possible, e.g.
```
return RegisteredClient.withId(UUID.randomUUID().toString())
    .clientId("foobar")
    .clientSecret(passwordEncoder().encode("foobar"))
    .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
    .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
    .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
    .redirectUri("*")     // allow everything 
    .redirectUri("https://*.mydomain.com/auth/callback")   // allow various subdomains
    .scope(OidcScopes.OPENID)
    .build();
```

**Current Behavior**
Currently each `redirectUri` has to be a valid URI without wildcards (validated in `RegisteredClient`) and tested for a literal match (e.g. in `OAuth2AuthorizationCodeAuthenticationProvider`):
```
if (StringUtils.hasText(authorizationRequest.getRedirectUri()) &&
		!authorizationRequest.getRedirectUri().equals(authorizationCodeAuthentication.getRedirectUri())) {
	throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_GRANT);
}
```

**Context**

During development, we have various use cases, for example local hostnames, temporary host names in branch builds and so on. Parsing wildcards in the redirectUri seems to be a common use case in authorization servers, e.g. Keycloak.

**Comment by emilburzo** [comment]
@michael-ylb did you find a solution/work-around for this?

**Comment by michael-ylb** [comment]
Yes, you can customize like shown here: https://docs.spring.io/spring-authorization-server/docs/0.4.0/reference/html/protocol-endpoints.html#oauth2-authorization-endpoint-customizing-authorization-request-validation

You have to customize CustomRedirectUriValidator to your needs
