### ISSUE TITLE
Incorrect redirection behaviour Springboot Embedded Tomcat vs standalone Tomcat

### ISSUE THREAD

**Issue by javiiker** [spring-projects/spring-authorization-server#1007]
Hi team,

We have created a Oauth spring authorization server with the latest version compatible with **Spring security 5 (spring-security-oauth2-authorization-server-0.4.0)** under **Spring Boot 2.7.6**

When using the Spring Boot embedded Tomcat, it works like charm, but when the same code it's deployed in a standalone **Tomcat 9.0.70** version as a war package, once user has successfully logged we have detected that the redirection is not done correctly.

Looking into the logs, we can see that the authorization server behavior is different when using **Spring Boot embedded Tomcat**:

> 2022-12-15 19:28:07.310 DEBUG 14552 --- [0.1-8082-exec-7] o.s.s.w.csrf.CsrfAuthenticationStrategy  : Replaced CSRF Token
> 2022-12-15 19:28:07.310 DEBUG 14552 --- [0.1-8082-exec-7] w.a.UsernamePasswordAuthenticationFilter : Set SecurityContextHolder to UsernamePasswordAuthenticationToken [Confidential User Data]
> 2022-12-15 19:28:07.311 TRACE 14552 --- [0.1-8082-exec-7] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'delegatingApplicationListener'
> 2022-12-15 19:28:07.311 TRACE 14552 --- [0.1-8082-exec-7] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'refreshScopeRefreshedEventListener'
> 2022-12-15 19:28:07.311 TRACE 14552 --- [0.1-8082-exec-7] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'springApplicationAdminRegistrar'
> 2022-12-15 19:28:07.311 DEBUG 14552 --- [0.1-8082-exec-7] o.s.s.web.DefaultRedirectStrategy        : **Redirecting to XXXX (Confidential URI)**

Than when authorization server is deployed as war package in **standalone Tomcat 9.0.70**:

> 16:57:16.343 [https-openssl-apr-443-exec-73] DEBUG o.s.s.w.c.CsrfAuthenticationStrategy - Replaced CSRF Token
> 16:57:16.343 [https-openssl-apr-443-exec-73] DEBUG o.s.s.w.a.UsernamePasswordAuthenticationFilter - Set SecurityContextHolder to UsernamePasswordAuthenticationToken [Confidential User Data]
> 16:57:16.343 [https-openssl-apr-443-exec-73] TRACE o.s.s.w.a.SavedRequestAwareAuthenticationSuccessHandler - Using default url /
> 16:57:16.343 [https-openssl-apr-443-exec-73] DEBUG o.s.s.web.DefaultRedirectStrategy - **Redirecting to /**

Seems the cached data is not being loaded and so, it's redirecting to root page / instead of the original uri.

Right now we have our customized login page, but it happens also when using the  _.formLogin(Customizer.withDefaults())_

Don't know if it's really a bug related to the oauth server, but at least it's behaving different in the two situations above.

Thanks!

**Comment by jgrandja** [comment]
@javiiker The logs provided do not indicate usage of Spring Authorization Server endpoints. **NOTE:** `DefaultRedirectStrategy` is used by many different components within Spring Security.

And as you noted...

> Right now we have our customized login page, but it happens also when using the `formLogin(Customizer.withDefaults())`

Turn on `TRACE` for `org.springframework.security.oauth2` and you'll see if the OAuth2 Endpoints are being called.

However, I suspect this is environment specific.

If your problem persists then please provide more details on how you are deploying and a minimal reproducible sample and I can take a look further.
