### ISSUE TITLE
If the JWT token is used, and the request will show 401 error when the server restart

### ISSUE THREAD

**Issue by Waylon-Firework** [spring-projects/spring-authorization-server#1015]
**Describe the bug**
If the JWT token is used, and the request will show 401 error when the server restart.

If the server is not restarted, the jwt token can be used normally.

**Comment by kuschzzp** [comment]
I have the same question, why is the old access_token unavailable after the service is restarted

**Comment by ramonmalcolm10** [comment]
> **Describe the bug** If the JWT token is used, and the request will show 401 error when the server restart.
> 
> If the server is not restarted, the jwt token can be used normally.

Are you using a in-memory client? Also is the client id random?

**Comment by kuschzzp** [comment]
I find that the reason for the 401 error code is that the token cannot be resolved correctly.
For the first time, I found an obvious point that the `kid` had changed. So I modified the `Jwks.java` class：

```
    public static RSAKey generateRsa() {
        KeyPair keyPair = KeyGeneratorUtils.generateRsaKey();
        RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();
        RSAPrivateKey privateKey = (RSAPrivateKey) keyPair.getPrivate();
		return new RSAKey.Builder(publicKey)
				.privateKey(privateKey)

				//.keyID(UUID.randomUUID().toString())
				.keyID("my_key_id")

				.build();
    }
```
But later I found out that `RSAPublicKey` and `RSAPrivateKey` also change when the program is restarted, and I don't know how to encode these two values into the class file.  I would really appreciate it if you could give me some code examples. @ramonmalcolm10

**Comment by ramonmalcolm10** [comment]
> I find that the reason for the 401 error code is that the token cannot be resolved correctly. For the first time, I found an obvious point that the `kid` had changed. So I modified the `Jwks.java` class：
> 
> ```
>     public static RSAKey generateRsa() {
>         KeyPair keyPair = KeyGeneratorUtils.generateRsaKey();
>         RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();
>         RSAPrivateKey privateKey = (RSAPrivateKey) keyPair.getPrivate();
> 		return new RSAKey.Builder(publicKey)
> 				.privateKey(privateKey)
> 
> 				//.keyID(UUID.randomUUID().toString())
> 				.keyID("my_key_id")
> 
> 				.build();
>     }
> ```
> 
> But later I found out that `RSAPublicKey` and `RSAPrivateKey` also change when the program is restarted, and I don't know how to encode these two values into the class file. I would really appreciate it if you could give me some code examples. @ramonmalcolm10

Sorry for taking so long to respond. I will share in a few @kuschzzp

**Comment by Waylon-Firework** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/95599645/209858562-7299824d-e788-40aa-bec1-9ee22c40e744.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/95599645/209858596-fb12e776-0c23-4fc6-b6a1-a9c350b56ff1.png">
I use jks files. But still not work when restarting the server.

**Comment by ramonmalcolm10** [comment]
> <img alt="image" width="738" src="https://user-images.githubusercontent.com/95599645/209858562-7299824d-e788-40aa-bec1-9ee22c40e744.png">
> 
> <img alt="image" width="270" src="https://user-images.githubusercontent.com/95599645/209858596-fb12e776-0c23-4fc6-b6a1-a9c350b56ff1.png">
> 
> I use jks files. And I use the fixed key id: `".keyID("my_key_id")"`, then it works. Thank you @kuschzzp. I found my problem from your answer. I didn't keep the key ID unchanged on my side.

Is because you using a randomUUID for the keyId, change to a static value
