### ISSUE TITLE
About the performance problem of access_token verification

### ISSUE THREAD

**Issue by artugo** [spring-projects/spring-authorization-server#1025]
I have noticed that in the findByToken method of JdbcOAuth2AuthorizationService, when checking whether the token is correct, the SQL statement cannot use an index, and a new record will be generated in the oauth2_authorization table for each request. The access_token field of oauth2_authorization cannot be created index, so the data in this table will become very large over time, seriously affecting performance when checking the token. I want to extend RedisOAuth2AuthorizationService, but I found that the OAuth2Authorization class cannot be instantiated. I hope the official team will consider how to improve the performance of token validation. Thank you.

I have found that the SQL statement generated for checking the accuracy of the token is as follows:
SELECT
	id,
	registered_client_id,
	principal_name,
	authorization_grant_type,
	attributes,
	state,
	authorization_code_value,
	authorization_code_issued_at,
	authorization_code_expires_at,
	authorization_code_metadata,
	access_token_value,
	access_token_issued_at,
	access_token_expires_at,
	access_token_metadata,
	access_token_type,
	access_token_scopes,
	oidc_id_token_value,
	oidc_id_token_issued_at,
	oidc_id_token_expires_at,
	oidc_id_token_metadata,
	refresh_token_value,
	refresh_token_issued_at,
	refresh_token_expires_at,
	refresh_token_metadata from oauth2_authorization 
WHERE
	refresh_token_value = ?
	OR access_token_value = ?
	OR authorization_code_value = ?

The result of viewing the execution plan is as follows:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/109275325/209749227-c08056e5-8545-40e1-a1f9-bb97d1977f86.png">

**Comment by jgrandja** [comment]
@artugo As stated in this [comment](https://github.com/spring-projects/spring-authorization-server/issues/995#issuecomment-1344888214):

> `JdbcOAuth2AuthorizationService` is a simplified JDBC implementation that MAY be used in production. However, **the expectation is that the consuming application is responsible for implementing `OAuth2AuthorizationService` with whatever backing store of their choice.**

Closing as duplicate.

**Comment by artugo** [comment]
@jgrandja  thanks
