### ISSUE TITLE
Can you provide a Deserializer for OAuth2Authorization?

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [spring-projects/spring-authorization-server#1028]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by xuxiaowei-com-cn** [comment]
For processing https://github.com/spring-projects/spring-security/issues/4370

**Comment by jgrandja** [comment]
@xuxiaowei-com-cn Please see [comment](https://github.com/spring-projects/spring-authorization-server/issues/558#issuecomment-1361248920). Closing as duplicate.
