### ISSUE TITLE
gradle build with 0.2.0 but I get many dependencies error, how can i resolve it?

### ISSUE THREAD

**Issue by Lvbuqing** [spring-projects/spring-authorization-server#1032]
A problem occurred configuring root project 'spring-authorization-server'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.apache.xerces:xercesImpl:2.9.1.
     Required by:
         project : > io.spring.gradle:spring-build-conventions:0.0.38 > io.spring.gradle:docbook-reference-plugin:0.3.1
      > Could not resolve org.apache.xerces:xercesImpl:2.9.1.
         > Could not get resource 'https://repo.spring.io/plugins-snapshot/org/apache/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.pom'.
            > Could not GET 'https://repo.spring.io/plugins-snapshot/org/apache/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve org.apache.xerces:resolver:2.9.1.
     Required by:
         project : > io.spring.gradle:spring-build-conventions:0.0.38 > io.spring.gradle:docbook-reference-plugin:0.3.1
      > Could not resolve org.apache.xerces:resolver:2.9.1.
         > Could not get resource 'https://repo.spring.io/plugins-snapshot/org/apache/xerces/resolver/2.9.1/resolver-2.9.1.pom'.
            > Could not GET 'https://repo.spring.io/plugins-snapshot/org/apache/xerces/resolver/2.9.1/resolver-2.9.1.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by jgrandja** [comment]
@Lvbuqing `0.2.0` release is quite old now and is no longer supported.

Please checkout the [latest releases](https://spring.io/projects/spring-authorization-server#learn) or supported branches `0.4.x` or `main`.
