### ISSUE TITLE
Sleuth Aware Tracing

### ISSUE THREAD

**Issue by zhenchuan9r** [spring-projects/spring-authorization-server#1041]
**Expected Behavior**
Endpoints, especially token endpoint activities can be traced by Sleuth.

**Current Behavior**
Because endpoints are implemented by filters, sleuth cannot capture requests.

**Context**
To implement tracing on Spring Authorization Server, Sleuth seems not currently usable.
Some other solutions, like Skywalking may be used to enforce tracing feature.
However I hope Sleuth can be the official solution.
I am using Spring Boot 2.7.x series and SAS 0.3.1.
Thanks.

**Comment by jgrandja** [comment]
@zhenchuan9r Spring Authorization Server primary purpose is to provide a light-weight and customizable foundation for building OpenID Connect 1.0 Identity Providers and OAuth2 Authorization Server products. Product specific features would need to be implemented in the consuming application. Tracing and/or eventing is a type of product feature that would need to be implemented in the consuming application. Whether the application uses Spring Cloud Sleuth or another framework/library is up to the application.

Spring Authorization Server may consider adding specific extension point(s) that would help consuming applications implement a custom tracing feature.

**Comment by jgrandja** [comment]
@zhenchuan9r `TRACE` logging was added via gh-159
