### ISSUE TITLE
Revoking token doesn't clean the session of the user

### ISSUE THREAD

**Issue by medmsd** [spring-projects/spring-authorization-server#1047]
**Describe the bug**
When i call the RevokeToken API it makes the token inactive, but the session always remains, so when the user try to login again ( via web application for my case in ReactNative ) it automatically logins without showing the form as the user is already logged in

**To Reproduce**
- Login
- Logout ( Revoke Token )
- Try to Login again , it won't show the form, it will just login automatically

**Expected behavior**
- Login
- Logout ( Revoke Token )
- Login ( get the form again to fill the details to login again as there are no session for the user )

**Comment by jgrandja** [comment]
Closing as duplicate of gh-1022
