### ISSUE TITLE
Deprecate method provided in sample code

### ISSUE THREAD

**Issue by madhairsilence** [spring-projects/spring-authorization-server#1052]
Referring to [getting started](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html) link from the official website, the below code uses a deprecated method

```
@Bean 
	public UserDetailsService userDetailsService() {
		UserDetails userDetails = User.withDefaultPasswordEncoder()
				.username("user")
				.password("password")
				.roles("USER")
				.build();

		return new InMemoryUserDetailsManager(userDetails);
	}
```
This code can be replaced by 

```
@Bean 
	public UserDetailsService userDetailsService() {
		UserDetails userDetails = User.builder()
				.username("user")
				.password(bcryptEncoder().encode("password"))
				.roles("USER")
				.build();

		return new InMemoryUserDetailsManager(userDetails);
	}

@Bean
    public PasswordEncoder bcryptEncoder() {
        return new BCryptPasswordEncoder();
    }

```

**Comment by jgrandja** [comment]
@madhairsilence As per javadoc for `User.withDefaultPasswordEncoder()`:

> Deprecated
Using this method is not considered safe for production, **but is acceptable for demos and getting started**. For production purposes, ensure the password is encoded externally. See the method Javadoc for additional details. **There are no plans to remove this support. It is deprecated to indicate that this is considered insecure for production purposes.**

Note the bold text.

Although it's marked as deprecated, there are no plans to remove it. It's more of a marker to indicate to the user that it should not be used in production. However, it's fine to be used in demos or getting started experience.

I'm going to close this as the current usage is fine for the sample.
