### ISSUE TITLE
In OAuth2TokenEndpointFilter accessTokenHttpResponseConverter can change to a variable can be set up? This allows for external extension of requirements

### ISSUE THREAD

**Issue by luamas** [spring-projects/spring-authorization-server#1058]
**Expected Behavior**
You can dynamically adjust the json format of variant oauth2.

**Current Behavior**
The current format can only be fixed

**Context**
accessTokenHttpResponseConverter allows custom

if this solution is allowed through. I would like to contribute this code.
Set HttpMessageConverters to public

**Comment by jgrandja** [comment]
@luamas 

[authorizationServerConfigurer.tokenEndpoint.accessTokenResponseHandler()](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oauth2-token-endpoint) provides the ability to customize the OAuth 2.0 Access Token Response parameters.

There is an open issue gh-925 where we are considering simplifying the customization.

Closing this as a duplicate.
