### ISSUE TITLE
Support specifying a PasswordEncoder when multiple PasswordEncoder exists in OAuth2ClientAuthenticationConfigurer

### ISSUE THREAD

**Issue by HungUnicorn** [spring-projects/spring-authorization-server#1059]
**Expected Behavior**
The application has more than 1 PasswordEncoder, for example:

```
    @Bean("v1-encoder")
    fun v1Encoder(): PasswordEncoder {
        return V1PasswordEncoder()
    }

    @Bean("v0-encoder")
    fun v0Encoder(): PasswordEncoder {
        return V0PasswordEncoder()
    } 
```
and OAuth2ClientAuthenticationConfigurer can accept configuring a specific PasswordEncoder as the following

```
	authorizationServerConfigurer
		.clientAuthentication(clientAuthentication ->
			clientAuthentication
				.passwordEncoder(passwordEncder)  
				.authenticationConverters(authenticationConvertersConsumer) 
				.authenticationProvider(authenticationProvider) 
				.authenticationProviders(authenticationProvidersConsumer)   
				.authenticationSuccessHandler(authenticationSuccessHandler) 
				.errorResponseHandler(errorResponseHandler) 
		)
``` 

**Current Behavior**

Currently it throws error `Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a single bean, but 2 were found:

```
		PasswordEncoder passwordEncoder = OAuth2ConfigurerUtils.getOptionalBean(httpSecurity, PasswordEncoder.class);
		if (passwordEncoder != null) {
			clientSecretAuthenticationProvider.setPasswordEncoder(passwordEncoder);
```
https://github.com/spring-projects/spring-authorization-server/blob/1.0.0/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/config/annotation/web/configurers/OAuth2ClientAuthenticationConfigurer.java#L231

**Context**

Not aware of any workaround as `createDefaultAuthenticationProviders()` is called in `init()`. Would be glad to use the workaround as well.

**Comment by Hccake** [comment]
You can try to add `@Primary` annotation on the default `PasswordEncoder`.

```java
    @Primary
    @Bean("v1-encoder")
    fun v1Encoder(): PasswordEncoder {
        return V1PasswordEncoder()
    }
```

Or refer to `DelegatingPasswordEncoder` to write a delegate class to delegate the behavior of `v1Encoder` and `v0Encoder`

**Comment by HungUnicorn** [comment]
> You can try to add `@Primary` annotation on the default `PasswordEncoder`.
> 
> ```java
>     @Primary
>     @Bean("v1-encoder")
>     fun v1Encoder(): PasswordEncoder {
>         return V1PasswordEncoder()
>     }
> ```
> 
> Or refer to `DelegatingPasswordEncoder` to write a delegate class to delegate the behavior of `v1Encoder` and `v0Encoder`

I already tried and the same error. I think the code finds all PasswordEncoders and if > 1, the error is thrown

**Comment by jgrandja** [comment]
@HungUnicorn Can you provide more details on why you need 2x `PasswordEncoder`'s?

**Comment by HungUnicorn** [comment]
> @HungUnicorn Can you provide more details on why you need 2x `PasswordEncoder`'s?
Our app had the situation that cannot use DelegatingPasswordEncoder to guarantee rolling back, and relying on the new app to write the encoded passwords into two fields: password and passwordV1, so that rolling back is possible. 

For example, when the user signs up with the new version of app, which persists a row with the prefix {bcrypt-sha} in the database, after rolling back the user cannot login , because the older version of the application doesn’t know how to handle {bcrypt-sha}, and only the new version of application knows.

Indeed, this issue will disappear after the new version of app is stable and doesn't need to rollback, or the app uses DelegatingPasswordEncoder from the beginning.

**Comment by Hccake** [comment]
> For example, when the user signs up with the new version of app, which persists a row with the prefix {bcrypt-sha} in the database, after rolling back the user cannot login , because the older version of the application doesn’t know how to handle {bcrypt-sha}, and only the new version of application knows.
> 
> Indeed, this issue will disappear after the new version of app is stable and doesn't need to rollback, or the app uses DelegatingPasswordEncoder from the beginning.

Try the `DelegatingPasswordEncoder#defaultPasswordEncoderForMatches` property, which will fall back to using this encoder when the password has no prefix:
```java
Map<String, PasswordEncoder> encoders = new HashMap<>();
encoders.put("bcrypt-sha", v1PasswordEncoder);
DelegatingPasswordEncoder delegatingPasswordEncoder = new DelegatingPasswordEncoder("bcrypt-sha", encoders);
delegatingPasswordEncoder.setDefaultPasswordEncoderForMatches(v0PasswordEncoder);
```

**Comment by HungUnicorn** [comment]
> > For example, when the user signs up with the new version of app, which persists a row with the prefix {bcrypt-sha} in the database, after rolling back the user cannot login , because the older version of the application doesn’t know how to handle {bcrypt-sha}, and only the new version of application knows.
> > Indeed, this issue will disappear after the new version of app is stable and doesn't need to rollback, or the app uses DelegatingPasswordEncoder from the beginning.
> 
> Try the `DelegatingPasswordEncoder#defaultPasswordEncoderForMatches` property, which will fall back to using this encoder when the password has no prefix:
> 
> ```java
> Map<String, PasswordEncoder> encoders = new HashMap<>();
> encoders.put("bcrypt-sha", v1PasswordEncoder);
> DelegatingPasswordEncoder delegatingPasswordEncoder = new DelegatingPasswordEncoder("bcrypt-sha", encoders);
> delegatingPasswordEncoder.setDefaultPasswordEncoderForMatches(v0PasswordEncoder);
> ```

DelegatingPasswordEncoder is what already used and let's call it versionB and let's call versionA can only read bcrypt. 

DelegatingPasswordEncoder only supports to write one encoding and for sure it can read(match) multiple encodings, and it means rolling back to the previous app version(versionA) won't work, because versionA doesn't know doesn't know how to read(match) the password encoding written by bcrypt-sha, and those users signs up with versionB won't be able to sign in with versionA

this issues is temporary. once versionB(bcrypt-sha) is reliable and stable, there is no need to continue to write the old password encoding in the field password_version0 for rolling back to versionA(bcrypt) if necessary
