### ISSUE TITLE
Unique Authentication Errorhandling in Filter

### ISSUE THREAD

**Issue by GrmpfNarf** [spring-projects/spring-authorization-server#1065]
**Expected Behavior**
The errorhandling for authencation errors in all filters should be the same when the error is reported to the servlet.

**Current Behavior**
Currently most of the filters use the ``ServletResponse`` to publish the error via the Spring ErrorController.
```java
private void sendErrorResponse(HttpServletRequest request, HttpServletResponse response, AuthenticationException exception) throws IOException {
  ...
  OAuth2Error error = ((OAuth2AuthenticationException) exception).getError();
  response.sendError(someHttpStatus, error.toString());
  ...
}
```
But there are 6 filter which use ``OAuth2ErrorHttpMessageConverter`` to publish the ``OAuth2Error``. 
- OidcClientRegistrationEndpointFilter
- OidcUserInfoEndpointFilter
- OAuth2ClientAuthenticationFilter
- OAuth2TokenEndpointFilter
- OAuth2TokenIntrospectionEndpointFilter
- OAuth2TokenRevocationEndpointFilter

Is there any reason why there are two different implementations for the same error which also results in 2 different responses ?

**Context**
I try to handle the same errors at the same place and not in two different places. So the Spring ErrorController seems the right place for this.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by GrmpfNarf** [comment]
I'm Sorry,
I've taken another deeper look into the filters and realized the only filter who uses this way is the ``OAuth2AuthorizationEndpointFilter`` and this because of user interaction. I'm closing this issue.
