### ISSUE TITLE
add option to enable token refresh for public clients

### ISSUE THREAD

**Issue by Yneth** [spring-projects/spring-authorization-server#1076]
**Expected Behavior**
option on client that allows to toggle token refresh functionality for public client exists.

**Current Behavior**
token refresh is disabled via if and there is no option to change it from non library sources.

**Context**
We are trying to add refresh token capabilities for public clients. We already set up rotation logic and correct lifetimes for tokens and certificates.
As of right now to overcome that issue we created additional ClientAuthenticationMethod with corresponding ClientAuthentication converter and provider, that customize the OAuth2ClientAuthenticationFilter, allowing ClientAuthentication with new ClientAuthenticationMethod.

**Comment by sjohnr** [comment]
@Yneth thanks for reaching out!

From [this comment](https://github.com/spring-projects/spring-authorization-server/issues/297#issue-896744390):

> **There are no plans to implement refresh tokens for Public Clients**, as there are no browser APIs that allow refresh tokens to be stored in a secure way, which would result in an increased attack surface.

I'd encourage you to read the entire page available there including the final recommendation. Customization is currently the only way to enable this feature. With that in mind, I'm going to close this issue.

**Comment by mathieuruellan** [comment]
Actually i'm facing the same issue. The demo from okta for instance gives an refresh_token in the final callback.
In my context, the client is a native application . ios/android. platforms provide secured way to store the tokens.
