### ISSUE TITLE
Improve OpenID Connect 1.0 Logout Endpoint

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#1077]
- [x] Initialize `SessionRegistry` only if OIDC is enabled
- [x] Remove attribute `OidcLogoutAuthenticationToken.sessionInformation`
- [x] Add `OidcLogoutAuthenticationToken.isPrincipalAuthenticated()`
- [x] Add check to ensure ID Token is active before processing the logout request

Related gh-1068

**Comment by haojava** [comment]
@jgrandja Will this feature be added in 0.4.x ?

**Comment by jgrandja** [comment]
@haojava No. New features can only be added in `main` which is currently `1.1`. The `0.4.x` branch will accept bug and security fixes only.
