### ISSUE TITLE
Make redirectStrategy configurable

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-authorization-server#1079]
Hi, we are trying to migrate from spring-security-oauth authorization server.
We have currently the problem that the spring-authorization-server is doing a redirect instead of a forward to the consent-page. Our OAuth2 authorization request requires some custom-parameters that are not defined in RFC6749 (which is not prohibited by the specification). These parameters are lost in the coming redirect and therefore we are getting some problems.
We are generating some objects before the `AuthorizationEndpointFilter` is reached in our own custom-filter-implementations. These objects are necessary when the consent-page-endpoint is accessed. 

It would be great if the `RedirectStrategy`-object in the `OAuth2AuthorizationEndpointFilter` could be made configurable in order for us to do a forward instead of a redirect here since we need the pre-generated data based on our customized parameters from the OAuth2 AuthorizationRequest that are not maintained after the redirect.

EDIT:
I forgot to mention why this becomes a problem in our case. We cannot use a session in our case. There are some architectural stones in our way that prevents us from having user-sessions and thus we cannot store the data in the session.

**Comment by jgrandja** [comment]
@Captain-P-Goldfish 

> It would be great if the `RedirectStrategy`-object in the `OAuth2AuthorizationEndpointFilter` could be made configurable in order for us to do a forward instead of a redirect

`RedirectStrategy` is designed to be used for redirects not forwards as the name and operation imply `RedirectStrategy.sendRedirect()`.

Also, `OAuth2AuthorizationEndpointFilter.redirectStrategy` is used for the Authorization Response, Authorization Consent Response and Error Response, so even if we were to expose it, I'm not sure it would make sense since it's used in 3 different flows.

> Our OAuth2 authorization request requires some custom-parameters that are not defined in RFC6749 (which is not prohibited by the specification). These parameters are lost in the coming redirect and therefore we are getting some problems.

Can you provide more details so I can better understand your scenario and help come up with a solution.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
