### ISSUE TITLE
How-to: How to configiure errorResponseHandler in authorization-server

### ISSUE THREAD

**Issue by XuYaoAnansi** [spring-projects/spring-authorization-server#1102]
![1677258294567](https://user-images.githubusercontent.com/43718577/221242358-184b2d94-f413-413d-ba22-42f8675ebdc7.jpg)

**Comment by jgrandja** [comment]
@XuYaoAnansi Please provide details in this issue. I do not understand what you are asking/requesting.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
