### ISSUE TITLE
The endpoint oauth2/token always throws "error": "invalid_client" 

### ISSUE THREAD

**Issue by cristian-ig** [spring-projects/spring-authorization-server#1104]
**Describe the bug**
The oauth2/authorize endpoint works to retrieve the code but when I try to exchange it I always get invalid_client.
From what I've seen when debugging the user is tested against the RegisteredClients and it always fails.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/22623940/221400491-0f3fef0d-33ef-43fd-8b6a-2a1118cf1926.png">
It seems that the two set of credentials (username:password, client_id:code+code verifier) get mixed up.

**To Reproduce**
I've implemented a basic Authorization server, link to github provided.
1. Generate code verifier + code challange
2. Go to the browser with the url http://localhost:9000/oauth2/authorize?response_type=code&client_id=client&scope=openid&redirect_uri=http://spring.io/auth&code_challange=8swP0rbhMPVIa20T9JSHXPMOLE1TcbC_SHrjMqg7fL4&code_challenge_method=S256 with the code challange value replaced. Get redirected to springio with the code in the url. - works fine
3. Postman post request to oauth2/token with the following parameters:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/22623940/221400733-c6d398bf-257e-46d8-b54e-7a9c48d9ad21.png">
The username and password are base 64 encoded in the Authorization header
<img width="459" alt="image" src="https://user-images.githubusercontent.com/22623940/221400776-340735f5-ff83-4e49-8ceb-5dd73d5c0945.png">
Also tried with postman basic auth and get the same result.

**Expected behavior**
To get the access token.

**Actual behavior**
Response: {
    "error": "invalid_client"
}

**Sample**

[A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).
](https://github.com/cristian-ig/AuthCodeServer)
Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment]
@cristian-ig From what I can gather in your comments, the client is not authenticating at the token endpoint since you are not passing the client's credentials (only client_id and missing client_secret). Please review the [default sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#messages-sample) and the [spec](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#name-client-authentication-2) to understand how to setup the request parameters.
