### ISSUE TITLE
Zenhub project board can't be accessed

### ISSUE THREAD

**Issue by appchemist** [spring-projects/spring-authorization-server#1107]
**Describe the bug**

Zenhub project board can't be accessed by the [link](https://app.zenhub.com/workspaces/authorization-server-5e8f3182b5e8f5841bfc4902/board?repos=248032165) in README.adoc.
Zenhub shows "This Workspace cannot be loaded".

> This project uses [ZenHub](https://www.zenhub.com/) to prioritize the feature roadmap and help organize the project plan. The project board can be accessed [here](https://app.zenhub.com/workspaces/authorization-server-5e8f3182b5e8f5841bfc4902/board?repos=248032165). It is recommended to install the ZenHub [browser extension](https://www.zenhub.com/extension) as it integrates natively within GitHub’s user interface.

**Comment by jgrandja** [comment]
@appchemist Please ask ZenHub for support [here](https://help.zenhub.com/support/home)
