### ISSUE TITLE
Can this use in a webflux project?

### ISSUE THREAD

**Issue by 1760793695** [spring-projects/spring-authorization-server#1114]
Can this use in a webflux project?

**Comment by jgrandja** [comment]
Closing as duplicate of gh-152. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644).

**Comment by 1760793695** [comment]
> Closing as duplicate of gh-152. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644).

thanks,i got know
