### ISSUE TITLE
Cannot remove `kid` and `x5t#S256` from `jwsHeader` using `OAuth2TokenCustomizer`

### ISSUE THREAD

**Issue by emilburzo** [spring-projects/spring-authorization-server#1133]
**Describe the bug**
Cannot remove `kid` and `x5t#S256` from `jwsHeader` using `OAuth2TokenCustomizer`

**To Reproduce**
```kotlin
    @Bean
    fun jwtCustomizer(): OAuth2TokenCustomizer<JwtEncodingContext> {
        return OAuth2TokenCustomizer { context: JwtEncodingContext ->
            val header = context.jwsHeader
            header.type(HEADER_TYP_JWT)
            header.headers { headerMap ->
                println(headerMap.containsKey("kid"))
                println(headerMap.containsKey("x5t#S256"))
            }
        }
    }
```

I can successfully add another header, but removing does not work as it seems `kid` and `x5t#S256` are not present when the `OAuth2TokenCustomizer` is applied, I assume they are added later.

**Comment by emilburzo** [comment]
After digging through the code, it seems this happens because `org.springframework.security.oauth2.jwt.NimbusJwtEncoder#addKeyIdentifierHeadersIfNecessary` is called from `org.springframework.security.oauth2.jwt.NimbusJwtEncoder#encode` after the customizations have been applied in `org.springframework.security.oauth2.server.authorization.token.JwtGenerator#generate`

It would be great if the customization would be applied after `addKeyIdentifierHeadersIfNecessary`, but I imagine that's not so trivial.

For others stumbling upon this, workarounds I've identified:
- use a custom `JwtEncoder` 
  - should work, quite a lot of code to reimplement
- change the `RSAKey` loading logic for `JWKSource<SecurityContext>` to forcefully set `keyID` and `x509CertSHA256Thumbprint` to `null` 
  - it seems like the easiest, with the caveat that key rotation might be more difficult

**Comment by jgrandja** [comment]
@emilburzo 

> Cannot remove `kid` and `x5t#S256`

I'd like to understand your use case better. Why do you need to remove the `kid` and/or `x5t#S256`?

There needs to be a unique identifier (`kid`) for a `Jwk`, when it's used to generate a `JWS`.

**Comment by emilburzo** [comment]
@jgrandja 

> I'd like to understand your use case better. Why do you need to remove the kid and/or x5t#S256?

I'm currently rewriting an existing service, using the EOL https://github.com/spring-attic/spring-security-oauth, which is used by lots of 3rd parties -- that makes any change quite painful due to the amount of coordination required.

As such, as a first step I'm trying to keep everything identical from an API perspective until we can provide an easier opt-in upgrade path. 

I was really hoping at least the JWT header is something where new fields can be added uneventfully, but this triggers extra validation in some libraries which in turn causes the otherwise valid JWT to be rejected. I could attempt to fix the validation issue for the case already discovered, but it's not feasible to check all libraries that everyone is using.

I hope that helped, let me know if any further details would be useful.

**Comment by jgrandja** [comment]
Thanks for the details @emilburzo.

The [workarounds](https://github.com/spring-projects/spring-authorization-server/issues/1133#issuecomment-1480706644) you identified are your best option at this point.
