### ISSUE TITLE
In cluster, data is inconsistent: JwtClientAssertionDecoderFactory  use a 'ConcurrentHashMap' to cache 'JwtDecoder'

### ISSUE THREAD

**Issue by loren-coding** [spring-projects/spring-authorization-server#1135]
**Describe the bug**
In a clustered environment, use 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer' login authentication model, adjusted during the client secret key, don't restart the service will lead to the secret key does not agree with the database.

![image](https://user-images.githubusercontent.com/49785430/227463385-22afb79a-69aa-4c16-af96-6d9e7ea4c827.png)
![image](https://user-images.githubusercontent.com/49785430/227463458-27c7c4ca-966f-4066-9d4d-d3a764b7ef27.png)
![image](https://user-images.githubusercontent.com/49785430/227463535-b63fd091-6315-4ebc-8607-89f33cbfb10b.png)

**Comment by jgrandja** [comment]
@loren-coding 

`JwtClientAssertionAuthenticationProvider.setJwtDecoderFactory(JwtDecoderFactory<RegisteredClient>)` was added in gh-944 to allow for a custom implementation to be configured.

For your scenario, if a client secret can be updated at runtime then you will need to provide a custom implementation similar to `JwtClientAssertionDecoderFactory` to meet your requirements.

Also see related issue gh-897
