### ISSUE TITLE
OAuth2AuthorizationEndpointFilter cover authentication.details when used BasicAuthenticationConverter

### ISSUE THREAD

**Issue by zsh9527** [spring-projects/spring-authorization-server#1137]
**OAuth2AuthorizationEndpointFilter cover authentication.details when used BasicAuthenticationConverter**
I used customer authenticationDetailsSource generated details, saved to UsernamePasswordAuthenticationToken.
But OAuth2AuthorizationEndpointFilter used self authenticationDetailsSource conver details. 
```
Authentication authentication = this.authenticationConverter.convert(request);
			if (authentication instanceof AbstractAuthenticationToken) {
				((AbstractAuthenticationToken) authentication)
						.setDetails(this.authenticationDetailsSource.buildDetails(request));
			}
```

**Comment by jgrandja** [comment]
@zsh9527 

> I used customer authenticationDetailsSource generated details, saved to UsernamePasswordAuthenticationToken.

You can set `OAuth2AuthorizationEndpointFilter.setAuthenticationDetailsSource()` using the same `BasicAuthenticationConverter.getAuthenticationDetailsSource()` by configuring an `ObjectPostProcessor<OAuth2AuthorizationEndpointFilter>`.

See gh-629 as it demonstrates the same configuration for `OAuth2TokenEndpointFilter`.
