### ISSUE TITLE
OAuth2ClientAuthenticationToken can not deserialize

### ISSUE THREAD

**Issue by UFO233** [spring-projects/spring-authorization-server#1155]
post：/oauth2/token
java.lang.IllegalArgumentException: The class with org.springframework.security.oauth2.server.authorization.authentication.OAuth2ClientAuthenticationToken and name of org.springframework.security.oauth2.server.authorization.authentication.OAuth2ClientAuthenticationToken is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details.

how to solve this problem? @joshlong

**Comment by jgrandja** [comment]
@UFO233 Please do not double post gh-1151.

Closing this as a duplicate. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/883#issuecomment-1245896451) for details.

**Comment by burakbalim** [comment]
it is not a duplicate, it is a spring-authorization-server issue, my configuration is like that

   @Bean
    public OAuth2AuthorizationService authorizationService() {
        JdbcOAuth2AuthorizationService jdbcOAuth2AuthorizationService = new JdbcOAuth2AuthorizationService(jdbcTemplate, registeredClientRepository());
        return jdbcOAuth2AuthorizationService;
    }
    
error position is like below --> JdbcOAuth2AuthorizationService.class

private Map<String, Object> parseMap(String data) {
			try {
				return this.objectMapper.readValue(data, new TypeReference<Map<String, Object>>() {});
			} catch (Exception ex) {
				throw new IllegalArgumentException(ex.getMessage(), ex);
			}
		}

**Comment by burakbalim** [comment]
Hi, you need to write own mixin method/class to deserialize the o
