### ISSUE TITLE
reactive AuthorizationServerContextHolder.getContext is null

### ISSUE THREAD

**Issue by pigping88** [spring-projects/spring-authorization-server#1202]
spring security 6 + webflux + spring-authorization-server 1.0.2

public Mono<Authentication> authenticate(Authentication authentication) {
          .....
         DefaultOAuth2TokenContext.Builder tokenContextBuilder = DefaultOAuth2TokenContext.builder()
                .registeredClient(client)
                .authorizationServerContext(AuthorizationServerContextHolder.getContext())
                .authorizationGrantType(AuthorizationGrantType.JWT_BEARER)
                .principal(principal);
}

webflux AuthorizationServerContextHolder.getContext() is null.  It's ok within mvc.
I need the context to generate jwt access_token and refresh_token

**Comment by sjohnr** [comment]
@pigping88, see [this comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644) and note that this project does not support webflux. I'm going to close this as a duplicate of gh-152.
