### ISSUE TITLE
JdbcRegisteredClientRepository should not write JDK classes to the database

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-authorization-server#1206]
**Expected Behavior**

`JdbcRegisteredClientRepository` should not write class names into the database. There should be an out of the box way to save the values without including the class names. 

It is not ideal to leak the domain model into the database unless necessary (eg you do not know the types that are being persisted and need to support generic serialization/deserialization). This is the equivalent of using blobs for objects and only slightly better than using `ObjectMapper` to write `RegisteredClient` into a single column.

**Current Behavior**

Currently `JdbcRegisteredClientRepository` `writeMap` uses `ObjectMapper` which serializes the map as a JSON string and includes  the JDK classes that are used. For example, token settings looks like:

```
{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}
```

**Context**

There is a lot of extra data written to the database and it leaks the object model into the persistence layer.

**Comment by jgrandja** [comment]
@rwinch `TokenSettings` and `ClientSettings` don't have associated Mixin's, hence the reason for the class names being serialized.

The intent behind `JdbcRegisteredClientRepository` is to provide a simplified JDBC implementation that can be customized however users want. The `registeredClientParametersMapper` and `registeredClientRowMapper` provide the hook for customization. Furthermore, the following test demonstrates how users can alter the db schema if they prefer not to go with the flattened approach:

https://github.com/spring-projects/spring-authorization-server/blob/6eeca4942849681d763facbcaa673bcc1796790b/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/client/JdbcRegisteredClientRepositoryTests.java#L262

Again, this is meant to be a simplified JDBC implementation that can be customized however users wish. However, there is a high likelihood that production applications will provide their own implementation of `RegisteredClientRepository` that persists using another approach other than JDBC and/or relational store.

I'm going to close this as the current implementation works and can be customized if users choose to do so.
