### ISSUE TITLE
CustomUserDetails  is not in the allowlist 

### ISSUE THREAD

**Issue by Been24** [spring-projects/spring-authorization-server#1221]
**Describe the bug**
When I user CustomUserDetails in Spring-Authorization-Server. JdbcOAuth2AuthorizationService$OAuth2AuthorizationRowMapper.parseMap() 
throws IllegalArgumentException with Class CustomUserDetails is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details.

**To Reproduce**
use CustomUserDetails instead of InMemoryUserDetails in authorization-server

**Comment by jgrandja** [comment]
Closing this as a duplicate. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/883#issuecomment-1245896451) for details.

**Comment by sdack-cloud** [comment]
I have also encountered this issue, with so many questions about Jackson2. The official should provide an example of Jackson2 on how to deserialize using UserDetails
@jgrandja

**Comment by uniquejava** [comment]
Then how to use custom user details. I think for non-demo project, this is a must.
