### ISSUE TITLE
ID Token missing sid claim after refresh_token grant

### ISSUE THREAD

**Issue by IwantDomore** [spring-projects/spring-authorization-server#1224]
**Describe the bug**

After using the refresh token, the obtained id_token does not contain the claim of sid, because there is no sid field, I failed to log out, because the sid field was verified in the logout logic

**To Reproduce**

1.Get authorization code
  
I use the /oauth2/authorize authorization endpoint in the browser to get the code

![1](https://github.com/spring-projects/spring-authorization-server/assets/40436060/7a002a23-78d7-41d5-ae6d-e25f5a219fc5)

2.Obtain token using authorization code

![2](https://github.com/spring-projects/spring-authorization-server/assets/40436060/b606ceec-afe3-4b15-bb14-56397a2a6dbd)

3.Parse the id_token and find that the id_token obtained using the authorization code mode contains the claim sid

![3](https://github.com/spring-projects/spring-authorization-server/assets/40436060/9b4f1722-dd7c-4cb9-8386-2977f5e2f4e8)

4.Use refresh_token to reacquire token

![4](https://github.com/spring-projects/spring-authorization-server/assets/40436060/0694d3f5-a754-4808-b40c-ed6f332573b1)

5.Parse the id_token again and find that there is no sid field

![5](https://github.com/spring-projects/spring-authorization-server/assets/40436060/03f52a13-d69b-4612-a6e5-8b34dea07193)

6.The id_token needs to be used when logging out, but the id_token parsed in the background does not contain the sid claim and an error is reported

![58502e9ac5e53ed5cd9a83d2b470b89](https://github.com/spring-projects/spring-authorization-server/assets/40436060/35d8899c-d141-4d0f-8c34-a999d9481111)

**Expected behavior**
1.Through the general browsing code, it is found that in the token obtained in the authorization code mode, the sid will be added to the claim when it is judged that the seesionInfomation exists, but the sid is not added when the token is constructed using the refresh token mode.

2.Hope the author can check and solve my difficulty, thank you very much.

**Comment by zjyhaha666** [comment]
Perhaps it is necessary to add this piece of code in the authenticate() method of OAuth2RefreshTokenAuthenticationProvider as well：```
SessionInformation sessionInformation = getSessionInformation(principal);
			if (sessionInformation != null) {
				try {
					// Compute (and use) hash for Session ID
					sessionInformation = new SessionInformation(sessionInformation.getPrincipal(),
							createHash(sessionInformation.getSessionId()), sessionInformation.getLastRequest());
				} catch (NoSuchAlgorithmException ex) {
					OAuth2Error error = new OAuth2Error(OAuth2ErrorCodes.SERVER_ERROR,
							"Failed to compute hash for Session ID.", ERROR_URI);
					throw new OAuth2AuthenticationException(error);
				}
				tokenContextBuilder.put(SessionInformation.class, sessionInformation);
```

**Comment by jgrandja** [comment]
Thank you for reporting this @IwantDomore. I just pushed the fix.
