### ISSUE TITLE
OpenID Nonce passed through, but duplicate values not rejected.

### ISSUE THREAD

**Issue by SkyAndyToone** [spring-projects/spring-authorization-server#1239]
**Describe the bug**
Passing a nonce value into an authorization request correctly returns that value in the ID Token. However, using the same nonce value in a subsequent request does not cause the request to be rejected.

**To Reproduce**

Authenticate to an OpenID client with a nonce value of "FIXED" and receive an ID Token with matching value.

Authenticate a second time with the same user/client/nonce value.

**Expected behavior**

The second authentication attempt should be rejected.

Note that it's also expected that there should be some way to configure duration for which nonces are retained, but there appears no documentation for the feature.

**Comment by jgrandja** [comment]
@SkyAndyToone As per [Section 2.  ID Token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken):

> nonce
String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. If present in the ID Token, Clients MUST verify that the nonce Claim Value is equal to the value of the nonce parameter sent in the Authentication Request. **If present in the Authentication Request, Authorization Servers MUST include a nonce Claim in the ID Token with the Claim Value being the nonce value sent in the Authentication Request. Authorization Servers SHOULD perform no other processing on nonce values used.** The nonce value is a case sensitive string.

As defined in the spec, the AS passes the `nonce` value as-is in the ID Token and performs **no other processing** (no validation). **The client is responsible for validating** the ID token, which includes validating the `nonce`.

I'll close this issue as it's been implemented to spec.

**Comment by SkyAndyToone** [comment]
Thank you, I appreciate the clarification.
