### ISSUE TITLE
Support for RFC 8693 Token Exchange

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-authorization-server#1242]
**Expected Behavior**
The OAuth2 Token Exchange extension defines a mechanism for a client to obtain its own tokens given a separate set of tokens.
It uses the `grant_type=urn:ietf:params:oauth:grant-type:token-exchange` and is performed via the `token_endpoint`.
Users could exchange an access-token / refresh-token obtained from an different issuer, for a different client for another token (refresh-token access-token) from this issuer for a target client. The exchange strategy should be plugable, such that users can implement different use-cases such as delegation and impersonation use-cases as described in the RFC-8693.

The support for token-exchange should also be exposed via the .well-known configuration endpoint.

**Current Behavior**
Token-Exchange is not supported out of the box. As a workaround users can add a custom `AuthorizationGrantType` with `urn:ietf:params:oauth:grant-type:token-exchange` and implement the necessary plumbing.

**Context**
See: https://datatracker.ietf.org/doc/html/rfc8693
See: https://oauth.net/2/token-exchange/
See: https://connect2id.com/products/nimbus-oauth-openid-connect-sdk/examples/oauth/token-exchange

I'd like to use standard functionality to exchange a short-lived access-token / refresh-token from an OpenID provider obtained from an authorization-code flow in a browser-context to longer lived access-token / refresh-token with more reliable and  scalable handling of sessions managed via spring-authorization-server.

Other scenarios are delegation and impersonation use-cases within the spring-authorization-server, e.g. switch user, switch-client, elevate scopes etc.

**Comment by jgrandja** [comment]
@thomasdarimont This feature request has been logged in gh-60. Feel free to add further comments in the issue.

I'll close this as a duplicate.
