### ISSUE TITLE
Consider logging invalid client secret

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-authorization-server#1246]
https://github.com/spring-projects/spring-authorization-server/blob/27a893fbeea7ec1f8ebb85be9242f17b24223e72/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/ClientSecretAuthenticationProvider.java#L116-L118

We should consider adding a log entry at DEBUG level in `ClientSecretAuthenticationProvider` for this case. This would allow the logging level to be tuned specifically for this logging.

**Comment by fndejan** [comment]
Hi @sjohnr, can I take this issue?
