### ISSUE TITLE
Introspect and refresh token end point does not work with AD Authentication

### ISSUE THREAD

**Issue by encyclopedi2a** [spring-projects/spring-authorization-server#1254]
Authorization server successfully gives the token and store in SQL server database but during introspect endpoint and refresh token endpoint it gives following error 

java.lang.IllegalArgumentException: The class with org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap and name of org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details

The above issue does not exist  with in memory authentication.

**Comment by jgrandja** [comment]
Closing this as a duplicate. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/883#issuecomment-1245896451) for details.
