### ISSUE TITLE
Data in the oauth2_authorization table keeps increasing

### ISSUE THREAD

**Issue by Moss-Lee** [spring-projects/spring-authorization-server#1256]
**Describe the bug**
Rows are inserted every time the authorization is successful, shouldn't they be deleted after the token expires

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment]
Closing as duplicate gh-873
