### ISSUE TITLE
authenticationDetailsSource in OAuth2ClientAuthenticationFilter should be configurable

### ISSUE THREAD

**Issue by sismik** [spring-projects/spring-authorization-server#1265]
**Expected Behavior**
OAuth2ClientAuthenticationFilter should use customized authenticationDetailsSource.

**Current Behavior**
Custom authenticationDetailsSource for OAuth2ClientAuthenticationFilter can't be set from OAuth2AuthorizationServerConfigurer.

**Context**
I want to implement custom WebAuthenticationDetails to support remote ports. I can set it for HttpSecurity.formLogin and HttpSecurity.oauth2Login, but I would also like to set it for OAuth2ClientAuthenticationFilter.

**Comment by sismik** [comment]
Thank you, that works.

**Comment by sealte** [comment]
Perhaps OAuth2TokenRevocationEndpointFilter needs to obtain the client's IP from HttpServletRequest. I found that the code for setting WebAuthenticationDetailsSource in the revoke process has only appeared in OAuth2ClientAuthenticationFilter, so there needs to be an entry to configure OAuth2ClientAuthenticationFilter.authenticationDetailsSource
