### ISSUE TITLE
Cros error regarding PKCE

### ISSUE THREAD

**Issue by sdack-cloud** [spring-projects/spring-authorization-server#1287]
Using PKCE according to document configuration, there was an error submitting the login page

# How-to: Authenticate using a Single Page Application with PKCE

```
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	@Order(1)
	public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http)
			throws Exception {

		return http.cors(Customizer.withDefaults()).build();
	}

	@Bean
	@Order(2)
	public SecurityFilterChain defaultSecurityFilterChain(HttpSecurity http)
			throws Exception {

		return http.cors(Customizer.withDefaults()).build();
	}

	@Bean
	public CorsConfigurationSource corsConfigurationSource() {
		UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
		CorsConfiguration config = new CorsConfiguration();
		config.addAllowedHeader("*");
		config.addAllowedMethod("*");
		config.addAllowedOrigin("http://127.0.0.1:4200");
		config.setAllowCredentials(true);
		source.registerCorsConfiguration("/**", config);
		return source;
	}

}
```

The authorization server address is not in the AllowedOrigin list

Error

![image](https://github.com/spring-projects/spring-authorization-server/assets/49465225/a73dbbd5-75cf-44e1-8beb-28e59ac36c12)

**Comment by jgrandja** [comment]
@sdack-cloud The sample code you provided is incomplete. Take a look at the bottom of the [Enable CORS](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-pkce.html#enable-cors) section and you will see the Tip:

> Click on the "Expand folded text" icon in the code sample above to display the full example.

Also, running the following test demonstrates the configuration is correct:

https://github.com/spring-projects/spring-authorization-server/blob/a74f90d2dfa708bbae5c3890a9a7323902493d64/docs/src/docs/asciidoc/examples/src/test/java/sample/pkce/PublicClientTests.java#L45

I'll close this as the sample code in the guide is working as expected.

**Comment by vskiadas90** [comment]
> @sdack-cloud The sample code you provided is incomplete. Take a look at the bottom of the [Enable CORS](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-pkce.html#enable-cors) section and you will see the Tip:
> 
> > Click on the "Expand folded text" icon in the code sample above to display the full example.
> 
> Also, running the following test demonstrates the configuration is correct:
> 
> https://github.com/spring-projects/spring-authorization-server/blob/a74f90d2dfa708bbae5c3890a9a7323902493d64/docs/src/docs/asciidoc/examples/src/test/java/sample/pkce/PublicClientTests.java#L45
> 
> I'll close this as the sample code in the guide is working as expected.

For anybody struggling with CORS, the documentation pointed above is the key, and more specifically, what was missing for me was these line in the respecfive securityFilterChain configs: 		return http.cors(Customizer.withDefaults()).build();
