### ISSUE TITLE
README describes a non-functional install step

### ISSUE THREAD

**Issue by ddubson** [spring-projects/spring-authorization-server#1298]
**Describe the bug**

README section that guides the user to install dependencies into local Maven cache no longer works. A replacement command is needed, potentially `./gradlew check` or something similar.

**To Reproduce**

Go to [README install section](https://github.com/spring-projects/spring-authorization-server#install-all-spring--jars-into-your-local-maven-cache), and run the `install` Gradle task as described. Gradle wrapper then throws: 

```text
FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in root project 'spring-authorization-server'. Some candidates are: 'npmInstall'.
```

**Expected behavior**

Maven dependencies of the entire project are preloaded into local Maven cache, and task succeeds.

**Comment by sjohnr** [comment]
Thanks @ddubson! The command is `./gradlew publishToMavenLocal` which comes from the bundled gradle plugin `MavenPublishPlugin`. Would you be interested in submitting a PR?

**Comment by ddubson** [comment]
@sjohnr sure thing, will submit.
