### ISSUE TITLE
code_challenge_methods_supported field not in openid-configuration endpoint

### ISSUE THREAD

**Issue by drunkcattt** [spring-projects/spring-authorization-server#1302]
**Expected Behavior**
The `code_challenge_methods_supported` field should be included in the `.well-known/openid-configuration` endpoint.

**Current Behavior**
Currently, the `code_challenge_methods_supported` field is only available in the `.well-known/oauth-authorization-server` endpoint, However, we typically only use auto-discovery when using OIDC clients.

**Context**
In popular identity providers like Keycloak and Google (e.g., https://accounts.google.com/.well-known/openid-configuration), the code_challenge_methods_supported field is included in the openid endpoint. Some clients, such as the OAuth4WebAPI library (https://github.com/panva/oauth4webapi), also support this field.

**Comment by jgrandja** [comment]
Thanks for the report @drunkcattt. Would you be interested in submitting a PR for this enhancement?

In the meantime, you can customize the OpenID Connect 1.0 Provider Configuration Endpoint and add the `code_challenge_methods_supported` metadata. See `providerConfigurationCustomizer()` in the [reference documentation](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oidc-provider-configuration-endpoint).

**Comment by drunkcattt** [comment]
[](url)
https://github.com/spring-projects/spring-authorization-server/blob/0a87e78bd1ac9e37f7c5d2c5f97de81c4d995085/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/CodeVerifierAuthenticator.java#L140-L158
#

#1329 

According to the processing logic of the `CodeVerifierAuthenticator`, I have directly added `.codeChallengeMethod("S256")` to the `OidcProviderConfigurationEndpointFilter`, similar to the `OAuth2AuthorizationServerMetadataEndpointFilter`.
