### ISSUE TITLE
How to set the default value of scope when Authorization Request?

### ISSUE THREAD

**Issue by 2252603132** [spring-projects/spring-authorization-server#1303]
**Expected Behavior**

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-4.1.1

**Current Behavior**

scope should have a default value when authorizing

**Context**
If no scope is set when authorizing the request
Now when i make the authorization request the error occurs
![image](https://github.com/spring-projects/spring-authorization-server/assets/85060647/b65314ef-59a5-443c-b414-973386d95dd6)

**Comment by 9527286768** [comment]
Label
