### ISSUE TITLE
Provide a mechanism to disable client authentication with token Introspection Endpoint 

### ISSUE THREAD

**Issue by wapkch** [spring-projects/spring-authorization-server#1307]
**Expected Behavior**

The token Introspection Endpoint can be accessed without client authentication

**Current Behavior**

The token Introspection Endpoint needs client authentication

**Context**

https://datatracker.ietf.org/doc/html/rfc7662#section-2.1:

> To prevent token scanning attacks, the endpoint MUST also require
   some form of authorization to access this endpoint, such as client
   authentication as described in OAuth 2.0 [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)] or a separate
   OAuth 2.0 access token such as the bearer token described in OAuth
   2.0 Bearer Token Usage [[RFC6750](https://datatracker.ietf.org/doc/html/rfc6750)].  The methods of managing and
   validating these authentication credentials are out of scope of this
   specification.

Although client authentication is used to prevent token scanning attacks, but if the token Introspection Endpoint is only exposed to a private network, it will not be a big issue. Hence for convenience, can we provide a mechanism disable client authentication?

**Comment by jgrandja** [comment]
@wapkch 

> The token Introspection Endpoint can be accessed without client authentication

This is already possible by customizing the default client authentication configuration. You could allow "Public Clients" to access the Token Introspection endpoint, very similar to how the `demo-authorizationserver` sample allows Public Client access to the Device Authorization endpoint and Token endpoint.

Take a look at `DeviceClientAuthenticationConverter` and how it's configure in via `clientAuthentication().authenticationConverter()`

https://github.com/spring-projects/spring-authorization-server/blob/0a87e78bd1ac9e37f7c5d2c5f97de81c4d995085/samples/demo-authorizationserver/src/main/java/sample/config/AuthorizationServerConfig.java#L95

You can create an `AuthenticationConverter` similar to `DeviceClientAuthenticationConverter` to achieve the same.
