### ISSUE TITLE
/connect/register returns http status 401 given unauthenticated request instead of 200

### ISSUE THREAD

**Issue by HungUnicorn** [spring-projects/spring-authorization-server#1322]
**Expected Behavior**
Returns http status 401 when calling `/connect/register` given unauthenticated request, as this endpoint is called from backend. 

**Current Behavior**
Returns http status 302 and then 200 after the redirection when calling `/connect/register` given unauthenticated request

**Context**
 `.oidcClientRegistrationEndpoint("url")` provides the ability to use `/connect/register` and reigster oauth2 client.
It currently redirects to the endpoint defined as the following:

```
        http
            .exceptionHandling { exceptions ->
                exceptions.authenticationEntryPoint(LoginUrlAuthenticationEntryPoint("/$ROUTE"))
            }
```

It creates false alarm in the tool OWASP API scan (https://www.zaproxy.org/docs/docker/api-scan/) as it returns 200.

my idea would resolve the issue as the following:

```
class OAuth2LoginUrlAuthenticationEntryPoint(loginFormUrl: String, settings: AuthorizationServerSettings) : LoginUrlAuthenticationEntryPoint(loginFormUrl) {
    override fun commence(
        request: HttpServletRequest,
        response: HttpServletResponse,
        authException: AuthenticationException
    ) {
        if (request.requestURI.contains(settings.getOidcClientRegistrationEndpoint()) {
            response.sendError(HttpServletResponse.SC_UNAUTHORIZED, authException.message)
        } else {
            super.commence(request, response, authException)
        }
    }
}
```

do you think this class should be supported in the library? if so, I can opend a PR.

**Comment by jgrandja** [comment]
@HungUnicorn 

> Returns http status 302 and then 200 after the redirection when calling `/connect/register` given unauthenticated request

The reason 302 is being returned is because you are attempting to access `http://localhost:9000/connect/register` directly from the browser. Dynamic Client Registration is not designed to be called by a browser agent. Instead the OAuth2 Client is meant to send a POST request to the `http://localhost:9000/connect/register` endpoint. Please review the [spec](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest) for more details.

**Comment by HungUnicorn** [comment]
> not quite. if the request is sent using `curl`, it returns 302 without following redirect or 200 following redirect.


not quite. if the request is sent using curl, it returns 302 without following redirect or 200 following redirect.



> @HungUnicorn
> 
> > Returns http status 302 and then 200 after the redirection when calling `/connect/register` given unauthenticated request
> 
> The reason 302 is being returned is because you are attempting to access `http://localhost:9000/connect/register` directly from the browser. Dynamic Client Registration is not designed to be called by a browser agent. Instead the OAuth2 Client is meant to send a POST request to the `http://localhost:9000/connect/register` endpoint. Please review the [spec](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest) for more details.


not quite. if the request is sent using `curl`, it returns 302 without following redirect or 200 following redirect.
