### ISSUE TITLE
After version 1.1.1, when continue parameter is prefilled, it is not possible to call the endpoint /token

### ISSUE THREAD

**Issue by Daniel100262** [spring-projects/spring-authorization-server#1333]
**Describe the bug**
After version 1.1.1, an implementation was changed and is causing a bug when parameter continue is submitted with URL. This implementation occours in [class `OAuth2AuthorizationCodeRequestAuthenticationConverter` in line 141 ](https://github.com/spring-projects/spring-authorization-server/compare/1.1.0...1.1.1).

After this, the request is being converted from an arraylist to a array of String, as below:

![image](https://github.com/spring-projects/spring-authorization-server/assets/6551994/64eaa5e5-00ca-4eb8-98b4-d5cc8be9eade)

After that, when the repository looks on database table for the authorization code to perform the exchange for a token, he find this on column `attributes` of `oauth2_authorization` table:

`&continue=%5BLjava.lang.String;@a598662` 

Then the String array has no serializer registered and the following error occurs:

![image](https://github.com/spring-projects/spring-authorization-server/assets/6551994/27b34bf6-579f-473a-ab93-f55c6caf6255)

Spring Security bug in "continue" parameter related here maybe affect that issue: https://github.com/spring-projects/spring-security/issues/13438

**To Reproduce**
Make an request to authorize endpoint with "continue" parameter using authorization code flow. After that, make an request to "token" endpoint to perform the exchange for a token.

**Expected behavior**
Make the exchange without any issues.

**Comment by jgrandja** [comment]
@Daniel100262 I ran the [demo sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#demo-sample), which appends the `continue` parameter (see attached), but was not able to reproduce the error.

![Continue-param](https://github.com/spring-projects/spring-authorization-server/assets/10884212/9c13a6d2-96a5-4fd2-90f7-d1aa947733a9)


Did you try it with the demo sample? Please provide more detailed steps on how to reproduce.

**Comment by Daniel100262** [comment]
Hello @jgrandja, I solved this problem by upgrading from Spring Boot from 3.1.1 to 3.1.2. This updates Spring Security to version 6.1.2, where there is already a fix for the "continue" case, which also solves the desserialization problem.

If anyone else is having this type of problem, this would be the solution.
