### ISSUE TITLE
For the oidc, we need the access_token and refresh_token from google/github

### ISSUE THREAD

**Issue by Waylon-Firework** [spring-projects/spring-authorization-server#1335]
**Expected Behavior**

For the oidc, we need the access_token and refresh_token from google/github. According the google development doc, we can get the access_token and refresh_token from google. But from the spring authorization server demo, we only see the id_token. We hope we can get the access_token and refresh_token.

https://developers.google.com/identity/openid-connect/openid-connect

<img width="921" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/95599645/55018f8f-55b2-4c6d-8c4a-047ccb8acae3">

**Current Behavior**
We only get the id_token.

**Comment by jgrandja** [comment]
@Waylon-Firework 

> But from the spring authorization server demo, we only see the id_token

The access token is being returned from the spring authorization server demo, otherwise, the demo would not work since the access token is passed to the resource server to retrieve the messages. The sample is working as expected.

**Comment by Waylon-Firework** [comment]
We need the google access token to request some google resource. Do you mean the authorization server will return the google access token? I tested it and it doesn't work. The access_token is spring authorization server token and not a google access_token.

**Comment by Waylon-Firework** [comment]
<img width="1057" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/95599645/f29cb48f-f62d-43a5-bb56-9d432aa53640">

**Comment by Waylon-Firework** [comment]
Hi @shanman190 . Sorry to bother you again. This question is closed. But I'd love to know the answer. Why doesn't oidc put google's access token (refresh token, etc), into the return value. Without access token/ refresh token, we will not be able to request google/github's api. We will have to ask the users to log in again. Could you please help me the answer. I'm confused。

**Comment by Waylon-Firework** [comment]
<img width="1236" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/95599645/c71a7820-d640-4830-bb2b-dee982639425">

**Comment by jgrandja** [comment]
@Waylon-Firework The access token and refresh token returned from Google is stored in `OAuth2AuthorizedClientRepository` within an instance of `OAuth2AuthorizedClient`. This is in the `oauth2-client` side of things, not Spring Authorization Server, since Google is acting as a client in the flow.

**Comment by Waylon-Firework** [comment]
I found the same requirement issue: https://github.com/spring-projects/spring-authorization-server/issues/700

(I copy it to this place.) Its description is as follows:

```
Context

The only justification for this request is that we have use cases where we really need to do federated OAuth2 rather than just federated OIDC. I.e. the access_token needs to be retained. The existing federated identity sample has code for both OIDC and OAuth2 (e.g. in the success handler) implying it was intended to support both, but the loss of the access_token in federated OAuth2 makes that scenario incomplete. In our use cases we often do federated OAuth2 with the idtoken scope included so that we are authenticating and also acquiring an access_token for subsequent API calls an external resource server that is associated with the upstream services.
```


We hope that the obtained Google access token and Google refresh token information can be retained in the OidcUser.

**Comment by Waylon-Firework** [comment]
Ignore this. I found the solution.  Thank you guys.
 
https://github.com/spring-projects/spring-authorization-server/issues/700#issuecomment-1775655840
