### ISSUE TITLE
Use the access token to access /oauth2/authorize

### ISSUE THREAD

**Issue by knightdreams6** [spring-projects/spring-authorization-server#1336]
**Expected Behavior**
OAuth2AuthorizationEndpointFilter should be after BearerTokenAuthenticationFilter

**Current Behavior**
Accessing /oauth2/authorize with access token failed

**Context**
I want to access /oauth2/authorize using access token

**Comment by jgrandja** [comment]
@knightdreams6 

> I want to access /oauth2/authorize using access token

The Authorization Endpoint does not accept access tokens. Please review the [spec](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#name-authorization-request) for details.
