### ISSUE TITLE
Failed /userinfo requests return too much information in response body

### ISSUE THREAD

**Issue by townsece** [spring-projects/spring-authorization-server#1341]
**Describe the bug**
When /userinfo endpoint fails with error, it returns all the error information in the response body. This is undesirable as it exposes info which could prove a security issue. It also directly contradicts the approach that Spring has taken regarding 4xx codes on /oauth2/introspect and /oauth2/revoke which do not disclose details of the error.

An example response body is below, with info redacted where it is identifying or sensitive:

`{"error_description":"OpenID Connect 1.0 UserInfo Error: The server failed planning the query {&quot;completed&quot;:true,&quot;coreId&quot;:&quot;redacted&quot;,&quot;errors&quot;:[{&quot;code&quot;:4000,&quot;message&quot;:&quot;No index available on keyspace default:{{redacted}}.authorisation that matches your query. Use CREATE PRIMARY INDEX ON default:{{redacted}}.authorisation to create a primary index, or check that your expected index is online.&quot;,&quot;retry&quot;:false}],&quot;httpStatus&quot;:404,&quot;idempotent&quot;:false,&quot;lastDispatchedFrom&quot;:&quot;{{redacted-ip}}:{{port}}&quot;,&quot;lastDispatchedTo&quot;:&quot;{{redacted.db.host}}:{{port}}&quot;,&quot;requestId&quot;:4490,&quot;requestType&quot;:&quot;QueryRequest&quot;,&quot;retried&quot;:0,&quot;service&quot;:{&quot;bucket&quot;:&quot;oauth-store&quot;,&quot;operationId&quot;:&quot;null&quot;,&quot;scope&quot;:&quot;redacted&quot;,&quot;statement&quot;:&quot;{{db-query}}&quot;,&quot;type&quot;:&quot;query&quot;},&quot;timeoutMs&quot;:75000,&quot;timings&quot;:{&quot;dispatchMicros&quot;:2571,&quot;totalDispatchMicros&quot;:2571,&quot;totalMicros&quot;:3049}}","error":"invalid_request","error_uri":"https://openid.net/specs/openid-connect-core-1_0.html#UserInfoError"}`

**To Reproduce**
Customise userinfo endpoint to return information on an index that doesn't exist
Call userinfo endpoint with valid access_token (with openid scope)

**Expected behavior**
Request fails with a serverside error
Error information is not exposed to client/end-user by default

**Sample**
Not provided

**Comment by jgrandja** [comment]
@townsece 

> Customise userinfo endpoint to return information on an index that doesn't exist

This scenario is highly unlikely to happen in a production environment or even a testing environment. The database backed by the `OAuth2AuthorizationService` is simply misconfigured because of a missing or invalid index. This would (should) quickly be discovered during development time, otherwise the application simply would not work.

Can you provide a more realistic production scenario where this can be an issue?
