### ISSUE TITLE
OAuth2Authorization.isActive() may return false because of time differences between servers (Deploying multiple replicas)

### ISSUE THREAD

**Issue by loren-coding** [spring-projects/spring-authorization-server#1346]
**Describe the bug**
version: 0.4.2

OAuth2Authorization.isActive() may return false because of time differences between servers (Deploying multiple replicas)

**To Reproduce**
I deployed two spring authorization server services, and when I requested '/userinfo', the occasional http request returned 401.
The log at the time was:
![image](https://github.com/spring-projects/spring-authorization-server/assets/49785430/3aae1286-bd36-413e-ab24-0fe1c3df25f1)

**Expected behavior**
Return user information

**Sample**
![image](https://github.com/spring-projects/spring-authorization-server/assets/49785430/29552cdb-fb5b-47f7-810b-4fe56c3bd6e6)

**Comment by ramonmalcolm10** [comment]
Don’t think this is a bug, how are you storing the session? When running multiple replicas, if you need shared state, you would need to have something to manage the state centrally like Redis

**Comment by loren-coding** [comment]
> Don’t think this is a bug, how are you storing the session? When running multiple replicas, if you need shared state, you would need to have something to manage the state centrally like Redis

Thank you for your answer.  Yes, I have used `spring session` and saved the session state to redis. But as long as the (multi-replica) `spring-authorization-server` service has inconsistent time between different servers, that problem arises, regardless of the session state

**Comment by loren-coding** [comment]
> **Describe the bug** version: 0.4.2
> 
> OAuth2Authorization.isActive() may return false because of time differences between servers (Deploying multiple replicas)
> 
> **To Reproduce** I deployed two spring authorization server services, and when I requested '/userinfo', the occasional http request returned 401. The log at the time was: ![image](https://user-images.githubusercontent.com/49785430/263594130-3aae1286-bd36-413e-ab24-0fe1c3df25f1.png)
> 
> **Expected behavior** Return user information
> 
> **Sample** ![image](https://user-images.githubusercontent.com/49785430/263592848-29552cdb-fb5b-47f7-810b-4fe56c3bd6e6.png)

The single node is running normally. Can you provide a solution that allows a second time difference between multiple nodes in cluster mode

**Comment by ramonmalcolm10** [comment]
I normally configured the pods timezone when deploying to Kubernetes. Are you able to do same?

**Comment by tofdragon** [comment]
The server directly needs to set time synchronization

![image](https://github.com/spring-projects/spring-authorization-server/assets/7513852/61587b24-a59c-44f3-9506-572078ea4364)

**Comment by jgrandja** [comment]
@loren-coding The issue you are having is environment related. You'll need to figure out a way to synchronize the time between the server instances.

**Comment by loren-coding** [comment]
> @loren-coding The issue you are having is environment related. You'll need to figure out a way to synchronize the time between the server instances.

thanks for the reply.  `OAuth2Authorization.isBeforeUse()`   the  `Instant.now.isBefore(Instant otherInstant)`  uses nanosecond comparisons, and the difference is small: 
```java
public boolean isBeforeUse() {
	Instant notBefore = null;
	if (!CollectionUtils.isEmpty(getClaims())) {
		notBefore = (Instant) getClaims().get("nbf");
	}
	return notBefore != null && Instant.now().isBefore(notBefore);
}
```

Maybe should add `clockSkew` like  `org.springframework.security.oauth2.jwt.JwtTimestampValidator`

**Comment by jgrandja** [comment]
@loren-coding 

> `OAuth2Authorization.isBeforeUse()`   the  `Instant.now.isBefore(Instant otherInstant)`  uses nanosecond comparisons, and the difference is small

I'm not sure this warrants an enhancement since "the difference is small". Is this a real issue when dealing with nanosecond comparisons?

> Maybe should add `clockSkew` like `org.springframework.security.oauth2.jwt.JwtTimestampValidator`

Adding `OAuth2Authorization.setClockSkew()` doesn't make sense from a design standpoint.

**Comment by arpadf78** [comment]
> Is this a real issue when dealing with nanosecond comparisons?

**This is a real issue.** The accuracy of the time does not matter. The only thing which matters is the server processing power compared to the time drift. Faster servers tolerate less time drift. There should be a way to configure the max allowed time drift.
