### ISSUE TITLE
Add setCustomizer method to DelegatingOAuth2TokenGenerator

### ISSUE THREAD

**Issue by Majuhwan** [spring-projects/spring-authorization-server#1359]
**Expected Behavior**
Can dynamically add OAuth2TokenCustomizer to the OAuth2AccessTokenGenerator within the provided Delegating OAuth2TokenGenerator.

**Current Behavior**
After the initial configuration, cannot inject OAuth2TokenCustomizer into the OAuth2AccessTokenGenerator within Delegating OAuth2TokenGenerator.

**Context**
Hello! While using the Spring Authorization server library, I encountered an inconvenience. The OAuth2AccessTokenGenerator allows us to inject an implementation class of OAuth2TokenCustomizer through its setAccessTokenCustomizer method. However, this functionality is not available for an OAuth2AccessTokenGenerator that is constructor-injected into a DelegatingOAuth2TokenGenerator. This limitation makes it difficult to add additional information to the Access token during the authentication process when using the DelegatingOAuth2TokenGenerator class.

To resolve this issue, I have added a setCustomizer method to the DelegatingOAuth2TokenGenerator, allowing dynamic configuration of the Customizer from classes implementing the AuthenticationProvider. I am currently using this functionality in my project and can provide an example if needed. If there is a reason this function cannot be added, please let me know. Thank you!

releated PR: https://github.com/spring-projects/spring-authorization-server/pull/1358

**Comment by jgrandja** [comment]
@Majuhwan See the reference for [OAuth2TokenCustomizer](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-token-customizer):

> If the `OAuth2TokenGenerator` is not provided as a `@Bean` or is not configured through the `OAuth2AuthorizationServerConfigurer`, an `OAuth2TokenCustomizer<OAuth2TokenClaimsContext>` `@Bean` will automatically be configured with an `OAuth2AccessTokenGenerator`.

So if you configure an `OAuth2TokenCustomizer<OAuth2TokenClaimsContext>` `@Bean` then it will be autowired into an `OAuth2AccessTokenGenerator` instance and supplied to the `DelegatingOAuth2TokenGenerator`.

If this doesn't work for you, please provide your configuration so I can better understand your issue.

**Comment by Majuhwan** [comment]
@jgrandja Thanks for reply 👍 
Let me explain to you what I want to add more clearly.

I learned from the source code that OAuth2TokenCustomizer can be configured as Bean. Below is an example of how to set up the OAuth2TokenCustomizer, which is shown in the document.
```
@Bean
public OAuth2TokenCustomizer<OAuth2TokenClaimsContext> accessTokenCustomizer() {
	return context -> {
		OAuth2TokenClaimsSet.Builder claims = context.getClaims();
		// Customize claims

	};
}
```

If I check the example, we can see that if we want to write code that works on claims, we need to write it at the time when spring boot registers @Bean.

The issue I want to talk about is when we want to dynamically generate data specific to the claims using OAuth2TokenCustomizer.
I will attach the code I wrote below. I wrote two classes, and I will explain each class's implementation intention.


CustomAccessTokenCustomizer has changed the CustomUser that was taken over from the creator to DTO so that it can be entered as a key called x_custom_userinfo.
```
@AllArgsConstructor
public class CustomAccessTokenCustomizer implements OAuth2TokenCustomizer<OAuth2TokenClaimsContext> {

    private final CustomUser customUser;

    public CustomAccessTokenCustomizer(CustomUser customUser) {
        this.customUser = customUser;
    }

    @Override
    public void customize(OAuth2TokenClaimsContext context) {
        if (context != null) {
            ClaimsBuilder claimsBuilder = context.getClaims();
            if (claimsBuilder != null) {
                claimsBuilder.claim("x_custom_userinfo", customUser.toDto());
            }
        }
    }
}
```


CustomDelegatingOAuth2TokenGenerator is almost identical to the existing DeregatingOAuth2TokenGenerator. Just added one setCustomizer function. This function allows you to add a customizer to the OAuth2AccessTokenGenerator that is already created.
```
public class CustomDelegatingOAuth2TokenGenerator<T extends OAuth2Token> implements OAuth2TokenGenerator<T> {

    private final List<OAuth2TokenGenerator<? extends T>> tokenGenerators;

    public CustomDelegatingOAuth2TokenGenerator(OAuth2TokenGenerator<? extends T>... tokenGenerators) {
        Assert.notEmpty(tokenGenerators, "tokenGenerators cannot be empty");
        Assert.noNullElements(tokenGenerators, "tokenGenerators cannot contain null elements");
        this.tokenGenerators = new ArrayList<>();
        Collections.addAll(this.tokenGenerators, tokenGenerators);
    }

    @Nullable
    @Override
    public T generate(OAuth2TokenContext context) {
        for (OAuth2TokenGenerator<? extends T> tokenGenerator : this.tokenGenerators) {
            T token = tokenGenerator.generate(context);
            if (token != null) {
                return token;
            }
        }
        return null;
    }

    public void setCustomizer(GeneratorType type, OAuth2TokenCustomizer<OAuth2TokenClaimsContext> customizer) {
        if (type == GeneratorType.ACCESS_TOKEN) {
            for (OAuth2TokenGenerator<? extends T> tokenGenerator : this.tokenGenerators) {
                if (tokenGenerator instanceof OAuth2AccessTokenGenerator) {
                    ((OAuth2AccessTokenGenerator) tokenGenerator).setAccessTokenCustomizer(customizer);
                }
            }
        }
    }

    public enum GeneratorType {
        ACCESS_TOKEN,
        REFRESH_TOKEN
    }
}
```



Using the two classes I wrote above, I was able to enter information from userDetails in the AuthenticationProvider implementation in the same way as below into the claims.

```
UserDetails userDetails = null;

try {
    userDetails = userService.loadUserByUsername(username, registeredClient.getClientId());
    if (userDetails != null) {
        ((CustomDelegatingOAuth2TokenGenerator) tokenGenerator).setCustomizer(
            CustomDelegatingOAuth2TokenGenerator.GeneratorType.ACCESS_TOKEN,
            new CustomAccessTokenCustomizer((CustomUser) userDetails)
        );
    }
} catch (Exception e) {
    e.printStackTrace();
}
```

This allows me to add user information to the claims as I wish. However, this approach cannot be resolved with the Degrating OAuth2TokenGenerator and customizer that were previously implemented. I created an issue and draft pull request to solve the above problems. The code for troubleshooting may not be neat. Please suggest if there is a solution to the problem I explained or if there is a better way you think. I can work on it if necessary.

**Comment by jgrandja** [comment]
@Majuhwan 

> This allows me to add user information to the claims as I wish.
 ...
 Please suggest if there is a solution to the problem I explained or if there is a better way you think.

The `OAuth2TokenContext` supplied to the `OAuth2TokenCustomizer` provides access to the currently authenticated principal via `OAuth2TokenContext.getPrincipal()`. This is where you would access user information and add as claims. Depending on the authentication mechanism configured (e.g. `formLogin()`) and the user service used (e.g. `UserDetailsService`) the returned user principal should contain all the information you would need to add to the claims set.

Furthermore, the `DelegatingOAuth2TokenGenerator` is not designed or intended to know about specific implementations of `OAuth2TokenGenerator` instances within it's internal list. Hence, the proposed updates in the PR cannot be accepted.

Although your solution above works, I would recommend obtaining user information from `OAuth2TokenContext.getPrincipal()`. You just need to ensure the authentication mechanism configured populates all the information you need into the user principal during the authentication process.

I hope this explanation helps?

I'm going to close this issue and associated PR as per explanation above.
