### ISSUE TITLE
Client registration access token rotation

### ISSUE THREAD

**Issue by atjohn-csam** [spring-projects/spring-authorization-server#1375]
**Expected Behavior**
Registration access token should be allowed to rotate. If the registration access token is expired, and the client still makes a call to register end point to view/modify client properties, it should be allowed.

**Current Behavior**
Now, as part of client registration service "registration_access_token" is shared. This access token has same expiry time as the token settings configured for that client. Once it expires, clients don't have a way of reading/managing the client properties.

**Context**
I have configured my clients to have short lived access tokens. Because the same token settings is considered while issuing the registration access token as well, the clients dont get to view/maintain their app after registration access token is expired.

**Comment by jgrandja** [comment]
@atjohn-csam The OpenID Connect Dynamic Client Registration 1.0 [specification](https://openid.net/specs/openid-connect-registration-1_0.html) does not state the requirement for access token rotation for `registration_access_token`, therefore, this would be a custom feature that would need to be implemented in the consuming application.

> I have configured my clients to have short lived access tokens. Because the same token settings is considered while issuing the registration access token as well, the clients dont get to view/maintain their app after registration access token is expired.

You can override the `exp` claim in the `registration_access_token` using a custom `OAuth2TokenCustomizer<JwtEncodingContext>` `@Bean`, for example:

```java
@Bean
public OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer() {
	return context -> {
		JwsHeader.Builder headers = context.getJwsHeader();
		JwtClaimsSet.Builder claims = context.getClaims();
		if (context.getTokenType().equals(OAuth2TokenType.ACCESS_TOKEN) &&
				context.getAuthorizedScopes().contains("client.read")) {
			claims.expiresAt(Instant.now().plus(7, ChronoUnit.DAYS));

		}
	};
}
```

I'm going to close this as the solution provided allows you to configure the TTL for the `registration_access_token`.

**Comment by atjohn-csam** [comment]
Though I can increase the time to live for registration access token as you suggested, I think having a rotation mechanism would be neat. I will look into adding the custom logic in my application, thanks for your inputs.
