### ISSUE TITLE
Inconsistency in the behavior of the token request when the grant_type parameter is incorrect

### ISSUE THREAD

**Issue by inseo24** [spring-projects/spring-authorization-server#1387]
**Describe the bug**

Currently, there is an inconsistency in the behavior of the token request handling for public and confidential clients when the grant_type parameter is incorrect. For confidential clients, an incorrect grant_type results in an unsupported_grant_type error, while for public clients, it leads to an Access Denied error. This inconsistency arises due to differences in how the converters handle the grant_type parameter, specifically, the AuthorizationFilter for public clients and the TokenEndpointFilter for confidential clients.

CodeVerifierAuthenticator also has validation logic for the grant type, which will return an invalid grant. We need to fix this as well to return the same result as confidential client.

**To Reproduce**

To reproduce the issue:

1. For a confidential client:
1.1 Send a token request with an incorrect grant_type, e.g., "foo".
1.2 Observe that it returns an unsupported_grant_type error.

2. For a public client (currently):
2.1 Send a token request with an incorrect grant_type, e.g., "foo".
2.2 Observe that it returns an Access Denied error. (invalid_grant)

3. For a public client (proposed change):
3.1 Send a token request with an incorrect grant_type, e.g., "foo".
3.2 Observe that it returns an unsupported_grant_type error (after applying the proposed logic change).

**Expected behavior**

The expected behavior is that both public and confidential clients should handle an incorrect grant_type parameter consistently. It should result in an unsupported_grant_type error in both cases. This change will ensure that public client requests are not denied at the converter level and instead undergo grant_type validation at the token endpoint, making the behavior more consistent between the two client types.

```
{
    "error_description": "OAuth 2.0 Parameter: grant_type",
    "error": "unsupported_grant_type",
    "error_uri": "https://datatracker.ietf.org/doc/html/rfc6749#section-5.2"
}
```

**Comment by jgrandja** [comment]
@inseo24 

> Currently, there is an inconsistency in the behavior of the token request handling for public and confidential clients when the grant_type parameter is incorrect.

We cannot assume that public and confidential client flows behave the same. We need to implement as per specification.

> For a public client (currently):
 2.1 Send a token request with an incorrect grant_type, e.g., "foo".

This is not a valid token request for a public client using PKCE. The `grant_type` parameter must be `authorization_code`, as per the [PKCE spec](https://datatracker.ietf.org/doc/html/rfc7636#section-4.5).

If it's not a valid PKCE token request, the `PublicClientAuthenticationProvider` will never be called and the request will proceed to the `AuthorizationFilter` **unauthenticated** resulting in access denied.

The current behaviour is implemented to spec. I'm going to close this and the associated PR.

**Comment by inseo24** [comment]
In the PKCE document you provided, there is no validation for grant_type in the [4. Protocol section](https://datatracker.ietf.org/doc/html/rfc7636#section-4). 

So, I think it is an incorrect Error Response that Access Denied is returned when only the parameter value of grant_type is incorrect, when the request for all other parameters is correct. 
In the same case, Confidential Client returns an unsupported_grant_type Error Response. 

Also, the documentation specifies unsupported_grant_type as an [Error Response for token requests](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2). 
So I think it's wrong for the AuthorizationFilter to return access denied because of the validation on grant_type for token requests (because the Error Response for token requests does not contain access denied, and that error is for [authorization code requests](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1).
