### ISSUE TITLE
No 'scope' is saved in OAuth2Authorization

### ISSUE THREAD

**Issue by szsun** [spring-projects/spring-authorization-server#1424]
**Describe the bug**
No 'scope' is saved in OAuth2Authorization if the /token request doesn't include the parameter.

https://stackoverflow.com/questions/76423232/no-getting-scopes-from-registeredclient-in-oauth2clientcredentialsauthentication/77363846#77363846

The code causes the issue:

https://github.com/spring-projects/spring-authorization-server/blob/7c197164e95395ff71ec03c191ee0ab655affdf2/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2ClientCredentialsAuthenticationProvider.java#L100

**To Reproduce**
Run the demo 
https://github.com/spring-projects/spring-authorization-server/tree/2a3b5d21f59d0353a1d5de806eb9b01ecd260034/samples/demo-authorizationserver

request:
curl --location --request POST 'http://localhost:9000/oauth2/token' \
--header 'Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: JSESSIONID=2E10D2E3608E02E65D98827B4888BEA9' \
--data-urlencode 'grant_type=client_credentials'

response:
{
    "access_token": "eyJraWQiOiI5NWZiOGU5NS01MDMzLTQ0MDYtYmZhZC1lZTVjYzcwMWNhNTEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTY5ODI4ODg5MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjk4Mjg5MTkxLCJpYXQiOjE2OTgyODg4OTF9.LAhiyH2rlgsU2U1qu_a0LyfZxSiMueHcrDWcgFy6LGBoWLxjQAxGIN4ouuTJa3Cakc7mkYEpbbi99-ASHejxegRcDFl2-pt_z7AdwJ8bg0STq6AISz8Ip9_nNyWlGObFvQw4UYjhBpuYyt1ho-BzuvzzlCl8Wl-xU7P1Wq8rAW4EH2oj-EfYblM33Ak_F30xoGauS1W4xk-CGt-RaeQJQf0iByMqhswpliS6gQ0rAK3utYo6jeE4j76h3IORMWKgVQ--06VLdIVHhwAcTCcOG14y6rfqslNWFC7uW7rvwEWfLDiS0A5ZGzasSsaGR7ntmxvOBZ2VO3ise3H8Jh2p6w",
    "token_type": "Bearer",
    "expires_in": 299
}

**Expected behavior**
"scope" should be populated/pesisted for the authorization and response.

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by szsun** [comment]
The fix is simply to add the else block as:
`if (!CollectionUtils.isEmpty(clientCredentialsAuthentication.getScopes())) {
			for (String requestedScope : clientCredentialsAuthentication.getScopes()) {
				if (!registeredClient.getScopes().contains(requestedScope)) {
					throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_SCOPE);
				}
			}
			authorizedScopes = new LinkedHashSet<>(clientCredentialsAuthentication.getScopes());
		} else {
			authorizedScopes = registeredClient.getScopes();
		}`

**Comment by jgrandja** [comment]
@szsun

We cannot default ALL the registered scopes `registeredClient.getScopes()` for the client if the access token request does not include the `scope` parameter. Although the `scope` parameter is OPTIONAL, if the client requires scope(s) to be associated to the acces token, then **it MUST request the scope explicitly is the token request**.

I'm going to close this as `OAuth2ClientCredentialsAuthenticationProvider` works as designed.

Related gh-884

**Comment by szsun** [comment]
But according to the  OAUTH2 specification 
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-07#name-access-token-scope
https://datatracker.ietf.org/doc/html/rfc6749#section-3.3

"If the client omits the scope parameter when requesting authorization, the authorization server MUST either process the request using a pre-defined default value or fail the request indicating an invalid scope. The authorization server SHOULD document its scope requirements and default value (if defined)."

The implementation here doesn't do either of the mentioned MUST approach.
It's not clear by the specification that what 'a pre-defined default value' really referred to here, could be the scopes defined on the client level, or a system level? but anyhow, neither behavior is implemented in the mentioned code.
