### ISSUE TITLE
Personally, I feel that annotations about permissions and roles should be provided.

### ISSUE THREAD

**Issue by imaxun** [spring-projects/spring-authorization-server#1442]
Personally, I feel that annotations about permissions and roles should be provided.

for example：

![image](https://github.com/spring-projects/spring-authorization-server/assets/29112991/c5137e94-830e-47ac-90b0-add391a9102c)

**Comment by geirhede** [comment]
I am not affiliated with the project, but isn't this what the @PreAuthorize spring security annotation would do, see e.g. https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html#oauth2resourceserver-jwt-authorization

Your image of something in an asian language did not help me understand your problem.

**Comment by jgrandja** [comment]
@imaxun The description provided needs more detail. Are you specifically asking for these new features? If so, please log separate issues for each. Also, this type of authorization feature belongs in Spring Security. See existing annotations in [Method Security](https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html).

I'm going to close this but if you decide to log a new issue in Spring Security, please be very specific on the feature request and provide details.
