### ISSUE TITLE
Query string in authorize request of `/?` format is not treated as OAuth request

### ISSUE THREAD

**Issue by townsece** [spring-projects/spring-authorization-server#1447]
**Describe the bug**
If a client calls the spring authorization server /oauth2/authorize endpoint with a query string following a trailing slash, they do not access the OAuth resource. Easy to work around, but passing it on to handle as you see fit.

**To Reproduce**
Call an implementation of the spring authorization server with eg.
`curl --verbose --url "{{HOST}}/oauth2/authorize/?response_type=code&client_id={{valid-client}}&scope=scope-a&state=anyState&redirect_uri={{valid-redirect-uri}}"`

Server will respond with login prompt/401 unauthorized

**Expected behavior**
302 response code and redirect following behaviour without trailing slash

**Sample**
N/A

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment]
@townsece `/oauth2/authorize/?response_type...` is not a valid authorization request. The authorization endpoint URI should be followed by the query string (without trailing slash). See example in [4.1.1. ](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#section-4.1.1)[Authorization Request](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#name-authorization-request)
