### ISSUE TITLE
Revoking a refresh token generated by a public client is not working

### ISSUE THREAD

**Issue by armandAkop** [spring-projects/spring-authorization-server#1461]
**Describe the bug**
With the latest 1.2.0 release, [this PR](https://github.com/spring-projects/spring-authorization-server/pull/1432/files) added the ability to generate a refresh token with a public client. After confirming I am able to generate a refresh token, I attempted to revoke the refresh token but received an invalid_client error. After stepping through the code with the debugger, I found that that authentication's principal is not of the expected class OAuth2ClientAuthenticationToken.

The request is made to POST /oauth2/revoke with
token: <refresh_token>
token_type_hint: refresh_token
client_id: <client_id>

The code that executes:
1. [OAuth2TokenRevocationEndpointFilter](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/OAuth2TokenRevocationEndpointFilter.java#L103)
2. [OAuth2TokenRevocationAuthenticationConverter](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/authentication/OAuth2TokenRevocationAuthenticationConverter.java#L47) Runs and the SecurityContextHolder returns back the custom Authentication class we have defined in our application which was set in the session on login.
3. [OAuth2TokenRevocationAuthenticationProvider](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2TokenRevocationAuthenticationProvider.java#L64C5-L64C49) is executed
4. [OAuth2AuthenticationProviderUtils.getAuthenticatedClientElseThrowInvalidClient](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthenticationProviderUtils.java#L40) is executed and since the Authentication principal is not of type OAuth2ClientAuthenticationToken, the method throws the invalid client error.

However, when I use a separate non-public client to generate a refresh token and revoke it with \
POST /oauth2/revoke with
token: <refresh_token>
token_type_hint: refresh_token
client_id: <client_id>
client_secret: <client_secret>

 everything works as expected since the authentication principal gets set to OAuth2ClientAuthenticationToken. \

**Expected behavior**
Is there a way to successfully revoke a public clients refresh token? Or am I just doing something wrong here?

**Comment by jgrandja** [comment]
@armandAkop The `/oauth2/revoke` endpoint requires client authentication as per spec and this is why the current authentication MUST be `OAuth2ClientAuthenticationToken` as it represents a client authentication. It appears you have either a misconfiguration and/or the call to the `/oauth2/revoke` endpoint is not being done by the client.
