### ISSUE TITLE
spring version compatibility matrix

### ISSUE THREAD

**Issue by Yneth** [spring-projects/spring-authorization-server#1466]
**Expected Behavior**
Spring version compatibility matrix is accessible in the docs

**Current Behavior**
There is no version compatibility matrix in the docs

**Context**
For migrating users, it would be nice to see spring-authorization-server compatibility matrix.

I can contribute one

**Comment by Yneth** [comment]
| Spring Authorization Server Version | Spring Version | Spring Boot Version | Spring Security Version |
|-------------------------------------|----------------|---------------------|-------------------------|
| 0.4.3                               | 5.3.28         | -                   | 5.8.4                   |
| 0.4.4                               | 5.3.30         | 2.7.16              | 5.8.8                   |
| 1.0.3                               | 6.0.10         | -                   | 6.0.4                   |
| 1.0.4                               | 6.0.13         | 3.0.11              | 6.0.8                   |
| 1.1.1                               | 6.0.10         | 3.1.0               | 6.1.1                   |
| 1.1.2                               | 6.0.11         | -                   | 6.1.2                   |
| 1.1.3                               | 6.0.13         | 3.1.4               | 6.1.5                   |
| 1.2.0-M1                            | 6.1.0-M5       | -                   | 6.2.0-M3                |
| 1.2.0-RC1                           | 6.1.0-RC1      | -                   | 6.2.0-RC2               |
| 1.2.0                               | 6.1.0          | -                   | 6.2.0                   |

**Comment by jgrandja** [comment]
@Yneth I'm not convinced we need to enhance the docs with this compatibility matrix.

Spring Security is the main project that Spring Authorization Server depends on. All Spring projects directly/indirectly depend on Spring Framework. However, Spring Authorization Server does not depend on Spring Boot.

Again, Spring Security is the main project that Spring Authorization Server depends on and it's quite easy to see what version of Spring Security is used for a specific Spring Authorization Server version via the [gradle.properties](https://github.com/spring-projects/spring-authorization-server/blob/main/gradle.properties#L6).

I'm going to close this based on the reasons explained above.
