### ISSUE TITLE
International Government Assurance Profile (iGov) for OpenID Connect 1.0

### ISSUE THREAD

**Issue by mcenci** [spring-projects/spring-authorization-server#1469]
**Expected Behavior**
Implementation of the above **DRAFT** specification

**Context**
Ability to use Spring Authorization Server in scenarions similar to **Italian SpID Openid connect** which relies on _iGov_ customizations. 

See: [iGov](https://openid.net/specs/openid-igov-openid-connect-1_0-03.html) built on top of [oauth2- iGov](https://openid.net/specs/openid-igov-oauth2-1_0.html)

**Comment by jgrandja** [comment]
Thanks for your interest in this project @mcenci.

The iGov Profile is still very early in the DRAFT phase so we would not consider implementing this until it reaches FINAL publication. Even at that point, I'm not sure this is something we would implement unless it is in high demand within our community.

I'm going to close this but feel free to open a new issue later on when (if) this becomes an official standard.
