### ISSUE TITLE
Scopes are not populated in OAuth2TokenIntrospectionAuthenticationProvider

### ISSUE THREAD

**Issue by amirh715** [spring-projects/spring-authorization-server#1487]
I need to include the authorized scopes of the token in the introspection result so that the resource server has the data it needs to perform authorization. But currently that's not happening and I believe the issue is in the code below:
https://github.com/spring-projects/spring-authorization-server/blob/4e56073b06b5b2a1bf571ef57f7153717ca926c1/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2TokenIntrospectionAuthenticationProvider.java#L129
https://github.com/spring-projects/spring-authorization-server/blob/4e56073b06b5b2a1bf571ef57f7153717ca926c1/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/OAuth2Authorization.java#L330

Current Behavior: They are not included in the introspection result (the client also has access to the scopes).
Expected Behavior: Authorized scopes be included in the introspection result.

Below is the data I have used:
```
        RegisteredClient.withId("1")
                .clientId("user-service")
                .clientSecret("{noop}12345")
                .redirectUri("http://localhost:8081")
                .scope("auth1")
                .scope("auth2")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
                .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
                .build()

        var id = "1";
        var scopes = Set.of("auth1", "auth2");
        var token = new OAuth2AccessToken(
                OAuth2AccessToken.TokenType.BEARER,
                id,
                Instant.now(),
                Instant.now().plusSeconds(1000000),
                scopes);
        var auth = OAuth2Authorization.withRegisteredClient(registeredClientRepository().findById("1"))
                .id(id)
                .token(token)
                .principalName("Amir")
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
                .authorizedScopes(scopes)
                .build();
```

Thank you.

**Comment by jgrandja** [comment]
@amirh715 When the client requests one or more scopes and is authorized for those scope(s), then it will be associated to the `OAuth2Authorization` alongside the `OAuth2AccessToken` in the "claims" attribute `OAuth2Authorization.Token.CLAIMS_METADATA_NAME`.

For example, for the `client_credentials` grant, it will be associated here:

https://github.com/spring-projects/spring-authorization-server/blob/ccad52dede17824ff9a13e4d2860602c85610316/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2ClientCredentialsAuthenticationProvider.java#L147

I'm going to close this as this has been working for quite some time now.
