### ISSUE TITLE
Add default OAuth2 device verification page

### ISSUE THREAD

**Issue by benacq** [spring-projects/spring-authorization-server#1488]
**Expected Behavior**
I am not sure if the omission was intentional, but, like other Spring security flows that comes with default pages for form login, saml, oauth2 and oauth2 consent, i was expecting a default basic form page for device `verification_uri` but it returned a 404 unless you define a controller mapping for that uri.

**Current Behavior**
The verification uri returned from the device authorization endpoint has no default mapping, hence it throws 404 when you launch the URL in the browser.

**Context**
I was expecting some consistency with existing spring security flows, so for a long time i thought i wasn't doing something right when no page was being returned until i figured out what the issue was, then i finally followed the authorization server example in the spring projects to configure custom pages for the verification.

Whilst this may not be critical, if it is something the team would consider implementing, i am willing to take it up and make the contribution.
I realise the `OAuth2DeviceAuthorizationEndpointFilter` class defines the `verificationUri`(for GET request i believe) and `OAuth2DeviceVerificationEndpointFilter` defines a `DEFAULT_DEVICE_VERIFICATION_ENDPOINT_URI` which shares the same value as the `verificationUri` in `OAuth2DeviceAuthorizationEndpointFilter` except this is where the `user_code` is submitted to(POST).
I think we could dynamically map the default `verificationUri` in `OAuth2DeviceAuthorizationEndpointFilter` to a default controller when no custom verificationUri is provided, what are your thoughts?

**Comment by jgrandja** [comment]
@benacq 

> i was expecting a default basic form page for device `verification_uri` but it returned a 404 unless you define a controller mapping for that uri.

Just to confirm, I'm assuming you were expecting a default generated form page similar to the page in the `demo-authorizationserver` sample?

https://github.com/spring-projects/spring-authorization-server/blob/main/samples/demo-authorizationserver/src/main/resources/templates/device-activate.html

**Comment by benacq** [comment]
> @benacq
> 
> > i was expecting a default basic form page for device `verification_uri` but it returned a 404 unless you define a controller mapping for that uri.
> 
> Just to confirm, I'm assuming you were expecting a default generated form page similar to the page in the `demo-authorizationserver` sample?
> 
> https://github.com/spring-projects/spring-authorization-server/blob/main/samples/demo-authorizationserver/src/main/resources/templates/device-activate.html

Yes,  that was what i was expecting, but no default page was mapped.

**Comment by benacq** [comment]
Yes that makes perfect sense, thanks for the clarification.

**Comment by benacq** [comment]
i will go ahead and close this thread.
