### ISSUE TITLE
Token endpoint filter error message should be handled using ControllerAdvice

### ISSUE THREAD

**Issue by learningvkpg** [spring-projects/spring-authorization-server#1515]
**Expected Behavior**
Writing @RestController advice for token endpoint should be able to customize the error response

**Current Behavior**
Current behaviors poses us to use error response handler and need to handle each exception

**Comment by jgrandja** [comment]
@learningvkpg Spring Authorization Server is based off of Spring Security (see [Architecture](https://docs.spring.io/spring-security/reference/servlet/architecture.html)), which uses `Filter` as the main processor. `Controller` is only reached if the `Filter` allows the request to proceed. If an error happens in the `Filter` (e.g. `OAuth2TokenEndpointFilter`) **it will never reach the** `Controller`. Therefore, customizing the error response must be performed by `OAuth2TokenEndpointFilter.authenticationFailureHandler`.

I'm going to close this based on the explanation provided.
