### ISSUE TITLE
java.util.ImmutableCollections$List12 is not in the allowlist

### ISSUE THREAD

**Issue by git9999999** [spring-projects/spring-authorization-server#1517]
**Describe the bug**
We use Spring Authorization Server with some fixed users in our Project in the Test Environment
. There it runs in a Docker container. 
I think, since the last version, is get a http 500 when i try to login, after the Server has run for more than 24h. 
I am sorry to not be able to provide a better description. But i will attach the log.

I solve the problem by restaring the Pod, then all works fine.

[ms-backend-test-authorization-server-mock.txt](https://github.com/spring-projects/spring-authorization-server/files/13976564/ms-backend-test-authorization-server-mock.txt)

**Comment by jgrandja** [comment]
Closing this as a duplicate. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/883#issuecomment-1245896451) for details.
