### ISSUE TITLE
"Token endpoint should not use query parameters" will block some usages

### ISSUE THREAD

**Issue by lidothui** [spring-projects/spring-authorization-server#1533]
As this ticket: https://github.com/spring-projects/spring-authorization-server/issues/1451, token endpoint should not use query parameters, since many existing external systems use our application's token endpoint which pass the query parameter as "/oauth/token?grant_type=client_credentials", it is not easy to notify all external systems to change their codes.
And the grant_type does not contain any sensitive information, is it possible that distinguish sensitive the parameters, accept non-sensitive parameters as query parameters, just reject the parameters which have sensitive information?

**Comment by jgrandja** [comment]
@lidothui 

> many existing external systems use our application's token endpoint which pass the query parameter as "/oauth/token?grant_type=client_credentials"

The external systems are not implemented to spec so it should be fixed there.

> is it possible that distinguish sensitive the parameters, accept non-sensitive parameters as query parameters, just reject the parameters which have sensitive information?

You can override the existing `OAuth2ClientCredentialsAuthenticationConverter` by supplying your own implementation of `AuthenticationConverter` (similar to `OAuth2ClientCredentialsAuthenticationConverter`) and configuring it as follows:

```java
OAuth2AuthorizationServerConfigurer authorizationServerConfigurer =
		new OAuth2AuthorizationServerConfigurer();
authorizationServerConfigurer
		.tokenEndpoint(tokenEndpoint ->
				tokenEndpoint
						.accessTokenRequestConverter(customClientCredentialsAuthenticationConverter)
						...

```

I'm going to close this as the consuming application would need to configure this off-spec customization.
