### ISSUE TITLE
Public OAuth2EndpointUtils

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-authorization-server#1542]
At present, we extend the implicit mode + password mode based on the authorization service, and need to obtain parameters from the request, considering the uniformity, the authorization server should be used, but this class is not disclosed, it is recommended to make it public.

**Comment by sjaeger-lxo** [comment]
As we also do a lot of customization I would also appreciate that this Utils is publicly available.
As a result, we needed to copy the whole OAuth2EndpointUtils class to be then usable in different AuthenticationConverters we extended or even replaced in its entirety. This generates quite a lot of copied code for us.

**Comment by jgrandja** [comment]
@leshalv @sjaeger-lxo 

`OAuth2EndpointUtils` is meant for internal use only and there are no plans to expose it.

IMO, duplicating `getFormParameters()` and `getQueryParameters()` in your application is quite minimal and I don't expect it to change much (if at all) going forward.

I'm going to close this and the associated PR.
