### ISSUE TITLE
Session created by the OAuth flow should be short lived

### ISSUE THREAD

**Issue by thingersoft** [spring-projects/spring-authorization-server#1584]
**Describe the bug**
Session (Security Context) created following request to the authorization endpoint survives after the related access token has been released. 

**To Reproduce**
1) Create two simple webapps: an authorization server based on SAS and a basic OAuth client app.
2) Login into the client webapp through the authorization server.
3) Logout from the client app (destroy client app session).
4) Try to login again into the client app

You will find yourself automatically logged in with the same account without being asked for consent and/or having the chance to switch to a different account.
This is due to the session-stored security context created during the authorization grant issuing phase.

**Expected behavior**
I would expect the security context to be destroyed after access token has been issued.
I think this should be the default (and possibly configurable) behaviour.

I would be happy to contribute but I would like to hear comments before coming up with a PR.

**Comment by jgrandja** [comment]
@thingersoft I'm not fully understanding the issue you reported here.

As far as the Session TTL and the Access Token TTL, there is no relation between the two. The Access Token could live longer or shorter than the Session. I'm not sure why you think these 2 should be linked? Did you read this somewhere in the related specs?

> You will find yourself automatically logged in with the same account without being asked for consent and/or having the chance to switch to a different account.

Try the [Demo Sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#demo-sample) and you will see the Logout works as expected - you will need to log in again but consent might not be required if you previously granted consent.

> I would expect the security context to be destroyed after access token has been issued.

I don't understand this? Please provide your reasoning for this. Did you read this in one of the related specs?

**Comment by thingersoft** [comment]
I'm referring to the session created by Spring AS to handle resource owner authentication following a request to the OAuth2 authorization endpoint.

This is an implementation detail since the way in which the authorization server authenticates the resource owner is beyond the scope of the OAuth spec:
[https://datatracker.ietf.org/doc/html/rfc6749#section-3.1](url)

Let's say you've got a basic SAS setup with a single form login and a client webapp using authorization code grant type:

1. Following a request to the authorization endpoint SAS creates a new session and perform a redirect to the login page.
2. Resource owner's credentials get posted to the login endpoint along with the newly created session cookie.
3. Resource owner is now authenticated by SAS so it's redirected to the uri provided by the OAuth client along with the authorization code.
4. The OAuth client calls the token endpoint with the provided authorization code and gets the authorization code.
5. The OAuth client webapp creates its own session bound to the resource owner certified identity.
6. The resource owner logs out from the client and login again because he wants to switch to a different account.
7. The user agent performs a request to the AS authorization endpoint, but the session cookie created at step 1 is still there.
8. The session tells SAS that the resource owner is already authenticated so it issue a redirect to the uri provided by the OAuth client with an authorization code bound to the same credentials provided at step 2.

The workaround is that when the user logs out from the client he also logs out from the SAS web application (by posting to the spring security /logout endpoint).


> Try the [Demo Sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#demo-sample) and you will see the Logout works as expected - you will need to log in again but consent might not be required if you previously granted consent.

I gave a quick look at the source code and it looks like the client is performing a OpenID Connect Logout wich is not part of a basic OAuth flow.

**Comment by thingersoft** [comment]
> Try the [Demo Sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#demo-sample) and you will see the Logout works as expected - you will need to log in again but consent might not be required if you previously granted consent.

@jgrandja 
I took a quick look at the demo code and it seems like the client is performing an OID Connect logout.

Upon further investigation I see that session management is really up to the single AP so I'm closing the issue.

What I was really looking for probably was the "login" value of the OID prompt parameter, it would be great if Spring AS could add support for it ( #501 upvoted).

Thanks for your time.

**Comment by jgrandja** [comment]
@thingersoft

> I see that session management is really up to the single AP

That's correct. The authentication sub-system is managed separately from the authorization server. There could be 1 Idp configured or multiple Idp's configured in a federation. Either way, the authentication system is not a concern of Spring Authorization Server. This is typically configured using Spring Security integrations. The only requirement for certain oauth2 flows, e.g. `authorization_code`, is that the request is authenticated.

gh-501 has quite a few upvotes so it will likely get scheduled for `1.4`.

**Comment by thingersoft** [comment]
@jgrandja 

> [gh-501](https://github.com/spring-projects/spring-authorization-server/issues/501) has quite a few upvotes so it will likely get scheduled for `1.4`.

Thank you, I would be available for a PR if you want/need.

**Comment by jgrandja** [comment]
@thingersoft I'll keep you posted when gh-501 is planned for a release.
