### ISSUE TITLE
Allow logout request to be sent without an id_token_hint

### ISSUE THREAD

**Issue by onghwand** [spring-projects/spring-authorization-server#1603]
**Expected Behavior**
When requesting a logout without an id_token_hint, logging out should be possible.

**Current Behavior**
The current version encounters an error with the OidcLogoutAuthenticationConverter when attempting a logout request without an id_token_hint.
```
// id_token_hint (REQUIRED)		// RECOMMENDED as per spec
String idTokenHint = parameters.getFirst("id_token_hint");
if (!StringUtils.hasText(idTokenHint) ||
		parameters.get("id_token_hint").size() != 1) {
	throwError(OAuth2ErrorCodes.INVALID_REQUEST, "id_token_hint");
}
```

**Context**
There is a test case for the RP Initiated Logout Profile regarding requests made without an id_token_hint.
<img width="1692" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/77609979/adc84397-1f23-4b2f-a0a7-88c65f73863c">

In the OpenID Connect RP-Initiated Logout 1.0 document (https://openid.net/specs/openid-connect-rpinitiated-1_0.html ), the id_token_hint parameter is RECOMMENDED, but not mandatory.
<img width="1590" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/77609979/f200d777-d57a-4a6c-93ad-c8bbe0a12548">

I want to successfully execute the test case using the Spring Authorization Server library. Is there any particular reason for implementing the code to throw an error when there is no id_token_hint? 

How about modifying the code as follows:
```
if (StringUtils.hasText(idTokenHint) &&
		parameters.get("id_token_hint").size() != 1) {
	throwError(OAuth2ErrorCodes.INVALID_REQUEST, "id_token_hint");
}
```
If you agree with my suggestion, I would like to contribute to the Spring Authorization Server library.

**Comment by jgrandja** [comment]
@onghwand 

> Is there any particular reason for implementing the code to throw an error when there is no `id_token_hint`?

As per spec, `id_token_hint` is `RECOMMENDED`, however, the implementation of `OidcLogoutAuthenticationProvider` requires the ID Token, as it relies on it to perform validation of `iss`, `aud`, `sid` and `exp` claims, as well as, `post_logout_redirect_uri` parameter.

Quite honestly, I'm not sure why `id_token_hint` is not `REQUIRED`. However, we decided to make it `REQUIRED` as per `RECOMMENDED`.

I'm going to close this based on the explanation provided.

**Comment by jgrandja** [comment]
@johanhaleby 

> If RP sends `/connect/logout` with an _expired_ `id_token_hint` but the browser still has a valid OP session cookie, then SAS returns 400 (invalid_token id_token_hint)

Expired ID tokens should be accepted. See gh-1440

https://github.com/spring-projects/spring-authorization-server/blob/ded91eadff8c62f8e275083dcc29f0236b53a0df/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/OidcLogoutAuthenticationProvider.java#L110

Can you put together a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) or test that reproduces the issue and I can look into it.

**Comment by jgrandja** [comment]
@ericmorand 

> if someone remove the ID Token from wherever it is stored into

Although this is a possibility I don't see this scenario as 

> a good reason for the token hint to be `RECOMMENDED` and not `REQUIRED`

If someone were to remove the ID Token from storage then it's either an admin error or a security breach, with the later being much more concerning then not logging out users

**Comment by jgrandja** [comment]
@johanhaleby I took a look at the tests in `Issue1603Test` and did not see a test that includes an expired ID Token. However, I did see this comment:

> I couldn't find a way to configure id-token timeout in application.yaml so there's not test for that

You can configure Spring Authorization Server to return a short-lived ID Token or an expired ID Token using an `OAuth2TokenCustomizer`. See the [reference doc](https://docs.spring.io/spring-authorization-server/reference/core-model-components.html#oauth2-token-customizer) for more details.

Here is an example configuration:

```java
@Bean
public OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer() {
	return context -> {
		JwtClaimsSet.Builder claims = context.getClaims();
		if (context.getTokenType().getValue().equals(OidcParameterNames.ID_TOKEN)) {
			claims.expiresAt(Instant.now().minusSeconds(1));
		}
	};
}
```

Please update the test and I'll look into it further.
