### ISSUE TITLE
Consider to support Federated Credential Management in the future

### ISSUE THREAD

**Issue by Chr3is** [spring-projects/spring-authorization-server#1608]
Google is working on Federated Credential Management, which can be used to log into sites.

See: 

- https://developers.google.com/privacy-sandbox/3pcd/fedcm
- https://fedidcg.github.io/FedCM/

We may want to check if the Spring Authorization Server can and should support this protocol.

**Comment by jgrandja** [comment]
@Chr3is Since Federated Credential Management API is authentication-related, this type of feature would belong in Spring Security. However, since this is still in Draft form, I would not recommend creating a ticket in Spring Security until it becomes a W3C Standard.
