### ISSUE TITLE
Introspection JWT customization

### ISSUE THREAD

**Issue by msmock** [spring-projects/spring-authorization-server#1626]
**Expected Behavior**
An extension point to customize the JWT received from the introspection endpoint in OAuth2TokenFormat.REFERENCE mode. I would expect something similar to the OAuth2TokenCustomizer functional interface to add claims to the JWT received from the introspection request. 

**Current Behavior**
Currently only patching of the OAuth2TokenIntrospection class seems to be the only option to modify the JWT from the introspection endpoint.

**Comment by jgrandja** [comment]
@msmock 

> An extension point to customize the JWT received from the introspection endpoint in OAuth2TokenFormat.REFERENCE mode

Please review the [OAuth 2.0 Token Introspection spec](https://datatracker.ietf.org/doc/html/rfc7662) as it is not designed how you are expecting. **The access token can only be customized before it is minted.**

Please review the reference doc for [OAuth2TokenCustomizer](https://docs.spring.io/spring-authorization-server/reference/core-model-components.html#oauth2-token-customizer) on how to customize an opaque or JWT access token.
