### ISSUE TITLE
AOT hints prevent compilation when using `JdbcOAuth2AuthorizationService` or `JdbcRegisteredClientRepository`

### ISSUE THREAD

**Issue by nwholloway** [spring-projects/spring-authorization-server#1629]
If you have a bean of type `org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService` or `org.springframework.security.oauth2.server.authorization.client.JdbcRegisteredClientRepository` then the compilation fails in `processAot` with the error:

```
java.lang.ClassNotFoundException:
  org.springframework.security.oauth2.server.authorization.jackson2.OAuth2ActorAuthenticationTokenMixin
```

To reproduce use `Spring Initializr` with dependencies "OAuth2 Authorization Server", "Spring Data JDBC" and "GraalVM Native Support", and just add the bean

```
@Bean
public JdbcRegisteredClientRepository registeredClientRepository(JdbcOperations jdbcOperations) {
    return new JdbcRegisteredClientRepository(jdbcOperations);
}
```

I have created an example [repository](https://github.com/nwholloway/spring-authorization-bug).

My investigation leads me to believe this this is caused by the AOT hint [OAuth2AuthorizationServerBeanRegistrationAotProcessor](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/aot/hint/OAuth2AuthorizationServerBeanRegistrationAotProcessor.java#L153)

The hint was introduced by 25a785de498b, but was not updated when the class was renamed by 2f1f45bc0152 (#60).

**Comment by jgrandja** [comment]
Closing as duplicate of gh-1630
