### ISSUE TITLE
Provide support for customizing OAuth2AuthorizationCode

### ISSUE THREAD

**Issue by reoshine** [spring-projects/spring-authorization-server#1656]
**Expected Behavior**

I hope to customize OAuth2AuthorizationCode

**Current Behavior**

When I customized OAuth2AuthorizationCode, I found it impossible to implement because OAuth2AuthorizationCodeRequestAuthenticationProvider has already instantiated OAuth2TokenGenerator<OAuth2AuthorizationCode>authorizationCodeGenerator=new OAuth2AuthorizationCodeGenerator();

**Context**

**Comment by jgrandja** [comment]
@reoshine It's already possible to provide your own implementation of `OAuth2TokenGenerator<OAuth2AuthorizationCode>`.

See `OAuth2AuthorizationCodeRequestAuthenticationProvider.setAuthorizationCodeGenerator(OAuth2TokenGenerator<OAuth2AuthorizationCode> authorizationCodeGenerator)`
