### ISSUE TITLE
AuthorizationServerContext should be accessible in custom consent controller

### ISSUE THREAD

**Issue by opcooc** [spring-projects/spring-authorization-server#1668]
When implementing multi tenant based on [stackoverflow](https://stackoverflow.com/questions/71528420/how-to-implement-multi-tenancy-in-new-spring-authorization-server/73230018#73230018), I need to implement TenantWebAuthenticationDetailsSource and TenantWebAuthenticationDetails during AuthorizationConsent to support tenant acquisition after 302. Can I provide custom parameter assembly in the sendAuthorizationConsent method to simplify this operation

**Comment by jgrandja** [comment]
@opcooc 

> I need to implement TenantWebAuthenticationDetailsSource and TenantWebAuthenticationDetails during AuthorizationConsent to support tenant acquisition

Can you please provide more details on why you need a custom `WebAuthenticationDetails`? How are you identifying tenants? Header, Sub-domain, etc..

Have you seen the [How-to: Implement Multitenancy](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-multitenancy.html) guide? It provides a complete sample without the need to customize the authorization consent process.

**Comment by opcooc** [comment]
> @opcooc
> 
> > 我需要在 AuthorizationConsent 期间实现 TenantWebAuthenticationDetailsS​​ource 和 TenantWebAuthenticationDetails 以支持租户获取
> 
> 您能否详细说明为什么需要自定义`WebAuthenticationDetails`？您如何识别租户？标头、子域等。
> 
> 您是否看过[《如何实施多租户》](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-multitenancy.html)指南？它提供了完整的示例，无需自定义授权同意流程。

Yes, I looked at [[How-to: Implement Multitenancy](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-multitenancy.html)] but can't get it after customizing the consentPage
This is my [sample](https://github.com/opcooc/demo-authorizationserver)，
access [authorize_uri](http://127.0.0.1:9443/server/oauth2/authorize?response_type=code&scope=profile openid&client_id=messaging-client&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc&state=8a0781548e7f76ae018e94e450982413) ，console output 'The issuer was not obtained',

**Comment by jgrandja** [comment]
@opcooc The `AuthorizationServerContext` should be accessible in `AuthorizationConsentController`. This appears to be a bug. I'll look into this and get back to you shortly.

**Comment by jgrandja** [comment]
@opcooc The fix is now merged.

**Comment by opcooc** [comment]
> @opcooc修复现已合并。

Thank

**Comment by opcooc** [comment]
Hi @jgrandja , I tested your modifications and found that 'AuthorizationServerContextHolder. getContext(). getIssuer()' seems to be incompatible with multi tenant scenarios.
For example:“ http://127.0.0.1:9443/issuerOne/oauth2/consent ", " http://127.0.0.1:9443/issuerTwo/oauth2/consent .
The problem seems to be with the resolveConsentUri method when requesting“ http://127.0.0.1:9443/issuerOne/oauth2/authorize When it comes to custom consent, it should be http://127.0.0.1:9443/issuerOne/oauth2/consent .
I don't know if my understanding is wrong.

**Comment by opcooc** [comment]
I have submitted a possible solution：[#1675 ](https://github.com/spring-projects/spring-authorization-server/pull/1675)

**Comment by jgrandja** [comment]
@opcooc I've re-opened the issue as the fix I merged was not the right solution. Please give me some time to think this one through.

**Comment by jgrandja** [comment]
@opcooc 

> When it comes to custom consent, it should be http://127.0.0.1:9443/issuerOne/oauth2/consent .

No. This is not correct. It is expected to be http://127.0.0.1:9443/oauth2/consent. The custom consent URI configured in `OAuth2AuthorizationEndpointFilter.consentPage` can be used for any issuer. There is no need for a different consent URI for each issuer.

Regarding gh-1675, the demo sample is broken with the suggested change. FYI, tests are required for any changes submitted. Either way, as mentioned in previous comment, another solution is required so I'll need more time to think it through. I'll close your PR.

**Comment by opcooc** [comment]
> @opcooc I've re-opened the issue as the fix I merged was not the right solution. Please give me some time to think this one through.

Ok thank you for your prompt response.

**Comment by opcooc** [comment]
> @opcooc
> 
> > When it comes to custom consent, it should be http://127.0.0.1:9443/issuerOne/oauth2/consent .
> 
> No. This is not correct. It is expected to be http://127.0.0.1:9443/oauth2/consent. The custom consent URI configured in `OAuth2AuthorizationEndpointFilter.consentPage` can be used for any issuer. There is no need for a different consent URI for each issuer.
> 
> Regarding [gh-1675](https://github.com/spring-projects/spring-authorization-server/pull/1675), the demo sample is broken with the suggested change. FYI, tests are required for any changes submitted. Either way, as mentioned in previous comment, another solution is required so I'll need more time to think it through. I'll close your PR.

Sorry, it was my misunderstanding. I will pay attention next time @jgrandja

**Comment by jgrandja** [comment]
@opcooc I'm starting to wonder if this is an issue after all.

The reason `AuthorizationServerContext` is not available after a redirect is performed to a custom `OAuth2AuthorizationEndpointFilter.consentPage` (e.g. `GET /oauth2/consent`) is because the request is not processed in the context of an authorization server request. More specifically, the `GET /oauth2/consent` is an application provided `@Controller` (with associated view) that is processed **outside of the** `authorizationServerSecurityFilterChain`.

Can you explain in detail why you need access to the `AuthorizationServerContext` during a `GET /oauth2/consent`? FYI, the `AuthorizationServerContext` is available during the processing of the authorization consent (`POST /oauth2/authorize`), which is where you would typically use it if needed.

**Comment by opcooc** [comment]
Hi @jgrandja ,
Reason: Because I need to display more comprehensive authorization confirmation information to prompt users, such as my customized application image information. So I need to perform a [query,](https://github.com/opcooc/demo-authorizationserver/blob/1f3294410113c05ea8bc164b70deacfa2bd4eed7/src/main/java/sample/web/AuthorizationConsentController.java#L72) and at this point, I need `AuthorizationServerContext`. In addition, the setting of `model. addAttribute' ('requestURI ','/oauth2/authorize ')` also requires `AuthorityServerContext`, because the `requestURI` is correct when `OAuth2AAuthorityEndpoint Filter. contentPage` is not set.

**Comment by jgrandja** [comment]
@opcooc 

> Because I need to display more comprehensive authorization confirmation information to prompt users

If you inject `OAuth2AuthorizationService` in `AuthorizationConsentController` (via constructor), then you can obtain the `OAuth2Authorization`, as follows:

```java
OAuth2Authorization authorization = this.authorizationService.findByToken(state, null);
OAuth2AuthorizationRequest authorizationRequest = authorization.getAttribute(OAuth2AuthorizationRequest.class.getName());
```

I believe this would give you all the information you would need (e.g. `authorizationRequest.getAuthorizationUri()`)?

**Comment by opcooc** [comment]
Hi @jgrandja 
You have overlooked an important issue that OAuth2Authorization Service cannot be correctly obtained in a multi tenant scenario.

[how-to-multitenancy](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-multitenancy.html)

![QQ图片20240724133912](https://github.com/user-attachments/assets/02c570d0-f167-49ea-9e51-2a79cde904ba)
![QQ图片20240724133906](https://github.com/user-attachments/assets/a5b6a30f-7687-4db2-bd07-71ab476808d3)

**Comment by jgrandja** [comment]
@opcooc 

> You have overlooked an important issue that OAuth2AuthorizationService  cannot be correctly obtained in a multi tenant scenario.

The `DelegatingOAuth2AuthorizationService` implementation in the "How-to: Implement Multitenancy" guide is a basic sample provided as a starting point. It's not meant to be production ready and should be adjusted and tested if used. Furthermore, there is always more than one way to implement things so users might not even use this sample implementation.

Regarding the issue you pointed out, this can easily be solved as follows:

Introduce the following method in `TenantPerIssuerComponentRegistry`:

```java
public <T> List<T> getAll(Class<T> componentClass) {
	List<T> components = new ArrayList<>();
	for (Map.Entry<String, Map<Class<?>, Object>> entry : this.registry.entrySet()) {
		components.add(componentClass.cast(entry.getValue().get(componentClass)));
	}
	return components;
}
```

Then update `DelegatingOAuth2AuthorizationService.findByToken()` to:

```java
@Override
public OAuth2Authorization findByToken(String token, OAuth2TokenType tokenType) {
	OAuth2AuthorizationService authorizationService =
			this.componentRegistry.get(OAuth2AuthorizationService.class);
	if (authorizationService != null) {
		return authorizationService.findByToken(token, tokenType);
	}
	for (OAuth2AuthorizationService authzService : this.componentRegistry.getAll(OAuth2AuthorizationService.class)) {
		OAuth2Authorization authorization = authzService.findByToken(token, tokenType);
		if (authorization != null) {
			return authorization;
		}
	}
	return null;
}
```

As mentioned in previous comment:

> The reason `AuthorizationServerContext` is not available after a redirect is performed to a custom `OAuth2AuthorizationEndpointFilter.consentPage` (e.g. `GET /oauth2/consent`) is because the request is not processed in the context of an authorization server request. More specifically, the `GET /oauth2/consent` is an application provided `@Controller` (with associated view) that is processed **outside of the** `authorizationServerSecurityFilterChain`.

Based on that reasoning, I'm going to close this ticket as it's expected that the `AuthorizationServerContext` will not be available **outside the context of an authorization server request**, which is the case for a custom consent `GET` request.
