### ISSUE TITLE
Consider adding an option to show consent screen when the only scope requested is openid 

### ISSUE THREAD

**Issue by balajimurugaiya** [spring-projects/spring-authorization-server#1681]
**Expected Behavior**
To display consent screen even when the only requested scope is `openid`. 

**Current Behavior**
When the only requested scope is `openid` there is no option of asking for consent and directly authorization code is returned. 

**Context**
In one of my projects where the relying party is an on prem software I want the end users to be asked consents even when the request contains openid as scope. As a workaround I have implemented my own AuthenticationProvider that supports `OAuth2AuthorizationCodeRequestAuthenticationToken.class` and returns `OAuth2AuthorizationConsentAuthenticationToken` to show the consent screen. But the issue here is I am completely bypassing the framework's implementation of `OAuth2AuthorizationCodeRequestAuthenticationProvider` as I am returning an Authentication object from my custom implementation. 

A fix I am suggesting is to add a flag like `mandateConsentForPureOpenidScope` in `OAuth2AuthorizationCodeRequestAuthenticationProvider` and `OAuth2AuthorizationConsentAuthenticationProvider` classes which can be set through customizers. Using these flags it can be determined if a consent is required or not.

**Comment by MrJovanovic13** [comment]
@balajimurugaiya
You can configure a `Predicate` via `OAuth2AuthorizationCodeRequestAuthenticationProvider.setAuthorizationConsentRequired()` which gives you full control on when to display the consent screen.

You have access to `OAuth2AuthorizationCodeRequestAuthenticationContext` which contains `getAuthorizationRequest()` and the `OAuth2AuthorizationRequest` contains the requested scopes so you can configure your own logic.

**Comment by balajimurugaiya** [comment]
@MrJovanovic13 This makes a lot of sense.My bad,I was still using 1.1.1 and was not aware of this release. Thanks for the comment! Closing this issue as its invalid.
