### ISSUE TITLE
Specify the FormLogin#loginUrl based on a tenant. 

### ISSUE THREAD

**Issue by rlagoue** [spring-projects/spring-authorization-server#1686]
**Expected Behavior**
Offer the possibility to specify custom login-urls depending on the tenant the user initiated the request with. It could be done in a similar way as the logout is configured now (have a look to the picture below)
![image](https://github.com/user-attachments/assets/2269b86f-e8b5-4480-b0d5-8d2425f79700)

The logic configurer could receive the ongoing instance of  "jakarta.servlet.http.HttpServletRequest" as input, therefor allowing us to extract the tenant and return the login-url based on this information

**Current Behavior**
The current state allows us to specify only one "login url" for all tenants

**Context**
I  configured multi tenancy according to the official documentation found [here](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-multitenancy.html) on my project.  After many days of digging I could not find a way to specify a tenant based custom login URL .

---
Thank you for the work delivered so far. 

Best Regards

**Comment by rlagoue** [comment]
Just understood that this issue should be addressed in the spring security project. Therefore it can be closed. I move it over there

**Comment by JL-Code** [comment]
> Just understood that this issue should be addressed in the spring security project. Therefore it can be closed. I move it over there刚明白这个问题应该在春季安全项目中解决。因此，它可以被关闭。我把它移到那边
I have also encountered the same problem. Can you share your ideas for solving the problem
