### ISSUE TITLE
Allow configuring OIDC ID token ttl

### ISSUE THREAD

**Issue by bytestreme** [spring-projects/spring-authorization-server#1689]
**Expected Behavior**

Configuring OIDC ID token ttl using token settings (id-token-signature-algorithm etc)

**Current Behavior**

Currently OIDC ID token ttl is 30 minutes

**Context**

Needed to configure ttl for client oidc id token

**Comment by jgrandja** [comment]
@bytestreme Have you see gh-790. Please read the comments and specifically [this one](https://github.com/spring-projects/spring-authorization-server/issues/790#issuecomment-1442319724) on why we haven't added this yet.

**Comment by bytestreme** [comment]
@jgrandja Now I see it, thanks!
