### ISSUE TITLE
OAuth2AuthorizationService::save return OAuth2Authorization to aid better integration with Spring @CachePut ?

### ISSUE THREAD

**Issue by colin-riddell** [spring-projects/spring-authorization-server#1726]
Hey esteemed SAS friends. I've a little suggestion I wanted to run past you:

**Expected Behavior**

Could `OAuth2AuthorizationService.save()` be changed to return `OAuth2Authorization` ?

**Current Behavior**

Currently, `OAuth2AuthorizationService.save()` returns `void`.
This is fine, but when trying to make use of spring cacheable, specifically with `@CachePut`, it's problematic. This can be worked around by injecting a cache manager and doing it manually

**Context**
Basically trying to do this to cache the authorization by it's token type using Springs `@CachePut`. It doesn't work, since `save()` is void.

```java
    @CachePut(
            cacheNames = {"authorizationById", "authorizationByToken"},
            key =
                    "T(org.springframework.util.StringUtils).hasText(#authorization.id) ? #authorization.id : #authorization.getToken(#tokenType).getToken().getTokenValue() + ':' + #tokenType.value")
    public void save(OAuth2Authorization authorization) {
```

**Comment by jgrandja** [comment]
Hi @colin-riddell 

> Could `OAuth2AuthorizationService.save()` be changed to return `OAuth2Authorization` ?

This would be a breaking change and doesn't follow our standard API design for `save()` operations as the following also return `void`: `OAuth2AuthorizationConsentService`, `RegisteredClientRepository`, `OAuth2AuthorizedClientService`, `UserDetailsManager`, `RequestCache`, etc.

After reviewing the [Cache Abstraction](https://docs.spring.io/spring-framework/reference/integration/cache/annotations.html) docs, it appears the `@CachePut` should be used on an `update()` operation, which `OAuth2AuthorizationService` does not provide.

I believe what you need to do is remove the `@CachePut` from `save()` and add `@Cacheable` to `findById()` and `findByToken()`. All the examples in the docs declare `@Cacheable` on "finder" methods so the authorization will get cached after the first lookup.

I'm going to close this as we cannot change the `OAuth2AuthorizationService.save()`.

**Comment by colin-riddell** [comment]
Thanks for the response. I understand completely.

We didn't use cache put annotation in the end, since the save is the update as you pointed out and it returns void, to the original point.

Thanks again.
