### ISSUE TITLE
Authentication with oauth2/token generates new token everytime for same clientId.

### ISSUE THREAD

**Issue by sreeraksha** [spring-projects/spring-authorization-server#1794]
Hi Team,

We noticed with oauth2/token endpoint for a clientId a new token is returned for every call. But instead it must return existing token.
In table OAUTH2_AUTHORIZATION we noticed multiple entries for same clientId and all tokens remain valid.

Library used :spring-security-oauth2-authorization-server:0.4.1
RegisteredClientRepository used is JdbcRegisteredClientRepository

Please help in addressing this issue.

**Comment by jgrandja** [comment]
Closing as duplicate of gh-1719
