### ISSUE TITLE
ClientSecretBasicAuthenticationConverter doesn't work properly

### ISSUE THREAD

**Issue by pstetsuk** [spring-projects/spring-authorization-server#1814]
In `ClientSecretBasicAuthenticationConverter` to extract `clientID` / `clientSecret` used the code below
```
			clientID = URLDecoder.decode(credentials[0], StandardCharsets.UTF_8.name());
			clientSecret = URLDecoder.decode(credentials[1], StandardCharsets.UTF_8.name());
```

I've checked [RFC7617](https://datatracker.ietf.org/doc/html/rfc7617) and didn't find that credentials should be URL encoded. Did I miss something?

Looks like need to remove `URLDecoder.decode()` from the code above.

Let me know if I'm correct and I'll prepare PR to fix it.

**Comment by jgrandja** [comment]
@pstetsuk As per section [2.4.1. Client Secret](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-07.html#name-client-secret):

> The client identifier **is encoded using the application/x-www-form-urlencoded** encoding algorithm per Appendix B, and the encoded value is used as the username; the client secret is encoded using the same algorithm and used as the password.

`ClientSecretBasicAuthenticationConverter` is implemented to spec as the `clientId` and `clientSecret` are expected to be URL encoded.

I'll close this and associated PR.
