### ISSUE TITLE
Will redis be supported in future versions?

### ISSUE THREAD

**Issue by Agoinyff** [spring-projects/spring-authorization-server#1857]
**Expected Behavior**
I saw 'How-to: Implement core services with Redis' in version 1.4.1-SNAPSHOT, but I have to add a lot of code when using it. Will this feature be integrated in the official version or subsequent versions instead of requiring programmers to write it manually?
![image](https://github.com/user-attachments/assets/0fbcfd64-8b48-41fc-8dcb-69dd659b4fbe)

**Current Behavior**
The current version does not support writing to redis. If you write it yourself, the biggest problem is serialization.

**Comment by jgrandja** [comment]
@Agoinyff Please see gh-444. Closing this as a duplicate.

> Data persistence is not an Application Security concern. The focus of this framework is strictly Application Security. For all persistence requirements, applications may freely choose the persistence framework and backing datastore that meets their requirements and provide the associated implementation. The framework simply requires a @Bean for the specific repository. It does not concern itself with the type of backing datastore.
