### ISSUE TITLE
Login Flow Issue When Adding Multiple Accounts

### ISSUE THREAD

**Issue by CoimbraVitor** [spring-projects/spring-authorization-server#1860]
**Expected Behavior**
When integrating my auth-server, I expect the option to log in with a different account to appear every time I try to add a new account. The flow should prompt the login screen consistently, regardless of previous login sessions.

**Current Behavior**
Currently, after adding one account, attempting to add another triggers the flow automatically without showing the login screen. Instead, it uses the session of the already logged-in account. The login page only appears if I close the browser or open an incognito window. This behavior suggests a potential cookie-related issue.

**Context**
I am working on integrating my auth-server with Zapier. While adding multiple accounts, the login flow does not behave as expected due to session persistence. Only by clearing cookies (via incognito mode or browser restart) does the flow correctly show the login page. This behavior impacts the ability to add multiple accounts seamlessly.

**Comment by jgrandja** [comment]
@CoimbraVitor Closing this as there are no plans to implement `prompt=select_account` as explained in this [comment](https://github.com/spring-projects/spring-authorization-server/issues/501#issuecomment-2275745818).
