### ISSUE TITLE
Add row_expires_at column to oauth2_authorization table

### ISSUE THREAD

**Issue by idotobi** [spring-projects/spring-authorization-server#1861]
**Expected Behavior**
There exists one column in the `oauth2_authorization` sql-table that contains the maximum of all `*_expires_at` columns. This would allow me to write an efficient query/index for entries that may be safely deleted as they can no longer impact any functionality of the authorization-server itself.

For example a `row_expires_at` could be written every time the entry is updated by the framework with 

```
row_expires_at = max(authorization_code_expires_at, access_token_expires_at, oidc_id_token_expires_at, refresh_token_expires_at, user_code_expires_at, device_code_expires_at)
```

This way users may use this aggregated information for creating queries/indices for cleanup tasks based on their business needs.

**Current Behavior**
Currently there are six `*_expires_at` columns

https://github.com/spring-projects/spring-authorization-server/blob/d2387942298406fe3c7565dc6f346a880826e3bf/oauth2-authorization-server/src/main/resources/org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql#L6-L41

 which all need to be checked to decide whether it may be safe to delete a row. 

**Context**
In our production system we're currently obtaining all entries we can delete via

```sql
SELECT id
        FROM oauth2_authorization
        WHERE (authorization_code_expires_at IS NULL OR authorization_code_expires_at < NOW())
          AND (access_token_expires_at IS NULL OR access_token_expires_at < NOW())
          AND (refresh_token_expires_at IS NULL OR refresh_token_expires_at < NOW())
          AND (oidc_id_token_expires_at IS NULL OR oidc_id_token_expires_at < NOW())
          AND (user_code_expires_at IS NULL OR user_code_expires_at < NOW())
          AND (device_code_expires_at IS NULL OR device_code_expires_at < NOW())
```

with the following index being present

```sql
CREATE INDEX EXPIRES_AT_CLEANUP_INDEX ON oauth2_authorization (
    refresh_token_expires_at -- the most selective column in our deployment scenario
);
```

Then we delete the entries batch-wise in a separate call to the Database.

We cannot simply run `DELETE FROM oauth2_authorization WHERE ...` (as spring-session does https://github.com/spring-projects/spring-session/blob/main/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcIndexedSessionRepository.java#L205-L208)  since the query alone regularly takes longer than 1s and thus impacts our token response times.

If we would have one single column we could potentially simplify the setup again by directly executing `DELETE FROM oauth2_authorization WHERE row_expires_at < NOW()` every minute similar to how spring-session handles it for jdbc (https://docs.spring.io/spring-session/reference/configuration/jdbc.html#customizing-cleanup-job).

We're currently considering to work around this by using database triggers to create a `row_expires_at` on `INSERT` and `UPDATE`. However, it might be more performant to add it to the authorization-server-framework directly and would also simplify the jdbc setup for other users with similar expiration criteria (see https://github.com/spring-projects/spring-authorization-server/issues/556, https://github.com/spring-projects/spring-authorization-server/issues/1266, and https://github.com/spring-projects/spring-authorization-server/issues/1534).

If you agree I could also try to implement a PR.

**Comment by jgrandja** [comment]
@idotobi I appreciate that `row_expires_at` would be useful for your use case, however, I'm not sure how much it would be used by other users. Furthermore, there are many customizations that are likely required in many different environments and we cannot support them all. For this reason, `JdbcOAuth2AuthorizationService` is fully customizable so you can simply customize it to meet your requirements, e.g. add `row_expires_at` column.

Take a look at `JdbcOAuth2AuthorizationServiceTests.tableDefinitionWhenCustomThenAbleToOverride()`, which provides a test on how to override the table definition altogether. There are tests in that class that demonstrate how to customize further.

**Comment by idotobi** [comment]
@jgrandja : Thank you for the quick answer and the pointer to `JdbcOAuth2AuthorizationServiceTests.tableDefinitionWhenCustomThenAbleToOverride()`. That definitely looks doable :pray: 
And thanks for your great work on the spring-authorization-server in general!!!
