### ISSUE TITLE
Request Parameters and Client Metadata for End-User Authentication

### ISSUE THREAD

**Issue by TakahikoKawasaki** [spring-projects/spring-authorization-server#211]
Request parameters and client metadata below are related to end-user authentication.

- `prompt` request parameter ([OIDC Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html) [Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest))
- `max_age` request parameter ([OIDC Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html) [Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest))
- `acr_values` request parameter ([OIDC Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html) [Section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest))
- `response_type=none` ([OAuth 2.0 Multiple Response Type Encoding Practices](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html) [Section 4](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#none))
- `default_acr_values` ([OIDC Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html) [Section 2](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata))
- `default_max_age` ([OIDC Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html) [Section 2](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata))

These have impacts on the implementation of end-user authentication. It is recommended to take these into consideration from the beginning.

**Comment by jgrandja** [comment]
Related #53 #57 #205

**Comment by dciarniello** [comment]
I'm wondering if there's been any movement on this request. If not, I'd like to add my vote for it to be done as clients are beginning to require support for this functionality.
