### ISSUE TITLE
OAuth2AuthorizationCodeAuthenticationProvider should check if the code has expired

### ISSUE THREAD

**Issue by AlekseyMishanin** [spring-projects/spring-authorization-server#290]
Hi guys! Glad to see you all.
When a client exchanges an authorization code for an access token, we forget to check the expiration date of the authorization code. Perhaps 
`if (authorizationCode.isInvalidated()) { throw new OAuth2AuthenticationException(new OAuth2Error(OAuth2ErrorCodes.INVALID_GRANT)); }` you can replace like this `if (authorizationCode.isInvalidated() || authorizationCode.isExpired()) { throw new OAuth2AuthenticationException(new OAuth2Error(OAuth2ErrorCodes.INVALID_GRANT)); }`.

**Comment by jgrandja** [comment]
Thank you for reporting this @AlekseyMishanin. This is a bug and should be `authorizationCode.isActive()`.
