### ISSUE TITLE
Jackson Exception When Creating Client

### ISSUE THREAD

**Issue by bibibiu2017** [spring-projects/spring-authorization-server#352]
**Describe the bug**
Jackson Mapping Exception when creating `RegisteredClient` with settings that contain collection created by `List.of()` or `Set.of()`

`Caused by: java.lang.IllegalArgumentException: The class with java.util.ImmutableCollections$List12 and name of java.util.ImmutableCollections$List12 is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details
	at org.springframework.security.jackson2.SecurityJackson2Modules$AllowlistTypeIdResolver.typeFromId(SecurityJackson2Modules.java:253) ~[spring-security-core-5.5.1.jar:5.5.1]
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:204) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:771) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:611) ~[jackson-databind-2.12.3.jar:2.12.3]
	... 41 common frames omitted`

**To Reproduce**
```
var client = RegisteredClient.withId(SecurityUtils.uuidGenerator())
                    .clientName("UsersClient")
                    .clientId("bibibiu_users_client")
                    .clientSecret(encoder.encode("bibibiu_auth_secret"))
                    .redirectUri("https://www.example.com")
                    .clientAuthenticationMethod(BASIC)
                    .clientAuthenticationMethod(POST)
                    .clientSettings(settings -> settings.requireUserConsent(true).requireProofKey(true))
                    .scopes(scopes -> scopes.addAll(Set.of(OidcScopes.OPENID, "bibibiu_auth:read", "bibibiu_auth:write")))
                    .clientSettings(settings -> settings.setting("resources", List.of("bibibiu-auth", "bibibiu-accounts")))
                    .authorizationGrantTypes(grantTypes -> grantTypes.addAll(Set.of(AUTHORIZATION_CODE, CLIENT_CREDENTIALS, REFRESH_TOKEN)))
                    .tokenSettings(settings -> settings.accessTokenTimeToLive(Duration.ofHours(1)))
                    .tokenSettings(settings -> settings.refreshTokenTimeToLive(Duration.ofHours(24)))
                    .build();
registeredClientRepository.save(client);
```

**Expected behavior**
Registered should be saved

**Comment by sjohnr** [comment]
@bibibiu2017, thanks for the report.

This project currently supports JDK 8, which would make compiling against code using `List.of`, `Set.of`, and the underlying types in `ImmutableCollections` quite difficult. We could possibly provide serializers/deserializers for `Set` and `List` in a generic way, however this is not done by Spring Security in `SecurityJackson2Modules`. It seems that it's just as easy for the application to provide `ArrayList` / `HashSet`, or even wrap them in `Collections.unmodifiableList` / `Collections.unmodifiableSet`. And of course you can add your own mixins.

Any reason your application would require these non-Java 8 collection types over easy alternatives?

**Comment by bibibiu2017** [comment]
There is no reason why my application requires non-java 8 collection types. I guess I will just create a Jackson Mixin.

**Comment by sjohnr** [comment]
Ok. If you can think of a way to specifically support `List.of`, `Set.of` in a Jackson module (e.g. not just generic `List`, `Set` support), while still compiling against Java 8 I'd be very interested. I'll leave this open for a bit and we can think about it, but I'm not currently sure it's worth doing until we drop support for Java 8, which would not be for some time I imagine.

**Comment by sjohnr** [comment]
@bibibiu2017, I'm going to close this issue based on what we discussed. If you have any ideas please feel free to add a comment. If it becomes a bigger issue, we can take a look and reopen if needed.
