### ISSUE TITLE
Return registration_endpoint in OidcProviderConfigurationEndpointFilter

### ISSUE THREAD

**Issue by bibibiu2017** [spring-projects/spring-authorization-server#370]
**Describe the bug**
OpenId configuration metadata endpoint does not return registration endpoint even though dynamic client registration it was implemented in gh-189 

**To Reproduce**
http://auth-server/.well-known/openid-configuration
returns

```
{
    "issuer": "http://localhost:8000/authorization",
    "authorization_endpoint": "http://localhost:8000/authorization/oauth2/authorize",
    "token_endpoint": "http://localhost:8000/authorization/oauth2/token",
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post"
    ],
    "jwks_uri": "http://localhost:8000/authorization/oauth2/jwks",
    "response_types_supported": [
        "code"
    ],
    "grant_types_supported": [
        "authorization_code",
        "client_credentials",
        "refresh_token"
    ],
    "subject_types_supported": [
        "public"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "scopes_supported": [
        "openid"
    ]
}
```

**Expected behavior**
Should contain the client registration endpoint

**Comment by sahariardev** [comment]
hi @jgrandja. Can I work on this issue?

**Comment by jgrandja** [comment]
Thanks for your interest @sahariardev.

We're holding off on adding new features and enhancements until after we release `0.3.0`.

Our top priority for `0.3.0` is to deliver the initial version of the reference documentation.
We still have a lot of work to do so we need to keep focused.

Please reach out again after `0.3.0` is released May 23.

**Comment by sahariardev** [comment]
Thanks for the reply. I will reach out after 0.3.0 release.

**Comment by sahariardev** [comment]
hi @jgrandja,
Can I work on this issue?

**Comment by jgrandja** [comment]
@sahariardev Yes, the issue is yours.

Please keep in mind that `OidcProviderConfigurationEndpointFilter` should return the `registration_endpoint` ONLY if the [OpenID Connect 1.0 Client Registration Endpoint](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oidc-client-registration-endpoint) is enabled - it's disabled by default.

**Comment by sahariardev** [comment]
ok thanks for the reply. I will keep in mind that

**Comment by sahariardev** [comment]
Hi @jgrandja,
I have created a Draft PR for this issue. Please review and let me know your feedbacks.
Here is the PR link
https://github.com/spring-projects/spring-authorization-server/pull/762
