### ISSUE TITLE
Cancel consent button does not submit form

### ISSUE THREAD

**Issue by ddubson** [spring-projects/spring-authorization-server#393]
**Describe the bug**

On the sample project: `spring-security-samples-boot-oauth2-integrated-authorizationserver-custom-consent-page`, upon landing on the custom consent page, the 'Cancel' button does not submit the consent form, but rather clears all form elements, as it is set to `type=reset`. This issue also extends to the default consent page as defined in `OAuth2AuthorizationEndpointFilter` class.

Looks like the specific change was introduced in commit `7b4fc46`

**To Reproduce**

1. Launch module: `spring-security-samples-boot-oauth2-integrated-authorizationserver-custom-consent-page` and adjacent sample client and resource server
2. Navigate to sample client (localhost:8080)
3. Log in with `user1` and `password`
4. Be redirected back to sample client home page
5. Click on `authorization code` grant type
6. Be redirected to Consent page
7. Click on 'Cancel' button

**Expected behavior**

The form is submitted and user is redirected back to client with no scopes approved.

**Comment by jgrandja** [comment]
Thanks for the report @ddubson.

The Cancel button should clear the checkboxes and then submit. It only resets at the moment as I haven’t gotten around to adding the javascript to perform that action. Would you be interested in submitting a PR for this?
