### ISSUE TITLE
Not support change client domain and got CORS error

### ISSUE THREAD

**Issue by hoanghuycptqt** [spring-projects/spring-authorization-server#399]
**Describe the bug**
Access to XMLHttpRequest at 'http://localhost:9090/oauth2/token' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request

**To Reproduce**
I try to setup client is a Angular app at:  http://localhost:8080  and call the POST method to get token: http://localhost:9090/oauth2/token

**Expected behavior**
I think should able to set the CORS allow in authorization server

**Comment by Ynnck123** [comment]
Have you tried to add the following to your SecurityFilterChain? 

`OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http.cors().and())`

**Comment by hoanghuycptqt** [comment]
I need to disable csrf and it worked
`http.csrf().disable().cors().and()`

**Comment by jgrandja** [comment]
@hoanghuycptqt I'm going to close this since this is a misconfiguration issue in the user application.
