### ISSUE TITLE
 Can I find the 0.2.0 release version in the maven center?

### ISSUE THREAD

**Issue by Benzenes** [spring-projects/spring-authorization-server#410]
Can I find the 0.2.0 release version in the maven center? 
![image](https://user-images.githubusercontent.com/22295395/129997496-3bfca339-15e0-4f05-b245-be33ae6abeb7.png)

**Comment by xialugui** [comment]
lasted version has been published 6 hours,  plz wait.
![image](https://user-images.githubusercontent.com/14935553/130025168-28d61012-2867-4a0d-a953-dc8a473051b1.png)
![image](https://user-images.githubusercontent.com/14935553/130025185-6e51356f-f7c8-4d0c-84ff-fd3a6dba8a52.png)

**Comment by jgrandja** [comment]
@Benzenes The index might not have been updated yet, hence why you are not seeing it in the search.

It has been published -> https://repo1.maven.org/maven2/org/springframework/security/spring-security-oauth2-authorization-server/

**Comment by Benzenes** [comment]
thx,I have seen it, and the dependency download is worked for me.
