### ISSUE TITLE
Encoded secret doesn't match BCryptPattern for "/oauth2/token"

### ISSUE THREAD

**Issue by Ynnck123** [spring-projects/spring-authorization-server#412]
**Describe the bug**
Since version 0.2.0 introduced automatic encoding of the client secret, I experience a bug that that the encoded secret doesn't match the Bcrypt Pattern when I set BCryptPasswordEncoder with 10 rounds as passwort encoder bean.

**To Reproduce**
Set password encoder bean
``` 
@Bean
fun passwordEncoder(): BCryptPasswordEncoder = BCryptPasswordEncoder(10)
```

Set raw secret e.g.:

```
val registeredClient: RegisteredClient = RegisteredClient.withId(UUID.randomUUID().toString())
                .clientId("clientId")
                .clientSecret("secret")
```

Set breakpoint in the BCryptPasswordEncoder `matches()` method.

Run through the authorization flow.

`POST` _/oauth2/token_ will fail due to "_Encoded password does not look like BCrypt_"

**Behavior**
The encrypted password doesn't matches the BCrypt pattern, 

`this.BCRYPT_PATTERN.matcher(encodedPassword).matches()` returns `false`.

**Expected behavior**
The encrypted password matches the BCrypt pattern and the POST with valid credentials on _/oauth2/token_ succeeds.

**Comment by Ynnck123** [comment]
**Update**: 
I managed to solve the problem by manually assigning the password encoder to the `RegisteredClientParametersMapper` in the declaration of the `RegisteredClientRepository` bean.

Assuming the password encoder is provided like in my example from the original post via:

```
@Bean
fun passwordEncoder(): BCryptPasswordEncoder = BCryptPasswordEncoder(10)
```

```
    @Bean
    fun registeredClientRepository(jdbcTemplate: JdbcTemplate, passwordEncoder: BCryptPasswordEncoder): RegisteredClientRepository {
        val registeredClientRepository = JdbcRegisteredClientRepository(jdbcTemplate)
        val translationToolClientId = "translation-tool-client"

        val registeredClientParametersMapper = RegisteredClientParametersMapper()
        registeredClientParametersMapper.setPasswordEncoder(passwordEncoder)
        registeredClientRepository.setRegisteredClientParametersMapper(registeredClientParametersMapper)
        
        // Rest of the settings
        
        return registeredClientRepository
        }
```

Nevertheless, I was assuming the underlying passwordEncoder would automatically get fetched by the provided `PasswordEncoder` bean?

**Comment by jgrandja** [comment]
@Ynnck123 Since your application configures `JdbcRegisteredClientRepository`, it also needs to be configured with the `BCryptPasswordEncoder`, as you have done.

I'm glad you figured it out. I'll close this.
