### ISSUE TITLE
OAuth2 implicit flow

### ISSUE THREAD

**Issue by kubboadam** [spring-projects/spring-authorization-server#415]
**Describe the bug**
Hello.
Maybe it is a stupid question, but I would like to ask, if "OAuth2 implicit flow" is supported by "spring-authorization-server".
I tried to set ".authorizationGrantType(AuthorizationGrantType.IMPLICIT)" for my registered client, but the flow always end with HTTP 500 Error. I know that this grant type is marked as deprecated, but I expected that it will work.

**To Reproduce**
Classic OAuth2 implicit flow

**Expected behavior**
Access token is issued after correct login

**Comment by dfcoffin** [comment]
@kubboadam The Authorization Server project will not be providing support for the Implicit grant as it is deprecated and removed from OAuth 2.1.  However, customization capability has been added (see [gh-139](https://github.com/spring-projects/spring-authorization-server/issues/139)).

**Comment by kubboadam** [comment]
Thank you for the answer

**Comment by buckett** [comment]
Although it's deprecated it is used by some standards that build on OAuth. An example is LTI 1.3 which uses the implicit grant as part of it's login flow. 

https://www.imsglobal.org/spec/security/v1p0/#openid_connect_launch_flow
