### ISSUE TITLE
New Feature: password grant type

### ISSUE THREAD

**Issue by 403Unauthorized** [spring-projects/spring-authorization-server#416]
** Feature Request **
I noticed that there are only `authorization_code`, `client_credentials` and `refresh_token` for grant type. Will you plan to add `password` to grant type?

**Comment by xialugui** [comment]
The Resource Owner Password Credentials grant is omitted from this specification,
see https://oauth.net/2.1/

**Comment by srempfer** [comment]
If you need it for your custom authorization server, perhaps the issue #343 helps you to implement it

**Comment by 403Unauthorized** [comment]
Thanks!

**Comment by sjohnr** [comment]
Thanks for the request, @403Unauthorized. I'll go ahead and close this issue as a duplicate. See #343 for context.
