### ISSUE TITLE
unsupport password grant_type?

### ISSUE THREAD

**Issue by xpp1109** [spring-projects/spring-authorization-server#419]
the response error is :
{
    "error_description": "OAuth 2.0 Parameter: grant_type",
    "error": "unsupported_grant_type",
    "error_uri": "https://datatracker.ietf.org/doc/html/rfc6749#section-5.2"
}

**Comment by xpp1109** [comment]
grant_type:  authorization_code、client_credentials is ok, others is not ok

**Comment by jgrandja** [comment]
Thanks for explaining @ovidiupopa91 !
