### ISSUE TITLE
Annotate RegisteredClient with @Entity for custom jpa, crud etc. repository use

### ISSUE THREAD

**Issue by ggrujic** [spring-projects/spring-authorization-server#422]
**Expected Behavior**
As a developer, I want to use some regular repository methods such as findAll and build some custom repository methods.

**Current Behavior**
There is no way to build JpaRepository, CrudRepository, etc. because it is failing on:
`java.lang.IllegalArgumentException: Not a managed type RegisteredClient` because there is no annotation as an Entity.

**Context**
I'm building my own UI which will handle registered clients so I need to use some methods such as findAll, findAllBySomeField delete, etc.

A second possible solution will be also to build RegisteredClientRepository to have all those default methods.

**Comment by bschoenmaeckers** [comment]
You should extend the RegisteredClientRepository and implement your own findAll methods as discussed in this issue: #325. Nevertheless I don't think that making RegisteredClient an Entity is a bad idea.

**Comment by yangyaofei** [comment]
Needed!  Working with spring-data-elasticsearch,  this drive me crazy ..........

**Comment by sjohnr** [comment]
Hi @ggrujic, thanks for the suggestion.

This framework is designed to be independent of technologies like Spring Data. However, you're welcome to use them in your own implementations.

> There is no way to build JpaRepository, CrudRepository, etc.

You can implement the interface and provide this functionality by mapping/delegating to a custom repository. Here is a gist which could get you started: [JpaOAuth2AuthorizationService](https://gist.github.com/sjohnr/463448fc00cf6059dd2892aed1e63d3c)

I'm going to close this, as it is not our intent to provide a JPA-compatible implementation directly. However, feedback welcome on the gist I provided above, as it may be helpful in doing exactly what you're trying to do.

**Comment by yangyaofei** [comment]
@sjohnr  hi, I don't think that create a new class is a good idea, it's like copy source code from this project. And if the code is changed, that code should be changed by hand. 

**There is a way to use `RegisteredClient` without any extra support**, is extend `RegisteredClient` and That subclass can add any annotation for JPA or other things, but `RegisteredClient` did not have a Constructor to new a instance from `RegisteredClient` instance

Because for implementing `RegisteredClientRepository` , the subclass need a constructor like `public MyRegisteredClient(RegisteredClient registeredClient)`.

**Comment by notbeenfound** [comment]
Hi! Why can't make org.springframework.security.oauth2.server.authorization.client.RegisteredClient interface (like org.springframework.security.core.userdetails.UserDetails)? What difficulties will arise?

**Comment by sjohnr** [comment]
@notbeenfound can you clarify the question? Are you asking if `RegisteredClient` can be made into an interface?

**Comment by notbeenfound** [comment]
@sjohnr, instead of the `RegisteredClient` class make an interface with getters, this will allow programmers to describe a stored class as they want.

**Comment by sjohnr** [comment]
Thanks for the clarification, @notbeenfound.
