### ISSUE TITLE
使用password 模式时，clientSecret值的验证逻辑是否有问题

### ISSUE THREAD

**Issue by luyanfeng** [spring-projects/spring-authorization-server#423]
**Describe the bug**
1. JdbcRegisteredClientRepository 保存clientSecret时行进了encode()(会有‘{bcrypt}’） 

2. 我在用密码模式 获取token时，发现没有过滤{bcrypt}就进行了比较，结果返回： Encoded password does not look like BCrypt。

![image](https://user-images.githubusercontent.com/5779510/131648661-25f64774-302e-42c6-8eda-71834f6486a5.png)
![image](https://user-images.githubusercontent.com/5779510/131648688-089199aa-d709-44e4-8143-fea6cc00cf21.png)
![image](https://user-images.githubusercontent.com/5779510/131648706-8f833a6c-72e0-4fde-b6cf-4f37d89a5cec.png)

version 0.2.0

这是否是个bug? 
我该如何正确配置clientSecret才能成功获取accessToken?

**Comment by sionguo** [comment]
如果你自己定义了passwordEncoder这个bean，就要把自定义的放到参数映射里面
```
    JdbcRegisteredClientRepository registeredClientRepository =
        new JdbcRegisteredClientRepository(jdbcTemplate);
    RegisteredClientParametersMapper registeredClientParametersMapper = new RegisteredClientParametersMapper();
    registeredClientParametersMapper.setPasswordEncoder(passwordEncoder);
    registeredClientRepository.setRegisteredClientParametersMapper(registeredClientParametersMapper);
```

**Comment by luyanfeng** [comment]
> 如果你自己定义了passwordEncoder这个bean，就要把自定义的放到参数映射里面
> 
> ```
>     JdbcRegisteredClientRepository registeredClientRepository =
>         new JdbcRegisteredClientRepository(jdbcTemplate);
>     RegisteredClientParametersMapper registeredClientParametersMapper = new RegisteredClientParametersMapper();
>     registeredClientParametersMapper.setPasswordEncoder(passwordEncoder);
>     registeredClientRepository.setRegisteredClientParametersMapper(registeredClientParametersMapper);
> ```
> 
> 或者定义passwordEncoder 的时候这样定义
> 
> ```
>   @Bean
>   PasswordEncoder passwordEncoder() {
>     return PasswordEncoderFactories.createDelegatingPasswordEncoder();
>   }
> ```

那我当前这么写是不是有问题的：
```java
class MyJdbcRegisteredClientRepository extends JdbcRegisteredClientRepository {

        public MyJdbcRegisteredClientRepository(JdbcOperations jdbcOperations) {
            super(jdbcOperations);
        }

        @Override
        public RegisteredClient findByClientId(String clientId) {
            RegisteredClient client = super.findByClientId(clientId);

            RegisteredClient passwdClient = RegisteredClient.from(client)
                    .clientSecret(client.getClientSecret().replaceFirst("\\{bcrypt\\}", ""))
                    .build();
            return passwdClient;
        }
    }
```

**Comment by luyanfeng** [comment]
> 如果你自己定义了passwordEncoder这个bean，就要把自定义的放到参数映射里面
> 
> ```
>     JdbcRegisteredClientRepository registeredClientRepository =
>         new JdbcRegisteredClientRepository(jdbcTemplate);
>     RegisteredClientParametersMapper registeredClientParametersMapper = new RegisteredClientParametersMapper();
>     registeredClientParametersMapper.setPasswordEncoder(passwordEncoder);
>     registeredClientRepository.setRegisteredClientParametersMapper(registeredClientParametersMapper);
> ```
> 
> 或者定义passwordEncoder 的时候这样定义
> 
> ```
>   @Bean
>   PasswordEncoder passwordEncoder() {
>     return PasswordEncoderFactories.createDelegatingPasswordEncoder();
>   }
> ```

多谢，确实是
