### ISSUE TITLE
Auth Flow Programmatically

### ISSUE THREAD

**Issue by asterisk360-admin** [spring-projects/spring-authorization-server#430]
Hi everyone

I'm looking to perform the authentication flow through an internal process (Programmatically)

It's possible to extend or create a custom authorize process?

Thanks

**Comment by asterisk360-admin** [comment]
Resolved with information at #343

https://github.com/Basit-Mahmood/spring-authorization-server-password-grant-type-support

It would be great if this is included in the standar package without having to do an extra implementation

**Comment by sjohnr** [comment]
@asterisk360-admin, thanks for the feedback and glad you found an answer. I would also encourage you to look into `client_credentials` grant, as it sounds possibly like an option for you.

It's not something we have a sample of currently, but if you want to authenticate normal users with a chosen client using `client_credentials`, you can implement a `RegisteredClientRepository` that delegates to a `UserDetailsService`. For example:

```java
public final class DaoRegisteredClientRepository implements RegisteredClientRepository {
	private final RegisteredClient registeredClient;
	private final UserDetailsService userDetailsService;

	public DaoRegisteredClientRepository(RegisteredClient registeredClient, UserDetailsService userDetailsService) {
		this.registeredClient = registeredClient;
		this.userDetailsService = userDetailsService;
	}

	@Override
	public void save(RegisteredClient registeredClient) {
		throw new UnsupportedOperationException();
	}

	@Override
	public RegisteredClient findById(String id) {
		return this.registeredClient.getId().equals(id) ? this.registeredClient : null;
	}

	@Override
	public RegisteredClient findByClientId(String clientId) {
		UserDetails userDetails;
		try {
			userDetails = this.userDetailsService.loadUserByUsername(clientId);
		} catch (UsernameNotFoundException ignored) {
			return null;
		}

		return RegisteredClient.from(this.registeredClient)
				.clientId(userDetails.getUsername())
				.clientSecret(userDetails.getPassword())
				.build();
	}
}
```

Tokens returned by the `POST /oauth2/token` endpoint then have a `sub` of a user instead of the `clientId`:

```json
{
  "sub": "user1",
  "aud": "user1",
  "nbf": 1630682022,
  "scope": [
    "scope1",
    "scope2"
  ],
  "iss": "http://auth-server:9000",
  "exp": 1630682322,
  "iat": 1630682022
}
```

**Comment by asterisk360-admin** [comment]
@sjohnr  Thanks really appreciate this new option.

At this time I'm trying to register this new DaoRegisteredClientRepository but can't find any example.

The current examples show the inMemory way:

@Bean
public RegisteredClientRepository registeredClientRepository() {
       return new InMemoryRegisteredClientRepository(clientx);
}


is any way to configure this custom clientRepository.

Thanks

**Comment by sjohnr** [comment]
Yep. You can use method injection and replace InMemory with a custom one:

```java
	@Bean
	public RegisteredClientRepository registeredClientRepository(UserDetailsService userDetailsService) {
		RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
				...
				.build();

		return new DaoRegisteredClientRepository(registeredClient, userDetailsService);
	}
```
