### ISSUE TITLE
authenticationDetailsSource of OAuth2TokenEndpointFilter should be customizable

### ISSUE THREAD

**Issue by octopusthu** [spring-projects/spring-authorization-server#431]
**Expected Behavior**

The `authenticationDetailsSource` field of `OAuth2TokenEndpointFilter` should be made customizable by removing the final modifier from the field and adding a setter method for it. This would allow richer information other than just the IP address and session ID to be included in an authentication request. 

```java
private AuthenticationDetailsSource<HttpServletRequest, ?> authenticationDetailsSource = 
    new WebAuthenticationDetailsSource();

public void setAuthenticationDetailsSource(AuthenticationDetailsSource<HttpServletRequest, ?> authenticationDetailsSource) {
    this.authenticationDetailsSource=authenticationDetailsSource;
}
```

**Current Behavior**

The `authenticationDetailsSource` field can not be customized because it is a private final field.

```java
private final AuthenticationDetailsSource<HttpServletRequest, ?> authenticationDetailsSource =
    new WebAuthenticationDetailsSource();
```

**Comment by octopusthu** [comment]
Further, if `OAuth2TokenEndpointFilter` could be made non-final, it should provide a protected method to build authentication details, instead of directly building it in the `doFilterInternal` method. This is what `UsernamePasswordAuthenticationFilter` does in Spring Security. 

```java
protected void setDetails(HttpServletRequest request, Authentication authRequest) {
    authRequest.setDetails(authenticationDetailsSource.buildDetails(request));
}
```

This would allow greater flexibility when using the class. For example, in certain scenarios if a developer would like to set the authentication details via other means, he can achieve this by overriding the method and setting it blank.

**Comment by sjohnr** [comment]
@octopusthu thanks for the suggestions. I think we can definitely discuss allowing the `authenticationDetailsSource` to be customizable.

As far as removing `final` from the class, I will say that the filter follows the same pattern as that used in Spring Security, though perhaps there are some older implementations that aren't as consistent with that, such as the one you mentioned. If we were to allow setting the `authenticationDetailsSource`, the class would be customizable without the need to open it up for extension, which is the preferred approach.

If we just focus on making it non-final, and allowing it to be customized via an `ObjectPostProcessor`, we can then see if it feels like we need support in the configurer itself, as a follow-up issue.

Are you interested in working on a change to the filter to make it non-final and add a setter?

**Comment by octopusthu** [comment]
Hi @sjohnr , thanks for the reply! Yes I'm interested in working on this. I'll open a PR, then. :)
