### ISSUE TITLE
Support JPA to manage `RegisteredClient`

### ISSUE THREAD

**Issue by mrth1995** [spring-projects/spring-authorization-server#440]
Hello, can i get confirmation if `RegisteredClientRepository` supports JPA?

Looks like current implementation of authorization server is using `JDBCTemplate` to do operation related to RegisteredClient.

I would like to implement this authorization with my project that using JPA to manage data. If i use this implementations looks like i'll have two database connection, from JPA and JDBC and i don't think its effective. please correct me if i'm wrong.

Thanks in advance for your supports!

**Comment by sjohnr** [comment]
Hi @mrth1995, thanks for your interest in the project.

Per [this comment](https://github.com/spring-projects/spring-authorization-server/issues/422#issuecomment-917029019):

> This framework is designed to be independent of technologies like Spring Data. However, you're welcome to use them in your own implementations.

> You can implement the interface and provide this functionality by mapping/delegating to a custom repository. Here is a gist with an example of how to do this for the `OAuth2AuthorizationService` interface: [JpaOAuth2AuthorizationService](https://gist.github.com/sjohnr/463448fc00cf6059dd2892aed1e63d3c)

Do you have interest in working up a similar example for `RegisteredClientRepository`? Some of these types of "recipes" for implementation may be helpful for our upcoming documentation effort.

**Comment by wsaca** [comment]
@sjohnr Before adding a new issue I would like to understand why redirectUri in RegisteredClient builder is mandatory only for AUTHORIZATION_CODE grant, was it a design decision? When I have multiple grants enabled I need to create a new RegisteredClient without redirectUris to avoid forcing the user to enter it.

**Comment by sjohnr** [comment]
@wsaca if you don't mind, please go ahead and create a new issue directly related to that topic, and we can discuss it.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sjohnr** [comment]
@mrth1995, check out [this gist](https://gist.github.com/sjohnr/0c6065d90d11a0f24bd3f15cbbaa8527) to see an example `JpaRegisteredClientRepository` implementation. I'm going to close this issue for now. Let me know if you have any feedback on the sample code.
