### ISSUE TITLE
Role Mappings

### ISSUE THREAD

**Issue by suhasbhairav** [spring-projects/spring-authorization-server#443]
Dear Spring Developers,

I'd like to know if there is any possibility of incorporating roles for users in the coming spring security versions? For e.g., admin, normal-user, etc.

**Comment by jgrandja** [comment]
@suhasbhairav Can you please provide more detail. I'm not following your description.

**Comment by suhasbhairav** [comment]
@jgrandja Thanks for getting back. For e.g., in Keycloak [(link)](https://www.keycloak.org/docs/latest/server_admin/) , we have the option of setting roles and role mappings that typically identify the category of the user in the Authorization server. An example would be Admin, user, manager, and employee. I was wondering if there is any plan to introduce something similar in Spring OAuth 2.1?

Thanks 
Suhas

**Comment by jgrandja** [comment]
@suhasbhairav Spring Authorization Sever leverages Spring Security for Authentication and this is where you would configure custom mapping of roles for authenticated users.

For example, the [sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples/boot/oauth2-integration) is configured with `formLogin()` as the authentication mechanism and the configured [UserDetailsService](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/boot/oauth2-integration/authorizationserver/src/main/java/sample/config/DefaultSecurityConfig.java#L50) provides the registry of users and associated roles.

Please review the Spring Security documentation on [UserDetailService](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-authentication-userdetailsservice) and [GrantedAuthority](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-authentication-granted-authority).

There are many different authentication mechanisms that can be configured, not just `formLogin()`, but ultimately Spring Security handles the Authentication process.
