### ISSUE TITLE
WebFlux Resource Server

### ISSUE THREAD

**Issue by sundarvc** [spring-projects/spring-authorization-server#449]
Hi Team,

Can you let me know how I can modify the resource server to make it work with spring-webflux ?
I have an existing webflux resource server on which I want to enable oauth.

Thanks,
Sundar

**Comment by sjohnr** [comment]
Hi @sundarvc, the [Spring Security project](https://github.com/spring-projects/spring-security/) has support for a webflux resource server. See [this sample](https://github.com/spring-projects/spring-security-samples/tree/main/reactive/webflux/java/oauth2/resource-server).

Were you perhaps intending to ask about a webflux authorization server? That question was asked in #152. See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644). I'm assuming that's the case, so I'm going to go ahead and close this as a duplicate.
