### ISSUE TITLE
OAuth2AuthorizationServerConsentTests fails when trying to retrieve buttons

### ISSUE THREAD

**Issue by adakevms** [spring-projects/spring-authorization-server#463]
This is my first time submitting an issue.  I hope I have followed the guidelines correctly. There was no need to submit a working example in this case, as the bug is reproducible as-is.

**Describe the bug**
The following lines fail in OAuth2AuthorizationServerConsentTests with a NullPointerException.
In whenUserConsentsToAllScopesThenReturnAuthorizationCode():

```
DomElement submitConsentButton = consentPage.querySelector("button[id='submit-consent']");
```

In whenUserCancelsConsentThenReturnAccessDeniedError():

```
DomElement cancelConsentButton = consentPage.querySelector("button[id='cancel-consent']");
```

**To Reproduce**
I output the consentPage as XML:

```
final HtmlPage consentPage = this.webClient.getPage(this.authorizationRequestUri);
System.out.println(consentPage.asXml());
```

Here are the relevant lines from the output. You can see that neither of the buttons contains an id.

```
<div class="form-group pt-3">
    <button class="btn btn-primary btn-lg" type="submit">
        Submit Consent
    </button>
</div>
<div class="form-group">
    <button class="btn btn-link regular" type="reset">
        Cancel
    </button>
</div>
```

**Expected Behavior**
The buttons are retrieved from the consent page correctly

**Comment by xialugui** [comment]
obviously your OAuth2AuthorizationEndpointFilter.java is not lastest:
![c4acab13f50498e3986f5398458bf09](https://user-images.githubusercontent.com/14935553/138389289-3b6cc190-56f3-423f-9afb-14b8904793a8.png)
there is my test:
![image](https://user-images.githubusercontent.com/14935553/138389530-2a078b80-8e30-4fa9-bc13-20449613b51e.png)
![image](https://user-images.githubusercontent.com/14935553/138389659-6c4b4857-05b3-4936-a4a4-0705f1c4d360.png)
So make sure you CODE LASTEST.
