### ISSUE TITLE
401 when hitting /oauth2/token with PKCE authorization_flow

### ISSUE THREAD

**Issue by ShannonHung** [spring-projects/spring-authorization-server#473]
Describe the bug
I want to implement PKCE flow in authorization server. I have already set `ClientSettings.builder().requireProofKey(true)`. After request with code_challenge and get the code. I use postman Post to `/auth2/token` with code_verifier. 
The way to make code_verifier and code_challege is implemented from this video 
https://www.youtube.com/watch?v=xEw5m1EV7ZY&t=1279s

However, when i want to get access_token, auth-server always give me 401 error. 
```json 
{
    "error": "invalid_client"
}
```
Here is my project: https://github.com/ShannonHung/PKCE_auth

How i test: 
1. Open authorization URL in browser
```
http://localhost:3000/oauth2/authorize?response_type=code&client_id=pig&code_challenge=x0TUH323lFGUGY46xb-K3erPjA5XrtVHelWz1Tc6xRc=&code_challenge_method=S256&scope=read
```

2. Login with username lengleng and password 123456, and this will redirect to consent page. 
3. accept the consent. This will redirect to :
```
http://127.0.0.1:9090/authorized?code=vkEKhr-ltf24KeYCGjpJGWNZDOhF0f7mLO89_PWxnX5Sxg5SZQEmy18Y6eepbIob3zmUNKTFLSyKLHg1_GB0wImzMngAqyNkgaPJz0oHHGWaTVGQFQd3XCCQAWcMvkj6
```

4. copy the code, and set the following in Postman (which follow in the video: https://www.youtube.com/watch?v=xEw5m1EV7ZY&t=1279s)
```
curl --location --request POST 'http://localhost:3000/oauth2/token?client_id=pig&code_verifier=LLrVdz2JKxBqePkp4X5NrFLb4cWl47cspdVwcVthgOk&code=vkEKhr-ltf24KeYCGjpJGWNZDOhF0f7mLO89_PWxnX5Sxg5SZQEmy18Y6eepbIob3zmUNKTFLSyKLHg1_GB0wImzMngAqyNkgaPJz0oHHGWaTVGQFQd3XCCQAWcMvkj6&grant_type=authorization_code&scope=read' \
--header 'Cookie: JSESSIONID=D5EC5CEAED017DE2148274E5B1A94A6E'
```

Request Method : POST
Basic Auth : None
Param grant_type : authorization_code
Param code : vkEKhr-ltf24KeYCGjpJGWNZDOhF0f7mLO89_PWxnX5Sxg5SZQEmy18Y6eepbIob3zmUNKTFLSyKLHg1_GB0wImzMngAqyNkgaPJz0oHHGWaTVGQFQd3XCCQAWcMvkj6
Param client_id : pig (I already try to include and exclude this param, result is still invalid_client)
Param scope: read
Param code_verifier：LLrVdz2JKxBqePkp4X5NrFLb4cWl47cspdVwcVthgOk
Hit Send

Expected behavior

I tried the reproduce step above to the sample project and getting access_token successfully.　（with client-secret method). But when i want to try PKCE method, which mean we are going to remvoe client-secret. 
In my project, I got invalid_client message.

I searched on the internet and try to implement the PKCE method. But there is no example except that youtube video... 
I stocked at here for two days...QQ

**Comment by meghraj27** [comment]
@jgrandja , could you please tell us how it is invalid? I'm also facing the same issue and this feature is completed according to wiki page.

**Comment by meghraj27** [comment]
@ShannonHung , the issue got fixed when I used same urlencoded redirect_uri during authorization and token fetch both.

**Comment by tksarul** [comment]
I am facing the same issue
