### ISSUE TITLE
Delete registered client

### ISSUE THREAD

**Issue by edwardzjl** [spring-projects/spring-authorization-server#475]
Currently RegisteredClientRepository exposes 3 methods, `save`, `findById` and `findByClientId`.

The problem is, once a client was created, there's no way to delete it. (Correct me if I'm wrong)

Should we add deletion support on the repository?

**Comment by jgrandja** [comment]
@edwardzjl At the moment, there is no functionality requiring the ability to delete a `RegisteredClient`, hence, the reason why there is no `RegisteredClientRepository.remove()` operation.

This might be needed later if a feature requires it, but for now, it's not needed so we won't be adding it.

If you require delete capability, you can simply provide your own implementation of `RegisteredClientRepository` and extend the delete capability.

**Comment by edwardzjl** [comment]
Extending `RegisteredClientRepository` sounds good to me, but I think `spring-authorization-server` should consider providing such function. As if a user found his client's credentials have been leaked, there's no way to disable (remove) the leaking client now.

**Comment by jgrandja** [comment]
@edwardzjl We are planning on adding a validation on whether a client is disabled before allowing access to a protected resource, e.g. /oauth2/token, /oauth2/revoke, /oauth2/introspect, etc.
