### ISSUE TITLE
RegisteredClient object doesn't deserialize without error

### ISSUE THREAD

**Issue by colin-riddell** [spring-projects/spring-authorization-server#481]
**Describe the bug**
`RegisteredClient` isn't deserializing properly, and throwng an unexpected error

**To Reproduce**
Run this test in a spring boot application
```java
static String inputJson = "{\n" +
			"\"id\": \"438318c7-2c7b-4471-b578-bd7d24e4a06a\",\n" +
			"\"clientId\": \"clientid\",\n" +
			"\"clientIdIssuedAt\": null,\n" +
			"\"clientSecret\": \"client-secret\",\n" +
			"\"clientSecretExpiresAt\": null,\n" +
			"\"clientName\": \"test\",\n" +
			"\"clientAuthenticationMethods\": [\n" +
			"{\n" +
			"\"value\": \"client_secret_post\"\n" +
			"}\n" +
			"],\n" +
			"\"authorizationGrantTypes\": [\n" +
			"{\n" +
			"\"value\": \"refresh_token\"\n" +
			"},\n" +
			"{\n" +
			"\"value\": \"authorization_code\"\n" +
			"}\n" +
			"],\n" +
			"\"redirectUris\": [\n" +
			"\"http://127.0.0.1:9010/callback\"\n" +
			"],\n" +
			"\"scopes\": [\n" +
			"\"read\",\n" +
			"\"openid\"\n" +
			"],\n" +
			"\"clientSettings\": {\n" +
			"\"settings\": {\n" +
			"\"settings.client.require-proof-key\": false,\n" +
			"\"settings.client.require-authorization-consent\": true\n" +
			"},\n" +
			"\"requireAuthorizationConsent\": true,\n" +
			"\"requireProofKey\": false\n" +
			"},\n" +
			"\"tokenSettings\": {\n" +
			"\"settings\": {\n" +
			"\"settings.token.reuse-refresh-tokens\": true,\n" +
			"\"settings.token.id-token-signature-algorithm\": \"RS256\",\n" +
			"\"settings.token.access-token-time-to-live\": \"PT5M\",\n" +
			"\"settings.token.refresh-token-time-to-live\": \"PT1H\"\n" +
			"},\n" +
			"\"reuseRefreshTokens\": true,\n" +
			"\"refreshTokenTimeToLive\": \"PT1H\",\n" +
			"\"idTokenSignatureAlgorithm\": \"RS256\",\n" +
			"\"accessTokenTimeToLive\": \"PT5M\"\n" +
			"}\n" +
			"}";

	@Test
	public void test() throws JsonProcessingException {
		ObjectMapper mapper = new ObjectMapper();
		RegisteredClient rc = mapper.readValue(inputJson, RegisteredClient.class);
		//  line: 10, column: 1] (through reference chain: 
		//org.springframework.security.oauth2.server.authorization.client.RegisteredClient["clientAuthenticationMethods"]->java.util.HashSet[0])
	}
```

The JSON object was created with this code: https://gist.github.com/sjohnr/0c6065d90d11a0f24bd3f15cbbaa8527

**Expected behavior**
I am not an expert, but I'd expect that object to deserialize correctly?

**Sample**

https://gist.github.com/colin-riddell/c1d6ec19d68d0f4edde433c9cb559ecd

Using Authorization Server 0.2.0
Jackson 2.12.5

Sincere apologies if this isn't correct, or if I've done something wrong and this isn't actually an issue.

**Comment by sjohnr** [comment]
Hi @colin-riddell. I don't believe that you can deserialize complex objects like this one without mixins, due to nested JSON structures. We have `OAuth2AuthorizationServerJackson2Module` for this purpose.

If you run that test in a project with the authorization server dependency, you can register the mixin and try it again. See [OAuth2AuthorizationServerJackson2ModuleTests](https://github.com/spring-projects/spring-authorization-server/blob/b455268fa1b801f244f2a94dac3d416d5e481397/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/jackson2/OAuth2AuthorizationServerJackson2ModuleTests.java#L50) for an example.

Does that resolve the issue for you?

**Comment by colin-riddell** [comment]
Ah, I wasn't aware of that. I'll give it a try and report back. Thanks

**Comment by colin-riddell** [comment]
Thanks @sjohnr After registering the mixin the error changes slightly to

 `Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class org.springframework.security.oauth2.server.authorization.client.RegisteredClient]: missing type id property '@class'`

Perhaps `RegisteredClient` deserialization isn't supported by that custom jackson module? 

I'll try to narrow the problem down further.

**Comment by sjohnr** [comment]
After registering the mixin, you'll get different JSON if you serialize it first. Thinking more about this though, I don't believe our mixin by itself is able to deserialize a `RegisteredClient`, as that's not the use case for it. It's designed for only attributes and metadata of the domain objects we persist via JDBC.

I'm assuming you're trying to serialize/deserialize the entire RegisteredClient via JSON so you can implement a remote `RegisteredClientRepository` as an HTTP client, correct? My suggestion would be to create your own simple data object to represent the registered client data for serialization to JSON, and not use the `RegisteredClient` domain object directly. You can then map to/from the domain object internally, similar to how it's done in this example [JpaRegisteredClientRepository](https://gist.github.com/sjohnr/0c6065d90d11a0f24bd3f15cbbaa8527).

I'm going to close this issue for now, as I can't think of a reason why we will be providing support in our Jackson module for serializing the entire `RegisteredClient` domain object. That would would need to be solved by the application, as mentioned above. If I've misunderstood something, let me know and we can reopen if needed.

**Comment by colin-riddell** [comment]
> I'm assuming you're trying to serialize/deserialize the entire RegisteredClient via JSON so you can implement a remote RegisteredClientRepository as an HTTP client, correct? 

That's correct. Got the JPA stuff happening on another service, and experimenting with using Feign to retrieve the RegisteredClient. Wouldn't deserialization support for `RegisteredClient` be something handy to have in authorization-server?

 I've been investigating what the mixin is able to deserialize, and yes `RegisteredClient` isn't supported. So I've been having a stab at creating a `RegistrationClientDeserializer` mixin along the same lines as the existing module support. 

If this works well, I'm assuming the mixin and target deserializer class can be kept in application code without too many problems?

**Comment by sjohnr** [comment]
Right, I don't see any problem with that. If you do create your own mixins, keep in mind you will have to share them in both places, as well as add the dependency on authorization server to your other service. It's often simpler to use your own pojo for data transport in these types of cases.

**Comment by colin-riddell** [comment]
Looking at it again think it might be a little messy-er to have a custom pojo to replace the `RegisteredClient`, actually.

 Especially since the pattern on the authorization server side starts by creating a `RegisteredClientRepository`. I wanted to inherit from `RegisteredClientRepository` meaning that a `CustomClientRepository` doesn't need to duplicate types and can remain polymorphic. That way the interface can be used for its intended purpose?
 
 If I introduce my own type here, I lose polymorphism with `RegisteredClient` and more awkwardly `RegisteredClientRepository` - the latter of which is arguably more sticky since it's methods promise to return objects of type `RegisteredClient`. I then need to do some awkward messing around when creating the `RegisteredClientRepository` to work with my custom client objects.

Can I ask you to re-consider your view on including deserialization mixin for the `RegisteredClient` object as a target? 🙏🏻 

 It would greatly reduce the complexity of the code on our auth-server and it's future maintainability. Presumably it's already a suitable serialization target - so why not also support deserialisation? Other developers would be able to make use of this in the future. It would mean that no changes would be needed on the `RegisteredClientRepository` and that interfaces contract could be used.

Happy to put up a PR for that if that helps?

**Comment by sjohnr** [comment]
Hi @colin-riddell. The goal of this framework is to support a spec-compliant authorization server implementation. We have not yet come across a use-case for serializing the entire `RegisteredClient` to JSON. The pattern used in the framework is to store the `registeredClientId`, and use the `RegisteredClientRepository` to look up the `RegisteredClient` when needed. This provides applications with complete control of how a `RegisteredClient` is stored. So it doesn't look like that would be a very likely candidate. If something changes in the future, we could revisit that, but it's not something needed by the framework right now.

So at the moment, it will be completely up to your application to provide this support however you want it to work in your environment.

**Comment by colin-riddell** [comment]
For anyone who finds this and wants to be able to deserialize RegisteredClient objects: https://gist.github.com/colin-riddell/b80dcd9f07a0a28850cd745b5efc519a
