### ISSUE TITLE
Supported a post-processing the `OAuth2AuthorizationCodeRequestAuthenticationToken` 

### ISSUE THREAD

**Issue by amexboy** [spring-projects/spring-authorization-server#484]
**Expected Behavior**
Supported a pluggable way to post-process the `OAuth2AuthorizationCodeRequestAuthenticationToken` in `OAuth2AuthorizationEndpointFilter` 

**Current Behavior**
No way to post-process the token

**Context**
I am trying to create a custom authorization code grant flow in which I show different login views based on the details in the authorization code. I also would like to validate some custom authorization parameters (custom logo, display name..)

Currently, I am achieving the behavior using the following hack while configuring the 

```
 public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) {
        var entryPoint = new LoginUrlAuthenticationEntryPoint("/oauth2/login");
        entryPoint.setUseForward(true)

       return http
                .antMatcher("/oauth2/authorize").httpBasic(httpBasic -> httpBasic.authenticationEntryPoint(entryPoint))
                // ... omited for bravity
               .build()
```

By setting `useForward` I get access to the query params for the authorize endpoint and I am able to rebuild (infer) the code request token in my custom login endpoint. I do extra validations that I need for the custom login page and commence the login flow. 

Two inconveniences with this solution:
- Validation is done when login is started (extra processing that could have been avoided)
- I have to load the client information again and determine the redirect uri (using a duplicated code from the library)

I hope my request is clear

**Comment by jgrandja** [comment]
@amexboy You could post-process the `OAuth2AuthorizationCodeRequestAuthenticationToken` by setting a custom `AuthenticationConverter` via `OAuth2AuthorizationEndpointFilter.setAuthenticationConverter()`. The custom `AuthenticationConverter` could delegate to the default `OAuth2AuthorizationCodeRequestAuthenticationConverter` and then post-process the returned `OAuth2AuthorizationCodeRequestAuthenticationToken`.

See this [test](https://github.com/spring-projects/spring-authorization-server/blob/088d9a8e3419ea96756d53935fcb63c28a758972/oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2AuthorizationCodeGrantTests.java#L735) on how to configure a custom `AuthenticationConverter`.

I'm going to close this as the solution provided will work for your use case.

**Comment by amexboy** [comment]
@jgrandja I missed that one! That works very well for my case, thank you for your assistance!
