### ISSUE TITLE
Registration access token cannot be de-serialized when calling Client Configuration Endpoint

### ISSUE THREAD

**Issue by ovidiupopa91** [spring-projects/spring-authorization-server#495]
Because the initial registration access token saves the authorized scope in a `SingletonSet` when calling the Client Configuration Endpoint the access token cannot be deserialized because there's no Mixin registered. 

A new mixin and custom deserializer should be registered in `OAuth2AuthorizationServerJackson2Module`

**Comment by jgrandja** [comment]
@ovidiupopa91 Instead of 

> A new mixin and custom deserializer

Changing `Collections.singleton()` to new `HashSet()` would be the easiest fix.

**Comment by ovidiupopa91** [comment]
@jgrandja that's true. This is how it was initially, but in your polish commit you've changed it and I think it makes sense to have an immutable `Set` here. I can change it to `Collections.unmodifiableSet`
