### ISSUE TITLE
Add reference documentation

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#499]
This issue will serve to provide a content outline for the reference documentation.

Our goal is to avoid the "fluff" and only write content that will be valuable to our users and community. The only way to achieve this is too directly involve our users in driving out the content they want to see.

**We'll be prioritizing the "How-to" Guides based on upvotes.** Please log an issue for a new How-to Guide if it's not already listed.

We also encourage users to log an issue recommending new content that is not already listed in the proposed [content outline](https://github.com/spring-projects/spring-authorization-server/issues/499#issuecomment-989022953).

**Comment by NotFound403** [comment]
Architecture Pic

**Comment by mabujaber** [comment]
- Best practice section for web, mobile, server, and ..etc

**Comment by sjohnr** [comment]
Since I missed linking the commit, see 525eca63d247478b0f4bbc5aed2d998eef70512f (initial draft of How-to: Implement the core services with JPA)

**Comment by NotFound403** [comment]
Relation between Spring Security and Spring Authorization Server

**Comment by mabujaber** [comment]
there is alot to do in the documentation. I started working on an authorization server integrated with spring security authentication and found a lot of stuff need to be clarified such as
1- phone verification page after the user login 
2- how to specify multiple login pages based on the client_id 
3- how to make multi-tenancy and this mostly will be done through an extra table linked with clients and users. 

some idea to help people start their project, I'll contribute my findings for any of above points

**Comment by colin-riddell** [comment]
Where will the documentation end up being hosted? Is there any way to review work-in-progress docs and help out with contribution to that?

**Comment by sjohnr** [comment]
Eventually, it will be hosted on docs.spring.io, but it might be a bit before we automate pushing documentation artifacts out there.

If you'd like to review progress, check out the [`docs`](https://github.com/spring-projects/spring-authorization-server/tree/main/docs) directory. You can run `npm install` and then `antora local-antora-playbook.yml` to build the site, then launch `docs/build/site/index.html` in your browser.

Not sure we're quite ready for lots of documentation contributions to begin flowing in yet, as we're still sorting out how it's going to look and nothing has settled yet. The most useful contributions at this point will be:

* Suggestions for content and guides, and up-votes to help us prioritize the ones we work on
* Feedback on any drafted content so we know whether we're on the right track (for example, "This was helpful..." or "The guide seems to be missing this piece of information..." etc.)
* Quick/easy updates such as typo fixes, etc.

Hopefully it will settle quickly and we can begin to divide up work among contributors at a later time.

**Comment by mabujaber** [comment]
One more use case might be needed in the documentation when registration is done on how to trigger authorization flows and return redirect_uri without entering the login credential again. 
the flow as following
1- registering -> 2- implicitly trigger authorization flow and login with credential entered in step 1 -> 3- authorization code return with redirect uri configured

**Comment by jgrandja** [comment]
**NOTE:** The reference documentation is a _"work-in-progress"_ and lives in the [ref-doc](https://github.com/spring-projects/spring-authorization-server/tree/ref-doc) branch.

**Comment by NotFound403** [comment]
> Eventually, it will be hosted on docs.spring.io, but it might be a bit before we automate pushing documentation artifacts out there.
> 
> If you'd like to review progress, check out the [`docs`](https://github.com/spring-projects/spring-authorization-server/tree/main/docs) directory. You can run `npm install` and then `antora local-antora-playbook.yml` to build the site, then launch `docs/build/site/index.html` in your browser.
> 
> Not sure we're quite ready for lots of documentation contributions to begin flowing in yet, as we're still sorting out how it's going to look and nothing has settled yet. The most useful contributions at this point will be:
> 
> * Suggestions for content and guides, and up-votes to help us prioritize the ones we work on
> * Feedback on any drafted content so we know whether we're on the right track (for example, "This was helpful..." or "The guide seems to be missing this piece of information..." etc.)
> * Quick/easy updates such as typo fixes, etc.
> 
> Hopefully it will settle quickly and we can begin to divide up work among contributors at a later time.

[antora](https://gitlab.com/antora/antora) is need. Anyone can install it by `npm install -g @antora/cli @antora/site-generator`

**Comment by dfcoffin** [comment]
@NotFound403 The [docs ](https://github.com/spring-projects/spring-authorization-server/tree/main/docs)link returns a 404.

**Comment by NotFound403** [comment]
> @NotFound403 The [docs ](https://github.com/spring-projects/spring-authorization-server/tree/main/docs)link returns a 404.

The git branch has been moved to `ref-doc`, so u need to checkout `ref-doc`

**Comment by sjohnr** [comment]
Thanks @dfcoffin @NotFound403. I've updated the link in all comments.

**Comment by jgrandja** [comment]
The reference documentation is a "work-in-progress" and lives in the [docs](https://github.com/spring-projects/spring-authorization-server/tree/main/docs) directory.
