### ISSUE TITLE
Support opaque access tokens

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#500]
The currently supported format for access tokens is JWT. We should also support opaque access tokens.

Related gh-414

**Comment by dfcoffin** [comment]
This continues to be pushed to the next milestone release.  Any idea what it will take to finally support opaque access tokens?  I have a UT at Dallas capstone project starting today that requires an authorization server that supports opaque access tokens.

**Comment by jgrandja** [comment]
Apologies @dfcoffin but there is a lot of work still to do and we're doing our best to prioritize features.

This one is top priority for `0.2.3` so I don't see it getting pushed back further.

**Comment by dfcoffin** [comment]
Thanks, @jgrandja.

**Comment by jgrandja** [comment]
@dfcoffin I just merged opaque access token support! Thanks for your patience.

As you know, we're in the process of writing the reference documentation so there is no documentation on usage just yet.

Take a look at the test [OAuth2TokenIntrospectionTests.requestWhenObtainReferenceAccessTokenAndIntrospectThenActive()](https://github.com/spring-projects/spring-authorization-server/blob/32414451f5163235739c045a3ce361bcc2eec599/oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2TokenIntrospectionTests.java#L253), which demonstrates how to configure a `RegisteredClient` for opaque access tokens and performs obtaining the token and then introspecting the token.

FYI, the `AuthorizationServerConfiguration` in this test completely disables JWT support. If you also want to enable JWT support along with opaque tokens, then simply register a `JWKSource<SecurityContext>` `@Bean` or a `JwtEncoder` `@Bean`. Alternatively, you can register a `OAuth2TokenGenerator` `@Bean`, with whatever capabilities you require. Take a look at the default in [OAuth2ConfigurerUtils.getTokenGenerator()](https://github.com/spring-projects/spring-authorization-server/blob/32414451f5163235739c045a3ce361bcc2eec599/oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2ConfigurerUtils.java#L93).

Please give this a try and would love to hear your feedback on usage. We want to ensure the API is easy to use so feedback on this is important.

Let me know if you have any questions.
Thanks.

**Comment by dfcoffin** [comment]
@jgrandja Thanks for the notification.  I have been out of town since February 23rd and will return on March 8th.  I'll try to find time to generate a Spring Authorization Server and let you know the results.  Thanks for making this the primary issue for verstion 0.2.3!
