### ISSUE TITLE
Add user authorities and roles in Access Token

### ISSUE THREAD

**Issue by amitkhurana92** [spring-projects/spring-authorization-server#502]
**Expected Behavior**
The access token returned by the auth server should contain the authorities and roles which are provided to the specific user. 

**Current Behavior**
I have created a below user

User
```
@Bean
	public UserDetailsService userDetailsService() {
		UserDetails userDetails = User.withDefaultPasswordEncoder()
				.username("amit")
				.password("password")
				.roles("ADMIN")
				.authorities("READ")
				.authorities("WRITE")
				.build();
		return new InMemoryUserDetailsManager(userDetails);
}
```
Client
```
	@Bean
	public RegisteredClientRepository registeredClientRepository() {
		RegisteredClient loginClient = RegisteredClient.withId(UUID.randomUUID().toString())
				.clientId("control-room")
				.clientSecret("{noop}control-room")
				.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
				.redirectUri("http://127.0.0.1:8081/login/oauth2/code/login-client")
				.redirectUri("http://127.0.0.1:8081/authorized")
				.scope(OidcScopes.OPENID)
				.scope(OidcScopes.PROFILE)
				.clientSettings(ClientSettings.builder().requireAuthorizationConsent(true).build())
				.build();
		return new InMemoryRegisteredClientRepository(loginClient, registeredClient);
	}
```
The payload of the access token is 

```
{
  "sub": "amit",
  "aud": "control-room",
  "nbf": 1637159481,
  "scope": [
    "openid",
    "profile"
  ],
  "iss": "http://localhost:9000",
  "exp": 1637159781,
  "iat": 1637159481
}
```
So it basically contains only the scope defined in the client and does not contain the roles and authorities (ADMIN, READ, WRITE) of the user which is authenticated.

If I'm missing some configuration here then please share the same.

**Comment by jgrandja** [comment]
@amitkhurana92 You can customize the `Jwt` claims by registering a `@Bean` of type `OAuth2TokenCustomizer<JwtEncodingContext>`. This [test](https://github.com/spring-projects/spring-authorization-server/blob/d4357197c9673eb1c040938859c726beb3e4337c/oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2AuthorizationCodeGrantTests.java#L283) demonstrates how to add a custom `authorities` claim.

I'll close this as the test provided is the approach to use to customize the `Jwt` access token.
