### ISSUE TITLE
Table OAUTH2_REGISTERED_CLIENT not found when using JdbcOAuth2AuthorizationService with h2

### ISSUE THREAD

**Issue by sharetute** [spring-projects/spring-authorization-server#506]
## Describe the bug

I try to use the JDBC implementation of the different services into the authorisation server config.  
I'm facing a strange issue with JdbcOAuth2AuthorizationService. The table is well populated once the user is connected but I get an Exception : 

`Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "OAUTH2_REGISTERED_CLIENT" not found; SQL statement:`

I don't know if it is a bug or a issue in my configuration.

## To Reproduce

Using the sample : 

on the h2-in-memory branch or the h2-file branch

1. access to http://localhost:8080
2. once you're redirected to http://localhost:12001/login, log in with identifiers john:pass
3. you get a redirection issue, and in the logs of the Authorization server you get a **Table not found** exception.
4. go to the h2 console of the authorization server : http://localhost:12001/h2 with url=jdbc:h2:mem:oauth2 and identifiers= sa:password you can see that the OAUTH2_AUTHORIZATION table has been populated in spite of the Exception.

Then just remove the OAuth2AuthorizationService bean or switch to the without-jdbc-auth-service branch, restart the client and the auth server and try again, everything works fine.

## Expected behavior

Not getting a **table not found exception**

## Sample

I started with [this sample](https://github.com/Baeldung/spring-security-oauth/tree/master/oauth-authorization-server) with an in memory configuration.

You can find my sample [here ](https://github.com/sharetute/tutorials/tree/master/spring-oauth2-resource-client), and the authorizationServerConfig with the JDBC implementation [here](https://github.com/sharetute/tutorials/blob/master/spring-oauth2-resource-client/authorization-server/src/main/java/com/sharetute/config/AuthorizationServerConfig.java).
The main branch use MySQL and need a database called spring_oauth available at localhost:3306
The branch h2-in-memory use a h2 in memory database
The h2-file use a file for the database on Windows located into C:\Users\username\h2 databases

Thanks !

**Comment by sharetute** [comment]
The problem seems to be related to the H2 in memory database, it doesn't happen with a MySQL server.

**Comment by edwardzjl** [comment]
Have you tried uncomment `spring.jpa.defer-datasource-initialization: true` in your configuration?

You may also want to check [this doc](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts).

**Comment by sharetute** [comment]
> Have you tried uncomment `spring.jpa.defer-datasource-initialization: true` in your configuration?
> 
> You may also want to check [this doc](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts).

This option is used to generate the schema from entities with JPA before using the files schema and data Sql, but it is not the case here. I noticed that one of the samples use a Jdbc implementation with H2 and it works perfectly, so I'll check the differences more further to see what 's wrong in my config.

**Comment by jgrandja** [comment]
@sharetute 

> The problem seems to be related to the H2 database (in memory or with a file), it doesn't happen with a MySQL server.

The [messages sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) uses H2 (in-memory) as defined in the [configuration](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/default-authorizationserver/src/main/java/sample/config/AuthorizationServerConfig.java#L108) and is working. The issue you are facing is likely a misconfiguration or environment related.

I'm going to close this as the sample works with H2.

**Comment by sharetute** [comment]
> @sharetute
> 
> > The problem seems to be related to the H2 database (in memory or with a file), it doesn't happen with a MySQL server.
> 
> The [messages sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) uses H2 (in-memory) as defined in the [configuration](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/default-authorizationserver/src/main/java/sample/config/AuthorizationServerConfig.java#L108) and is working. The issue you are facing is likely a misconfiguration or environment related.
> 
> I'm going to close this as the sample works with H2.

Thanks, I will use your sample.
