### ISSUE TITLE
spring-authorization-server 0.2.0 How to support password mode

### ISSUE THREAD

**Issue by peng-my** [spring-projects/spring-authorization-server#509]
**Expected Behavior**

Able to get token
**Current Behavior**

{
    "error_description": "OAuth 2.0 Parameter: grant_type",
    "error": "unsupported_grant_type",
    "error_uri": "https://datatracker.ietf.org/doc/html/rfc6749#section-5.2"
}
**Context**

java

**Comment by pxzxj** [comment]
See #349 and #466
