### ISSUE TITLE
Customize oidc discover endpoint

### ISSUE THREAD

**Issue by bingyanzhang** [spring-projects/spring-authorization-server#512]
**Expected Behavior**
Able to customize oidc discover endpoint. It seems there is no way to customize it for now. OidcProviderConfigurationEndpointFilter.DEFAULT_OIDC_PROVIDER_CONFIGURATION_ENDPOINT_URI.
**Current Behavior**
OidcProviderConfigurationEndpointFilter use default value "/.well-known/openid-configuration" and it seems there is no way to customize the URL.

**Comment by jgrandja** [comment]
@bingyanzhang As per spec, in [Section 4.  Obtaining OpenID Provider Configuration Information](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig):

> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer

I'm going to close this as the spec states the path must be formed using `/.well-known/openid-configuration` and therefore cannot be customized.
