### ISSUE TITLE
Failed to call endpoint userinfo

### ISSUE THREAD

**Issue by rafaelrddc** [spring-projects/spring-authorization-server#521]
Every time I try to call the userinfo endpoint I get a 401 return.

Example
curl --location --request GET 'http://127.0.0.1:9080/userinfo' --header 'Authorization: Bearer token'

To perform this test I used the repository's own test project

**Comment by keyhook** [comment]
There should be a filter that extracts the bearer token from the request header & set to the `SecurityContextHolder` beforehand. With the current implementation, the request can not reach the `OidcUserInfoEndpointFilter` but stops at the `FilterSecurityInterceptor` because of no authenticated principal (anonymous instead).

Waiting for the fix now.

**Comment by xie-heng** [comment]
Try to add ResourceServer support in your code, I fix the same 401 problem.

httpSecurity.XXX.oauth2ResourceServer(xxx).build()

[https://stackoverflow.com/questions/62890622/how-to-get-userinfo-by-jwt-token-in-spring-security-oauth2-authorization-server](this) may help.

**Comment by jgrandja** [comment]
@rafaelrddc I suspect the issue is related to misconfiguration and/or invalid request (e.g. invalid token).

The UserInfo endpoint is working correctly. Please see the integration test `OidcUserInfoTests` to see how to setup the configuration and request.

**Comment by bostandyksoft** [comment]
It works, because example is configured with OAuth2ResourceServerConfigurer. It appends BearerTokenAuthenticationFilter, that converts header Authorization to security Authentication. But in common, i don't think, that it is practicated

**Comment by rafaelrddc** [comment]
@jgrandja  What do you think we added in the project examples this configuration?

I can try to do a PR with this improvement.

**Comment by sjohnr** [comment]
@rafaelrddc as @jgrandja mentioned, the endpoint is working as designed. We intentionally designed it to be behind the `FilterSecurityInterceptor` and do not require a change at this time. If you want to use the UserInfo endpoint, please enable resource server support in your configuration, as demonstrated in the `OidcUserInfoTests`.

**Comment by rafaelrddc** [comment]
I understand, and I did the test and it really is working correctly.

My point would be to add this configuration in the project examples. Not to generate this doubt again.

**Comment by sjohnr** [comment]
> My point would be to add this configuration in the project examples. Not to generate this doubt again.

Thanks @rafaelrddc. I would encourage you to upvote #537 as that guide would contain all the information I think you're looking for/suggesting.
