### ISSUE TITLE
Add null check in clientSettings and tokenSettings methods for RegisteredClient builder

### ISSUE THREAD

**Issue by rayman245** [spring-projects/spring-authorization-server#522]
**Expected Behavior**
The RegisteredClient.Builder for clientSettings and tokenSettings should skip assigning the value passed if it's null.

**Current Behavior**
Both builder methods above would assign if its null and not use default settings which we see in the sample project.
![image](https://user-images.githubusercontent.com/11938827/144742124-9bbce991-b4b6-4a63-b825-e3316d6e7881.png)

**Context**
I am getting an error with this implementation.
![image](https://user-images.githubusercontent.com/11938827/144742028-c9ca01bd-51e3-409c-8363-4599e75ca191.png)
![image](https://user-images.githubusercontent.com/11938827/144742018-867e8a48-a067-4d47-bd3f-673d53f53fc8.png)

I know that we can do a null checking before building, but would be more convenient and helps reduce redundant validation if need to maintain in multiple locations.

**Comment by rayman245** [comment]
This is the current implementation, to make it workable.

![image](https://user-images.githubusercontent.com/11938827/144742726-60a4f48d-6679-4f88-aa6b-a70710cf92fa.png)

**Comment by jgrandja** [comment]
@rayman245 

Based on the stacktrace, it doesn't make sense to pass `null` to `TokenSettings.withSettings(null)`.

The javadoc states:

> Constructs a new `Builder` with the provided settings.

However, the `settings` is NOT provided since it's `null`. The exception thrown by the assertion is valid.

Instead, you should call `TokenSettings.builder()` to return the default settings.
