### ISSUE TITLE
Authorization code flow without user interaction

### ISSUE THREAD

**Issue by Blackmail92** [spring-projects/spring-authorization-server#524]
**Expected Behavior**
Login can be performed through post params, OR with login form.

**Current Behavior**
Login can be done with Login form only.

**Context**
I am trying to implement the current spring auth server to our application. We used to work with the Resource Owner Password flow, but since it became unrecommended to use, I switched to authorization code. Problem is - the flow of the auth code grant type is a bit annoying with redirects and a l;ogin form, requiring user interaction. For now when i request the /oauth/authorize endpoint, I need to login with the form. Problem is - our app requires api authorization, we cannot have the user type his creds to the login form. Is it possible somehow to pass the form and send the username/password directly to the authorization endpoint to get redirected with the code as query param? It is pretty easy to work from that point, but the login form really destroys the logic we need..

Unfortunately, other grant types are not appliable for us, as we have a number of users, but need only few clients for our microservices..

**Comment by edwardzjl** [comment]
You can custom your own rest login endpoint in spring security and get rid of the login form, but it's out of authorization-server's scope.

**Comment by jgrandja** [comment]
@Blackmail92 The OAuth 2.1 protocol implementations provided by Spring Authorization Server are implemented per spec. We would not implement off spec. This would be the responsibility of the consuming application.

As @edwardzjl suggested, there are many ways to implement login using Spring Security. Please see the reference documentation for [Authentication](https://docs.spring.io/spring-security/reference/servlet/authentication/index.html).
