### ISSUE TITLE
Include artifact coordinates in documentation

### ISSUE THREAD

**Issue by boerngen-schmidt** [spring-projects/spring-authorization-server#526]
Hello,

currently I found it quite a hassle to find the atrifact coodinates to use with maven or gradle.
It would be great if you could include a brief maven configuration like https://github.com/spring-projects/spring-data-mongodb#maven-configuration

Otherwise thanks for your awesome work.

**Comment by jgrandja** [comment]
Thanks for the request @boerngen-schmidt.

This will be covered in gh-499 in the section "Getting Started -> Installing Spring Authorization Server".

I'll close this as a duplicate.
