### ISSUE TITLE
Incorrect project information in pom.xml 

### ISSUE THREAD

**Issue by boerngen-schmidt** [spring-projects/spring-authorization-server#527]
**Describe the bug**
Information about the project in pom.xml seem to be wrong.

**To Reproduce**
See https://search.maven.org/artifact/org.springframework.security/spring-security-oauth2-authorization-server/0.2.1/jar

```xml
<url>https://spring.io/spring-security</url>
<scm>
	<connection>scm:git:git://github.com/spring-projects/spring-security</connection>
	<developerConnection>scm:git:git://github.com/spring-projects/spring-security</developerConnection>
	<url>https://github.com/spring-projects/spring-security</url>
</scm>
```

**Expected behavior**
Expected SCM to point this repository
Expected URL to point to this repository

**Comment by jgrandja** [comment]
Thanks for the report @boerngen-schmidt.

We'll look into this shortly.

**Comment by jgrandja** [comment]
@sjohnr Looks like we'll need to integrate the [MavenPublishingConventionsPlugin](https://github.com/spring-projects/spring-security/blob/main/buildSrc/src/main/java/org/springframework/gradle/maven/MavenPublishingConventionsPlugin.java) into this project.

**Comment by jgrandja** [comment]
This has been resolved in gh-674 via the [SpringMavenPublishingConventionsPlugin](https://github.com/spring-projects/spring-authorization-server/blob/main/buildSrc/src/main/java/org/springframework/gradle/maven/SpringMavenPublishingConventionsPlugin.java#L88). Closing as duplicate.
