### ISSUE TITLE
How-to: Obtain an access token using a specific grant_type

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#532]
Publish a guide on How-to: Obtain an access token using a specific `grant_type`:

- `authorization_code`
- `client_credentials`
- `refresh_token`

Related gh-499

**Comment by likith187** [comment]
Hey @jgrandja Can I work on this?

**Comment by jgrandja** [comment]
Thanks for your interest @likith187.

We are prioritizing "How-to guides" based on up-votes and this one doesn't have any yet so we'll wait on this one.

As well, we're still early in writing the reference documentation and have a few things we need to iron out as far as the format goes. Our plan is to release the initial version in `0.3.0` and then will likely open things up to external contributions at that point.

**Comment by jgrandja** [comment]
Closing this issue as it's redundant given the [samples](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) demonstrate the various `grant_type` flows.
