### ISSUE TITLE
How-to: Authenticate a user in a Single Page Application with PKCE

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#539]
Publish a guide on How-to: Authenticate a user in a Single Page Application with PKCE

Related gh-499, gh-536

**Comment by vakho10** [comment]
I am trying to authenticate Angular app using PKCE but am getting error. I guess I have a bad server configuration. Could you direct me to some example?

**Comment by sjohnr** [comment]
@vakho10, take a look at [this sample](https://github.com/sjohnr/spring-authorization-server/tree/bff-demo/samples/angular-client) I worked up for [a recent webinar on SAS](https://www.brighttalk.com/webcast/14893/528772) which focused on SPAs. You will want to browse some of the previous commits to that branch. You may also benefit from watching the recording of the webinar.
