### ISSUE TITLE
How-to: Authorize an access token containing custom authorities

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#542]
Publish a guide on How-to: Authorize an access token containing custom authorities, e.g. roles, groups, permissions, etc.
- How-to: Customize the headers / claims in a JWT

Related gh-499

**Comment by ddubson** [comment]
@jgrandja - I'd like to work on this how-to. May I request this assignment?

**Comment by jgrandja** [comment]
Thanks @ddubson ! The issue is yours 👍

**Comment by jgrandja** [comment]
@ddubson I wouldn't bother with the Google OIDC and GitHub login as it would require setup on the provider side to return certain claims and would make the doc more complicated. Let's just focus on the `User` configured in the `UserDetailsService` and configure roles, groups, permissions there and show how to map them to the claims in the JWT access token.
