### ISSUE TITLE
How-to: Implement the core services with JPA

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#545]
Publish a guide on How-to: Implement the core services with JPA:

- `RegisteredClientRepository`
- `OAuth2AuthorizationService`
- `OAuth2AuthorizationConsentService`

Related gh-499

**Comment by sjohnr** [comment]
See 36d18312b07b3a168de44d3cbf2624dced9a43cc (initial draft)

**Comment by jgrandja** [comment]
Merged via 8d08570
