### ISSUE TITLE
OAuth2AccessTokenResponseHttpMessageConverter class should be public for custom token response handling

### ISSUE THREAD

**Issue by mikesaurus** [spring-projects/spring-authorization-server#559]
**Expected Behavior**
When writing a custom AuthenticationSuccessHandler to customize the token response, the Spring OAuth2AccessTokenResponseHttpMessageConverter class should be available to write the token response back to the client.

**Current Behavior**
Writing the token response back to the client in a custom AuthenticationSuccessHandler currently requires duplication of the logic encapsulated within the package scope OAuth2AccessTokenResponseHttpMessageConverter class.

**Context**
I have a custom AuthenticationSuccessHandler that I am configuring on the token endpoint filter so that I can return SMART OAuth data in the additional parameters of the access token response. I have copied the OAuth2AccessTokenResponseHttpMessageConverter class into my code base, but it would be cleaner to simply use the code that already exists in the Spring code base.

**Comment by mikesaurus** [comment]
At least until upgrading to Spring Security 5.6.0 GA and the class is presumably removed.

**Comment by mikesaurus** [comment]
This should probably be closed.  The existing Spring Security implementation (pre-5.6.0) works fine until the upgrade to 5.6.0+.  No need to change the Spring Auth Server code for a temporary fix.

**Comment by sjohnr** [comment]
Thanks @mikesaurus. I think the update to 5.6 will be high on the list of priorities. I'll close this for now.
