### ISSUE TITLE
Allow localhost redirect URIs for development 

### ISSUE THREAD

**Issue by GrmpfNarf** [spring-projects/spring-authorization-server#565]
**Expected Behavior**
Redirect URIs which pointing on localhost should be allowed while developing.

**Current Behavior**
Currently when I try to use a redirect URI which points to localhost an invalid request is displayed because in 
https://github.com/spring-projects/spring-authorization-server/blob/28ac43bd503db92a13ec91698120e14af2ecc10d/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L459
it is checked for localhost and the redirect URI is marked as invalid.

For developing and local testing this is odd. I can prevent this by using 127.0.0.1 instead of localhost which is not very nice and makes the check obsolete.

**Solution suggestion**
Maybe it is possible to set a parameter to turn on/off this check so it will be possible to use it in higher stages and disable it in develop.

**Comment by jgrandja** [comment]
@GrmpfNarf The `redirect_uri` validation has been implemented as per spec. See the [reference](https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L460) for further details.


However, you can override the default `redirect_uri` validation using a custom `OAuth2AuthenticationValidator` configured via `OAuth2AuthorizationCodeRequestAuthenticationProvider.setAuthenticationValidatorResolver()`. Here's a full working [sample](https://github.com/sjohnr/spring-authorization-server/commit/99197740e1a917ce33bbc6706b42cdf05281d9f7#diff-f7f3c2238979bfb588b563ee1c3b92c929dedf52402f23229eccdef829cef699R107).
