### ISSUE TITLE
Make default OAuth2AuthenticationValidators public and handle validation error more globally

### ISSUE THREAD

**Issue by GrmpfNarf** [spring-projects/spring-authorization-server#570]
**Expected Behavior**
The implemented default OAuth2AuthenticationValidators should be public.

**Current Behavior**
Currently they are private.

**Context**
As suggest from @jgrandja in #565 I tried to replace the redirect URI validation by an custom ``authenticationValidatorResolver``. 
The default ``authenticationValidatorResolver`` contains two validators. One for the redirect URI and one for the scope. There is currently no way to add/replace one of the validator I just can replace the whole ``authenticationValidatorResolver``.
If I want to do that I can't use the ``DefaultScopeOAuth2AuthenticationValidator`` because it is a private inner class of ``OAuth2AuthorizationCodeRequestAuthenticationProvider``. 

So to replace or add a validator to the ``authenticationValidatorResolver`` I have to reimplement the other validators. To prevent this it would be better when the default validators are public so I can just use them.

Furthermore implementing a custom ``OAuth2AuthenticationValidator`` produces very much code duplication. Because the validators are calling the ``throwError`` method which is a private method inside the ``OAuth2AuthorizationCodeRequestAuthenticationProvider`` with a big complexity which must be copied when we expect the same behavior of validator error handling from the custom ``OAuth2AuthenticationValidator``. Maybe the validators can return a boolean or throw a kind of ``ValidationException`` which is then handled from the calling method. Becuase all information we need for calling ``throwError`` is already present in the calling method.

**Comment by sjohnr** [comment]
Hi @GrmpfNarf, we unfortunately have to start by conservatively releasing features and related utility code as private implementations, because opening up everything as public quickly leads to a large footprint of utility code that we need to support.

In this case, I believe that you can omit a mapping in the map for a validator (e.g. scope) that you don't want to implement, and it will fall back to the default. Just comment it out and restart. Can you please try this and verify that it resolves your issue? I'm going to close this, as I believe that will resolve it, but if not let me know and we will reopen this to investigate further.

**Comment by GrmpfNarf** [comment]
Hi,
no this won't resolve my two issues.

First:
The ``OAuth2AuthorizationCodeRequestAuthenticationProvider`` will use the validators from the ``authenticationValidatorResolver`` which I have to completly override when I want to use a custom validator. So it can fall back to the default. There is also no method to add/override an validator to the default ``authenticationValidatorResolver``.

Take a look at the following lines:
https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L81

https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L87

https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L411

https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L608

Second:
Even if I can use the the default validators it is nearly impossible to provide an custom validator because the whole validation error handling is private inside the ``OAuth2AuthorizationCodeRequestAuthenticationProvider``. I have to copy the whole ``throwError`` method behavior.

**Comment by sjohnr** [comment]
Hi @GrmpfNarf.

> it can't fall back to the default. There is also no method to add/override an validator to the default `authenticationValidatorResolver`.

As I mentioned above, please try providing an `authenticationValidatorResolver` without a `OAuth2ParameterNames.SCOPE`. See these lines:

https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L282-L287

The internal behavior falls back to the default when a parameter name is not specified in the user-provided implementation. I do believe this will work for you.

> Even if I can use the the default validators it is nearly impossible to provide an custom validator because the whole validation error handling is private inside the `OAuth2AuthorizationCodeRequestAuthenticationProvider`. I have to copy the whole `throwError` method behavior.

I know it's frustrating to need to copy/paste this code. Error handling is an area that will hopefully continue to be enhanced in the future as the project matures. However, we do not want to begin opening up core utility classes simply for convenience at this stage of the project (or possibly ever).

Feel free to [contact me directly](https://twitter.com/sjohnr) if you would like to discuss this in more detail, including brainstorming ideas for automating solutions to these problems in your project. I'm happy to help if I can!

**Comment by GrmpfNarf** [comment]
> Hi @GrmpfNarf.
> 
> > it can't fall back to the default. There is also no method to add/override an validator to the default `authenticationValidatorResolver`.
> 
> As I mentioned above, please try providing an `authenticationValidatorResolver` without a `OAuth2ParameterNames.SCOPE`. See these lines:
> 
> https://github.com/spring-projects/spring-authorization-server/blob/82e4f3a345101b454bc19d18fa0c127c6274439e/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L282-L287
> 
> The internal behavior falls back to the default when a parameter name is not specified in the user-provided implementation. I do believe this will work for you.
> 

You are right, sorry I missed that.

**Comment by GrmpfNarf** [comment]
> Feel free to contact me directly if you would like to discuss this in more detail, including brainstorming ideas for automating solutions to these problems in your project. I'm happy to help if I can!

Is there any other way except of twitter to contact you ?

**Comment by sjohnr** [comment]
Twitter is the best way. But you can email me as well. My vmware address is sriesenberg.
