### ISSUE TITLE
Upgrade to Gradle 7

### ISSUE THREAD

**Issue by think-info** [spring-projects/spring-authorization-server#572]
**Describe the bug**
Project and samples are not buildable in Java 17 due to Gradle 7 requirement and deprecation/removal of `compile` dependency syntax.

**To Reproduce**
Open project in environment running J17, and update `gradle-wrapper.properties` to a J17-supported version, e.g `7.3.2`

**Expected behavior**
The project to be usable in an up-to-date environment.

**Cause**
The `compile` instruction was deprecated in Gradle 6, per https://docs.gradle.org/current/userguide/upgrading_version_5.html

It was removed from Gradle 7, and 7.3 is required for Java 17.

**Solution**
Change all `compile` instructions in gradle dependancy lists to `implementation` (and all `testCompile` to `testImplementation`). There are a few other changes per the upgrade instructions, but I didn't see instances of them in the checked files. This change will not adverssely impact earlier-version users as it's to bring in line with Gradle 6 deprecation.

**Comment by jgrandja** [comment]
Thanks for the request @think-info.

FYI, this project depends on Spring Security 5.5, which compiles against JDK 1.8.

We do plan on upgrading to Gradle 7 soon.

**Comment by VonUniGE** [comment]
Upgrading to Gradle 7 is not yet possible because of the [spring-build-conventions](https://github.com/spring-gradle-plugins/spring-build-conventions) dependency. The development of this plugin seems to have stopped. Last commit is dated from 29 June 2021.

Should this plugin still be used ?

**Comment by jgrandja** [comment]
@VonUniGE We have a few changes that need to be made, including `spring-build-conventions`, before we can upgrade to Gradle 7. I've scheduled this for next release.
