### ISSUE TITLE
✨ feat: Ability to specify and go to a redirect url after successful logout

### ISSUE THREAD

**Issue by bjornharvold** [spring-projects/spring-authorization-server#574]
Based on Jeroen's answer in the linked ticket, I am now forwarding to the /logout url on Spring Auth Server instead. Once logged out successfully, is there any OAuth2 magic that will use the post_logout_redirect_uri angular-oauth2-oidc passes in as a request param?

Off topic: As I don't want to overwrite the /logout POST method, I am trying to find a hook in Spring Web MVC that lets the caller specify a redirect url. I'm guessing a filter could listen to /login?logout but wondering if there is a more standard way of doing redirects in OAuth.

🍺

**Comment by bjornharvold** [comment]
I think this needs an update. It is not a bug, it's a feature.

Based on Jeroen's answer in the linked ticket, I am now forwarding to the /logout url on Spring Auth Server instead. Once logged out successfully, is there any OAuth2 magic that will use the post_logout_redirect_uri angular-oauth2-oidc passes in as a request param? 

Off topic: As I don't want to overwrite the /logout POST method, I am trying to find a hook in Spring Web MVC that lets the caller specify a redirect url. I'm guessing a filter could listen to /login?logout but wondering if there is a more standard way of doing redirects in OAuth.

**Comment by jgrandja** [comment]
@bjornharvold Can you please update the main description comment and/or last comment as both are different. The main description refers to revoking a token and the last comment is logout. It's not clear what you are asking.

**Comment by bjornharvold** [comment]
✅

**Comment by jgrandja** [comment]
@bjornharvold Support for `post_logout_redirect_uri` will be added in gh-266 and gh-58.

For now, you can customize logout using Spring Security's `LogoutHandler` and/or `LogoutSuccessHandler`. See [Handling Logouts](https://docs.spring.io/spring-security/reference/servlet/authentication/logout.html).

I'll close this as a duplicate.
