### ISSUE TITLE
✨ feat: Tighter integration with Spring Social

### ISSUE THREAD

**Issue by bjornharvold** [spring-projects/spring-authorization-server#577]
**Expected Behavior**
I've just finished v1 of a fully functional SSO server with Spring Authorization Server. Love it! Thank you for this amazing framework. What I am looking at next is to have the SSO server be the hub for all my connected resource servers. What I'd like to do next, is add support for other ways the user can create an account via popular social platforms.

Flow:

1. User clicks on "Log in" on my Single Page Application
2. User is forwarded to my Spring Authorization Server "/login" page
3. User chooses to log in with FB
4. Go to FB domain
5. Authenticate with FB
6. Return to my SSO server with FB access token
7. Retrieve FB user info
8. Create user record on my SSO server
9. Put the authenticated user in SpringSecurityContext 

The next steps I am unclear about. I'd like to:
- Create a OAuth2Authorization entry based on the client-id the user came in on in step 1.
- Return to Single Page Application with access token from my SSO

Is that something that can be done today by me or would this be a feature that could go in Spring Authorization Server code base?

Thank you 🍻

**Comment by jgrandja** [comment]
@bjornharvold 

> I've just finished v1 of a fully functional SSO server with Spring Authorization Server. Love it!

Excellent ! We're so happy it's working out nicely for you.

Integration with an external Identity ("Social") Provider is a high priority item and we plan on working on a sample soon. This will be addressed in gh-106 and gh-538.

I'm going to close this as a duplicate but feel free to add comments in the existing issues. Thanks!
