### ISSUE TITLE
/userinfo endpoint always return code 401

### ISSUE THREAD

**Issue by c0ff75** [spring-projects/spring-authorization-server#583]
Hello,
I have an application that works successfully with the old version Spring Security OAuth server. Now I'm trying to use the new server variant with version 0.2.1. 

Unfortunately, there is probably some bug in the implementation of endpoint /userinfo, as JWT authorization is never successful.
I always get a 401 response. 

This happens because:
1. The method OAuth2AuthorizationServerConfiguration.applyDefaultSecurity() configures authentification for any request:

			.authorizeRequests(authorizeRequests ->
				authorizeRequests.anyRequest().authenticated()
			)

2. The OidcUserInfoEndpointFilter filter in the filter chain comes after the FilterSecurityInterceptor. Это задается в классе  OidcUserInfoEndpointConfigurer, string 103:

                       builder.addFilterAfter(postProcess(oidcUserInfoEndpointFilter), FilterSecurityInterceptor.class);

3. As a result, the OidcUserInfoEndpointFilter never runs. The execution of the filter chain is interrupted at the FilterSecurityInterceptor. It checks user authentication. And because the "authenticated" attribute was set in the OAuth2AuthorizationServerConfiguration.applyDefaultSecurity() configuration, the execution is aborted. An org.springframework.security.access.AccessDeniedException is thrown and the filter chain is aborted. The client receives a 401 code in response.

**Comment by sjohnr** [comment]
@c0ff75, please see [this comment](https://github.com/spring-projects/spring-authorization-server/issues/521#issuecomment-989769773). If you want to use the UserInfo endpoint, please enable resource server support in your configuration, as demonstrated in the `OidcUserInfoTests`.

I'm going to close this, as the UserInfo endpoint is working as designed.

**Comment by c0ff75** [comment]
@sjohnr - OidcUserInfoTests  - it doesn't contain tests that go through the actual chain of filters. Everything works there, because there are mocks :)

I foud workaround. I added to the application config:

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://hostname/oauth2/jwks
          issuer-uri: http://hostname/

and into 
public SecurityFilterChain authorizationServerSecurityFilterChain() :

http.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt)          
          
I suggest adding this to the documentation or examples

**Comment by sjohnr** [comment]
> @sjohnr - OidcUserInfoTests - it doesn't contain tests that go through the actual chain of filters. Everything works there, because there are mocks :)

Actually, `OidcUserInfoTests` contains integration tests that do exercise the filter chain.

> http.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt)
> 
> I suggest adding this to the documentation or examples

Will do. Thanks.
