### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: The class with com.example.authserver.config.DefaultSecurityConfig$1$1 and name of com.example.authserver.config.DefaultSecurityConfig$1$1 is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing

### ISSUE THREAD

**Issue by vjcool2408** [spring-projects/spring-authorization-server#586]
### Getting exception when creating the UserDetailsService Bean
**Caused by: java.lang.IllegalArgumentException: The class with com.example.authserver.config.DefaultSecurityConfig$1$1 and name of com.example.authserver.config.DefaultSecurityConfig$1$1 is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details**

       @Bean
	public UserDetailsService userDetailsService() {
		return new UserDetailsService() {
			
			@Override
			public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
				STREAM_USER_DETAILS userDetails = streamUserDetailsService.loadUserByUsername(username);
				if (Objects.nonNull(userDetails)) {
					Set<GrantedAuthority> authorities = userDetails.getAuthorities().stream()
							.map(ga -> new StreamGrantAuthority(ga.getAuthority())).collect(Collectors.toSet());

					return new UserDetails() {

						private static final long serialVersionUID = 1L;

						@Override
						public boolean isEnabled() {
							// TODO Auto-generated method stub
							return userDetails.isEnabled();
						}

						@Override
						public boolean isCredentialsNonExpired() {
							// TODO Auto-generated method stub
							return userDetails.isCredentialsNonExpired();
						}

						@Override
						public boolean isAccountNonLocked() {
							// TODO Auto-generated method stub
							return userDetails.isAccountNonLocked();
						}

						@Override
						public boolean isAccountNonExpired() {
							// TODO Auto-generated method stub
							return userDetails.isAccountNonExpired();
						}

						@Override
						public String getUsername() {
							// TODO Auto-generated method stub
							return userDetails.getUsername();
						}

						@Override
						public String getPassword() {
							// TODO Auto-generated method stub
							return userDetails.getPassword();
						}

						@Override
						public Collection<? extends GrantedAuthority> getAuthorities() {
							// TODO Auto-generated method stub
							return authorities;
						}
					};
				} else {
					throw new UsernameNotFoundException("username not found.");
				}
			}
		};
	}
`

**Comment by sjohnr** [comment]
@vjcool2408, thanks for getting in touch. The description of how to resolve this issue is already present in the error message you received. You need to provide Jackson annotations or a mixin for your custom `UserDetails` object in order to serialize it to JSON.

I'd encourage you to look at #499 and browse links to how-to guides for our upcoming reference documentation. If anything looks helpful, please up-vote those issues (or submit your own) as we are currently prioritizing which how-to guides we work on based on community feedback.

I'm going to close this, as the solution for your issue is already provided in the error, but please let me know if I misunderstood your issue, and we can re-open if necessary.
