### ISSUE TITLE
Support JWT Bearer Client Authentication

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#59]
This feature will deliver [Using JWTs for Client Authentication](https://datatracker.ietf.org/doc/html/rfc7523#section-2.2) defined in the JSON Web Token (JWT) Profile spec.

**Comment by rlewczuk** [comment]
I've implemented client authentication part of this specification. If there are no objections, I'm ready to issue PR as soon as 0.1.2 cycle starts. 

This implementation contains significant amount of duplicated code (PKCE related) that needs to be factored out, I'm aware of that and plan to take care of it.

Branch implementing this feature is here: https://github.com/rlewczuk/spring-authorization-server/tree/jwt-client-auth

**Comment by rlewczuk** [comment]
Here is another part of this epic - JWT assertion grant type: https://github.com/rlewczuk/spring-authorization-server/tree/jwt-assertion-grant

In both parts I had to make some design decisions that really need to be reviewed and discussed. Plus I have to review it once again for  compliance with RFC (especially error codes). If you have time some time next week, we can start working on this. Granted that design issues will be reviewed and fixed, its more-or-less complete and will be ready to land in master branch early in 0.1.2 (or even a bit earlier if we feel safe about it).

**Comment by jgrandja** [comment]
Thanks @rlewczuk !

Let's focus on JWT client authentication for `0.1.2`. I'm not sure when JWT authorization grant will get scheduled at this point.

I'm pretty backlogged over the next 2 weeks. After `0.1.1` is out, please submit PR for JWT client authentication. Thanks!

**Comment by larsw** [comment]
What's the status for this feature?

**Comment by jgrandja** [comment]
@larsw This is scheduled for `0.2.1` as indicated in the Milestone.
