### ISSUE TITLE
“authorities” claim not added to jwt by default

### ISSUE THREAD

**Issue by barneag** [spring-projects/spring-authorization-server#591]
Hello,
I'm implementing an oauth2 solution based on  Authorization Server 0.2.1, and noticed that “authorities” claim
not added to JWT by the authorization server by default.
i browsed to find a solution and found that need to configure a `OAuth2TokenCustomizer` bean, in order to add user’s “authorities” claim.

```
    @Bean
    OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer() {
        return new JwtCustomizer();
    }
```
this feels a bit like a workaround,and i wanted to verify that this solution is correct, and that the authorization server really doesn’t add the “authorities” claim by default and it is really required by us to implement the `OAuth2TokenCustomizer`
thanks!

**Comment by pxzxj** [comment]
you are correct,this is my implementation and it works.
```java
@Bean
public UserOAuth2TokenCustomizer userOAuth2TokenCustomizer() {
return new UserOAuth2TokenCustomizer();
}


private static class UserOAuth2TokenCustomizer implements OAuth2TokenCustomizer<JwtEncodingContext> {

@Override
public void customize(JwtEncodingContext jwtEncodingContext) {
	jwtEncodingContext.getClaims()
			.claim("authorities", jwtEncodingContext.getPrincipal()
					.getAuthorities()
					.stream()
					.map(Object::toString)
					.collect(Collectors.toList()));
    }
}
```

**Comment by sjohnr** [comment]
Hi @barneag. Thanks for your interest in the project.

I'm going to close this as [this question](https://stackoverflow.com/questions/70771027/authorities-claim-not-added-to-jwt-by-default/70777041) has been [answered](https://stackoverflow.com/a/70777041/15835039) on stackoverflow.
