### ISSUE TITLE
How-to: Configure your own user storage

### ISSUE THREAD

**Issue by andifalk** [spring-projects/spring-authorization-server#593]
Publish a guide on How-to: Customize the user storage

- How to use your own persistent user model (with additional attributes like _first name_, _last name_, address, etc.) instead of the core user model from spring security to make sense of the OIDC scopes like _profile_, _address_ or _phone_.

Related gh-499

**Comment by sjohnr** [comment]
Also related to gh-537

**Comment by jgrandja** [comment]
@andifalk 

> How to use your own persistent user model

The "How-to: Customize the OpenID Connect 1.0 UserInfo response" demonstrates how you can [use your own persistent user model](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-userinfo.html#customize-id-token). Is this sufficient to close this issue?

**Comment by jgrandja** [comment]
Great, thanks @andifalk
