### ISSUE TITLE
Spring 6 compatibility

### ISSUE THREAD

**Issue by Artur-** [spring-projects/spring-authorization-server#598]
**Expected Behavior**
This project should work with Spring 6

**Current Behavior**
The project uses Servlet < 5 with the `javax` namespace

**Context**
Spring 6 moved to Servlet 5 and Spring 6 M2 is already out. 
When trying to test out Spring Boot 3 snapshot + Spring 6 M2 I ran into the issue that the oauth server cannot be used.

**Comment by jgrandja** [comment]
@Artur- Spring Authorization Server currently builds against [Spring Security 5.5.3](https://github.com/spring-projects/spring-authorization-server/blob/main/gradle/dependency-management.gradle#L6). We plan to upgrade to Spring Security 5.6.0 in the 0.3.0 release (gh-594).

We will upgrade to Spring Security 6.0 after it is released, which is planned for later this year.
