### ISSUE TITLE
Implement OAuth 2.0 Token Exchange

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#60]
This feature will deliver [OAuth 2.0 Token Exchange](https://tools.ietf.org/html/rfc8693).

**Comment by oridool** [comment]
Hi,
Great work so far!! looks very promising 👍 

When is this Token Exchange planned for?

Or alternatively, any chance to add custom claims to JWT when using client_credentials flow? Claims that depends on my request (headers / scopes) ?
For example, if I send an HTTP header `x-my-custom-claim : value`, then I would like the token to be created with the claim `x-my-custom-claim` and the value `value`.

Thanks,
Ori.

**Comment by jgrandja** [comment]
Thanks @oridool !

Token Exchange will be delivered at a much later point. There are a few higher priority items ahead of it. You can always look at the ZenHub board (see [Feature Planning](https://github.com/spring-projects-experimental/spring-authorization-server#feature-planning) section for link) to see the features which are prioritized in the order of development.

The ability to add custom claims is coming up soon so stay tuned.

**Comment by amit-github-personal** [comment]
Hi @jgrandja, let me know whenever you want to work on this epic. I would love to raise a PR for this.

**Comment by jgrandja** [comment]
Thanks for your interest @amit-github-personal. The are a few higher priority features at the moment but will let you know when this one gets closer to scheduling for a release.

**Comment by lu-cheng** [comment]
This feature is very helpful for implementing stateless services and would love to see it progress.

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!

**Comment by pitagoras3** [comment]
Hello @jgrandja, at @allegro we're highly considering using `spring-authorization-server` as a core of our Authorization server, and _Token Exchange_ is a crucial grant type for us. Do you have any information on when implementation of this grant type is planned? We're open to help with open-source contributions from our side :)

**Comment by jgrandja** [comment]
@pitagoras3 Thank you for your interest in this project. We're releasing `1.2` Nov 21 and then will be planning `1.3`. We will consider adding this feature but I'm not sure at this point as we already have quite a bit of work planned for `1.3`. Please reach out again in Dec. Thanks.

**Comment by pitagoras3** [comment]
As we are in the middle of December and spring-authorization-server 1.2 was [released](https://github.com/spring-projects/spring-authorization-server/releases/tag/1.2.0), I am reaching out to @jgrandja with same question as above - _Do you have any information on when implementation of this grant type is planned?_

@bananich I'm trying to get the answer for the same question that you're asking :)

**Comment by jgrandja** [comment]
@pitagoras3 Please see [this comment](https://github.com/spring-projects/spring-security/issues/5199#issuecomment-1854426224) for an update.

**Comment by jgrandja** [comment]
Closing as duplicate of gh-1525
