### ISSUE TITLE
How-to: Migrate from spring-security-oauth2

### ISSUE THREAD

**Issue by Laures** [spring-projects/spring-authorization-server#614]
It would be great if we had a guide on how to migrate from spring-security-oauth2 with DB stored opaque tokens to this project. Preferably without loosing existing tokens or refresh tokens.

**Comment by jgrandja** [comment]
The [Spring Security OAuth](https://spring.io/projects/spring-security-oauth) project has reached EOL and therefore it doesn't make sense to allocate any efforts to this project. We need to focus our efforts with Spring Authorization Server and keep building out features and documentation.

Furthermore, Spring Authorization Server is a complete re-write of `spring-security-oauth` so the core classes and components are not a simple 1-1 mapping. The migration guide would take too much effort to write.

There have been quite a few projects (comments from the community) that have already migrated from the old `spring-security-oauth` to Spring Authorization Server so it is doable without a migration guide. The best place to start understanding how to migrate is by learning the [samples](https://github.com/spring-projects/spring-authorization-server/tree/main/samples).
