### ISSUE TITLE
Roles/Authorities not included in the JWT Token

### ISSUE THREAD

**Issue by bharaththippireddy** [spring-projects/spring-authorization-server#617]
**Describe the bug**

While configuring the Authorization server to use JWT the user authorities are not being included in the JWT Token

**To Reproduce**
Steps to reproduce the behavior.

Configure Authorization Server use JWT as below

	@Bean
	public JwtDecoder jwtDecoder(JWKSource<SecurityContext> jwkSource) {
		return OAuth2AuthorizationServerConfiguration.jwtDecoder(jwkSource);
	}

**Expected behavior**

The JWT Token Generated should have the roles/authorities returned by the UserDetailsService.

**Sample**

{
 x5t#S256: "ZLfQ5MvEEPU0hgdlce-F3LVPW98XsekvryW7cO6JTR0",
 kid: "jwtiscool",
 alg: "RS256"
}.
{
 sub: "john@ferguson.com",
 aud: "couponclientapp",
 nbf: 1643967633,
 scope: [
  "read"
 ],
authorities:[
"ROLE_ADMIN",
"ROLE_USER"
]
 iss: "http:\/\/localhost:8080",
 exp: 1643969433,
 iat: 1643967633
}.
[signature]

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by sjohnr** [comment]
@bharaththippireddy thanks for your interest in the project!

See [this comment](https://github.com/spring-projects/spring-authorization-server/issues/502#issuecomment-971731130), which I believe will instruct you how to include authorities in the access token.

I'm going to close this as answered.

**Comment by bharaththippireddy** [comment]
Thanks Steve.I have added a customizer to get the authorities into the
claim.Can you guide me with the below.The claim method on getClaims seems
to be deprecated.

context.getClaims().claim(*AUTHORITIES_CLAIM*, authorities);


Do we have to add a custom converter to get the authorities on the Resource
server as well when we use the below.

oauth2ResourceServer()


thanks again,

Bharath

**Comment by sjohnr** [comment]
@bharaththippireddy, the classes in package `org.springframework.security.oauth2.jwt` are deprecated and due to be replaced by the corresponding classes in spring security, so when you upgrade to 0.3.0 after release in a few months you'll just have minor refactoring (if any) to do. See gh-596.

I believe you will need to customize the resource server as well, yes.
