### ISSUE TITLE
how to : invalid access token and refresh token

### ISSUE THREAD

**Issue by zwjsexcalibur** [spring-projects/spring-authorization-server#618]
hi , I just want to know how to invalid access token and refresh token when any client logout. If the author can give some advices in the sample or document, I will feel very much indebted.In additon ,I think this is a very important function to improve the whole certification process.

**Comment by ctlove0523** [comment]
This class `OAuth2TokenRevocationEndpointConfigurer ` may be helpful

**Comment by kwanik-kor** [comment]
Sorry for replying on closed issue. But there were no documents on ref-doc branch. Is there any opened docs?

**Comment by sjohnr** [comment]
Documentation is the top priority for the 0.3.0 release, which is the week of May 23, 2022. So we'll be working on this soon!

**Comment by kwanik-kor** [comment]
@sjohnr Thanks for sharing schedule!
