### ISSUE TITLE
Support WebFlux

### ISSUE THREAD

**Issue by xindemeng** [spring-projects/spring-authorization-server#623]
Spring authorization server does not support WebFlux currently, will it support WebFlux in the future?

**Comment by luamas** [comment]
It is estimated that it will not be compatible with WebFlux until the version is stable.  For the time being, many interfaces need to be adjusted and all functions of OAuth2 need to be improved.

**Comment by xindemeng** [comment]
> It is estimated that it will not be compatible with WebFlux until the version is stable. For the time being, many interfaces need to be adjusted and all functions of OAuth2 need to be improved.

**Comment by jgrandja** [comment]
@xindemeng Closing as duplicate of gh-152. See [comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644)
