### ISSUE TITLE
Claim "aud" is filled with client-id, but should be list of allowed resource servers

### ISSUE THREAD

**Issue by kubav182** [spring-projects/spring-authorization-server#634]
I'm trying to migrate deprecated spring oauth server to this new one. I miss field "resource_servers" on registered client.

I would expect audience claim in JWT to be a list of allowed resource servers, but now it is filled with client-id.

According to [RFC 7519](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3):

The "aud" (audience) claim identifies the recipients that the JWT is intended for. Each principal intended to process the JWT MUST identify itself with a value in the audience claim. If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected. In the general case, the "aud" value is an array of case- sensitive strings, each containing a StringOrURI value. In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value. The interpretation of audience values is generally application specific. Use of this claim is OPTIONAL.

**Comment by jgrandja** [comment]
@kubav182

> I would expect audience claim in JWT to be a list of allowed resource servers, but now it is filled with client-id.

The client is the "intended" audience of the access token, since the authorization server mints the access token for use by the client.

To add additional audience(s) to `aud` claim, the application needs to customize the `Jwt`. This can be accomplished by registering a `@Bean` of type `OAuth2TokenCustomizer`.

Please see this 
[comment](https://github.com/spring-projects/spring-authorization-server/issues/502#issuecomment-971731130) for additional details.

**Comment by kubav182** [comment]
@jgrandja Thanks for your reply, I have already implemented as you mentioned via OAuth2TokenCustomizer. I'm ok with custom solution.

> The client is the "intended" audience of the access token, since the authorization server mints the access token for use by the client.

This has two conditions. The client == resource server && the client can call just only itself. I'm not sure if most of the real use cases fit this. Thats why i thought the lib should have better support for the audience claim as it is not the name of client, but the name of resource server the client wants to call and it is not the client id in really many cases (microservices, SPA, SSO).

**Comment by lojc** [comment]
@kubav182. Totally agree with you, I´m also trying to migrate to the newest spring versions and there´s no "easy" way to set the audience claims.

**Comment by kubav182** [comment]
@lojc there is snippet of code as example, its not hard, but would be better if library comply with the RFC and real use cases, this RFC and claim aud is misunderstood, maybe they're confusing it with client_id claim.


```
@Bean
 OAuth2TokenCustomizer<JwtEncodingContext> tokenCustomizer() {
        return context -> {
            Authentication principal = context.getPrincipal();
            if (OAuth2TokenType.ACCESS_TOKEN.equals(context.getTokenType())) {
                // check principal and set audience from config or db
                context.getClaims().audience(List.of("ms1", "ms2"));
            }
        };
 }
```

**Comment by jgrandja** [comment]
@kubav182 It depends on the flow (and associated parameters) that is performed that determines what goes into the `aud` claim.

> I would expect audience claim in JWT to be a list of allowed resource servers

That is true if the `resource` parameter is sent, which is part of the [Resource Indicators for OAuth 2.0](https://datatracker.ietf.org/doc/html/rfc8707) spec. However, this feature has not been implemented by Spring Authorization Server.

The `client_id` is a **sensible default** for the `aud` claim. If you need to override it then you can register a `OAuth2TokenCustomizer`, which is fairly easy.
