### ISSUE TITLE
When the redirect uri in the authorization request contains the encodeURI like '%3F' or '%26' (decode '?' ,'&') to concatenation parameter, the request fails.

### ISSUE THREAD

**Issue by yxgsg** [spring-projects/spring-authorization-server#636]
### the Bug

- **Sorry for my poor english.**
- **When the client request authorized login, it fails.**

### To Reproduce

- **The authorization request** :"_https://localhost:8080/oauth2/authorize?redirect_uri=https%3A%2F%2Fopen.bot.tmall.com%2Foauth%2Fcallback%3FskillId%3D86493%26token%3DMjIxMjE2MTIzOTc0NEFGRUhJTkZEVlE%3D&client_id=123&response_type=code&state=0.2484454384938234_", 

- **The backend print log display**: "o.s.security.web.FilterChainProxy        : Securing GET /error?redirect_uri=_https%3A%2F%2Fopen.bot.tmall.com%2Foauth%2Fcallback%3FskillId%3D86493%26token%3DMjIxMjE2MTIzOTc0NEFGRUhJTkZEVlE%3D&client_id=123&response_type=code&state=0.2484454384938234".

- **When I changed the authorization request address to('%3F' is replaced by '&', '%26' is replaced by '&')** :"_https://localhost:8080/oauth2/authorize?redirect_uri=https%3A%2F%2Fopen.bot.tmall.com%2Foauth%2Fcallback&skillId%3D86493&token%3DMjIxMjE2MTIzOTc0NEFGRUhJTkZEVlE%3D&client_id=123&response_type=code&state=0.2484454384938234_", 
-  **DecodeURI result, for easy reading**:"https://localhost:8080/oauth2/authorize?redirect_uri=https://open.bot.tmall.com/oauth/callback&skillId=86493&token=MjIxMjE2MTIzOTc0NEFGRUhJTkZEVlE=&client_id=123&response_type=code&state=0.2484454384938234"

- **The backend print** "s.w.a.DelegatingAuthenticationEntryPoint : Match found! Executing org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint@147e0734",**and** "Redirecting to https://localhost:8080/login"

- **But in the end, the authorization request client was prompted that the parameter was missing and failed.**

### Expected behavior

- **I swithed "spring-security-oauth2" framework and everything works fine with OAuth2.**

### Question

- **Please tell me what should I do?**
- **Thanks for you answer.**

**Comment by jgrandja** [comment]
@yxgsg I'm having a hard time following the issue you are having. Can you please create a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) or a test that reproduces the issue so I can better understand.

**Comment by yxgsg** [comment]
- **Hi, I uploaded the code to github at:** [auth-server-demo-master](https://github.com/yxgsg/auth-server-demo-master)

- **Thanks for your help**

**Comment by pxzxj** [comment]
@yxgsg you better upload the client project and resourceserver project too

**Comment by jgrandja** [comment]
@yxgsg The sample uploaded does not conform to a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) as it does not provide detailed steps to reproduce.

As well, the `redirect_uri` is `https://open.bot.tmall.com/oauth/callback`, which is an external platform that requires extra setup on my end.

Please provide a similar sample as the [default sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) and detailed steps to reproduce.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
