### ISSUE TITLE
Is there any plan to support JWT Bearer grant type defined in RFC7523

### ISSUE THREAD

**Issue by lys2356** [spring-projects/spring-authorization-server#637]
Thanks guys for developing such a great authorization server framework.

I had found this link for upcoming-features.
https://github.com/spring-projects/spring-authorization-server/wiki/Feature-List#upcoming-features
But no more detail plan could be found about JWT Bearer grant type.

Is there any link or doc for this feature plan?
Thanks

**Comment by jgrandja** [comment]
Thanks @lys2356 !

The ticket gh-546 addresses Jwt Bearer grant type, however, it's on hold as it's a lower priority feature at the moment. 

FYI, we typically prioritize features based on upvotes and at the moment there are no votes.
