### ISSUE TITLE
How-to: Dynamic client registration

### ISSUE THREAD

**Issue by arfatbk** [spring-projects/spring-authorization-server#647]
We should have a How-to guide on a dynamic client registration.
As in adding a client to the registered client repository (JDBC/any) at runtime.

**Comment by sjohnr** [comment]
@arfatbk take a look at gh-499. We have a rough outline that includes "OpenID Connect 1.0 Client Registration Endpoint". I think that section would touch on this topic. Can you explain what additional information you'd like to see in a "How-to" guide?

**Comment by arfatbk** [comment]
Thanks. That's it I guess.

**Comment by sjohnr** [comment]
Cool. I'll leave this open for now just in case there are other ideas. We can easily clean these issues up as we're working through the documentation effort, but I wanted to ask just to clarify.
