### ISSUE TITLE
Validate Principal

### ISSUE THREAD

**Issue by kwanik-kor** [spring-projects/spring-authorization-server#648]
**Describe the bug**
First of all, now I'm using 'custom consent example' to build my oauth2.0 server. I really appreciate your awesome project. 

The problem has occurred when authenticated principal has been expired or the user account has been deleted. When the `SecurityContextHolder` is still alive, authorization end point still throw me to consent page. But I think end point should throw me back to login page if principal is not actually valid. I've cleared up the `SecurityContextHolder` and could solve problem.

**Expected behavior**
How do you think about double check the principal on `OAuth2AuthorizationCodeRequestAuthenticationConverter`? I could solve the problem with under code.

Well I'm not quite good at 'Spring Security' so it can be a bad idea though...

**Sample**
```java
        Authentication principal = SecurityContextHolder.getContext().getAuthentication();
        if (principal == null) {
            principal = ANONYMOUS_AUTHENTICATION;
        } else {
            boolean exist = userService.fetchUserExistence(principal.getName());
            if(!exist) {
                SecurityContextHolder.getContext().setAuthentication(ANONYMOUS_AUTHENTICATION);
                principal = ANONYMOUS_AUTHENTICATION;
            }
        }
```

**Comment by jgrandja** [comment]
@kwanik-kor Regarding your comment:

> The problem has occurred when authenticated principal has been **expired** or the user account has been **deleted**. When the `SecurityContextHolder` is still alive...

Session management (expired) and User management (deleted) is not a responsibility of the framework and should instead be implemented/configured in Spring Security instead. Session management can be configured using `httpSecurity.sessionManagement()` and user management is dependent on where your user's are stored and the underlying identity provider being used, e.g. LDAP, SAML, custom user database, etc.

The only requirement for Spring Authorization Server to continue the Authorization flow is to ensure the current `Authentication.isAuthenticated` and not anonymous. The underlying authentication mechanism being used is responsible for clearing the session if the user has been deleted or if the session has expired.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
