### ISSUE TITLE
 Login page filter intercepts token based authorization server apis  

### ISSUE THREAD

**Issue by blabadi** [spring-projects/spring-authorization-server#664]
**Describe the bug**
In the Federated Identity sample and the way default security is setup it applies oauth2Login to all endpoints including /token /userinfo which should only be authenticated by an Oauth2 token interception.

**To Reproduce**
run the Federated identity sample and try to obtain token using client credentials grant, you get the login page instead of going through.

**Expected behavior**
oauth2login shouldn't intercept authserver/oidc server endpoints that should only be authorized by token / basic authentication
the Oauth2AuthorizationServerConfigurer default security prevents an easy way to achieve and applies the oauth2login to all the server endpoints 

if this by design, at least the FederatedIdentityConfigurer can be updated to handle this to avoid confusion

**Sample**
run the Federated identity sample in this repository, and try to obtain token using client credentials grant, you get the login page instead of going through.
```
POST /oauth2/token HTTP/1.1
Host: localhost:9000
Authorization: Basic ...
Content-Type: application/x-www-form-urlencoded
Content-Length: 50

client_secret=...&grant_type=client_credentials
```

**Comment by sjohnr** [comment]
Thanks @blabadi, I must have missed testing this scenario. The main reason the configurer is applied to both filter chains is for the `AuthenticationEntryPoint`. I'll see what can be done to clean it up a bit and fix the issue!

**Comment by blabadi** [comment]
@sjohnr I've tried this again today and couldn't reproduce it again, I apologize I've must have done something wrong first time. will close the ticket

**Comment by blabadi** [comment]
just one thing to point out for folks who may be looking at this for /userinfo in the federated example, you will need to add resource server to the authorization server filter chain (#521)

```
  @Bean
  @Order(Ordered.HIGHEST_PRECEDENCE)
  public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
    OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);
    http
        // https://github.com/spring-projects/spring-authorization-server/issues/521
        .oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt)
        .apply(new FederatedIdentityConfigurer());
    return http.formLogin(Customizer.withDefaults()).build();
  }
```

**Comment by sjohnr** [comment]
Ok @blabadi, thanks for letting me know.
