### ISSUE TITLE
Provide integrations with Spring Boot

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-authorization-server#673]
We should provide the following integrations with Spring Boot:

- [x] Design Custom Properties and specify YAML
- [x] Implement auto-configuration classes
- [x] Implement starter -> `spring-boot-starter-oauth2-authorization-server`
- [x] Add to [Spring Initializr](https://start.spring.io/)

**Comment by vkadam** [comment]
Hello, any update on this ticket? Looking for its  future status? 
Thanks for awesome work you all are doing 🙏🙏

**Comment by sjohnr** [comment]
You're quite welcome, @vkadam! This ticket is on hold pending the 1.0 release, and we will be right back to it afterwards. We'll provide an update when we get closer to picking it back up.

**Comment by vkadam** [comment]
Appreciate the response @sjohnr. Looking forward to future release.

**Comment by sjohnr** [comment]
I have opened spring-projects/spring-boot#34003 to get the party started!
