### ISSUE TITLE
oauth2 errors was not obvious

### ISSUE THREAD

**Issue by FileNotFoundExcetion** [spring-projects/spring-authorization-server#677]
when authorization-server receive  a request like oauth2/authorize or response=code?redirect_url=xxx. but unfortunately went something wrong with the request ,and we haven't seen some logs in some place .just receive a respone code 400 given us.and this is very difficult for us to resolve why receive a 400 code for us .and there is no exception in logs give us some hints

**Comment by FileNotFoundExcetion** [comment]
i think should add some debug logs in these important filters.

**Comment by sjohnr** [comment]
Thanks @FileNotFoundExcetion. Sorry about the difficulty in troubleshooting. I believe this is a duplicate of gh-159, so I am going to close this in favor of that issue.
