### ISSUE TITLE
Jdbc token store

### ISSUE THREAD

**Issue by alimorsel** [spring-projects/spring-authorization-server#683]
is there a way to store tokens in the database instead of storing them in the memory, so that when the auth server gets restarted no need for authorization again? thanks

**Comment by zxiaozhou** [comment]
@alimorsel use  JdbcOAuth2AuthorizationService

**Comment by sjohnr** [comment]
Hi @alimorsel, thanks for your interest in the project!

As @zxiaozhou pointed out, our default sample does demonstrate how to use the Jdbc implementation of each of the core interfaces. I'm going to close this as answered.
