### ISSUE TITLE
OpenID Provider Configuration endpoint should include the revocation token endpoint

### ISSUE THREAD

**Issue by mogTheDev** [spring-projects/spring-authorization-server#687]
**Expected Behavior**
The OpenID Connect Discovery endpoint should provide the revocation token endpoint.
i.e. adding this:
"revocation_endpoint": "http://{host_issuer}:{port_issuer}/oauth2/revoke"

**Current Behavior**
The current response for /.well-known/openid-configuration does not contain the endpoint revocation.

**Context**
Some angular lib such as angular-auth-oidc-client expect the revocation endpoint to be in the response when requesting the OpenID Connect Discovery endpoint.

**Comment by jgrandja** [comment]
Thanks for the report @mogTheDev. We'll look at adding this soon.
