### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-authorization-server#694]
We should use a Java 11 baseline for the 0.3.0 release.

**Comment by zhenchuan9r** [comment]
Would JRE-8 compatible versions be release after 0.3.0?

**Comment by sjohnr** [comment]
Hi @zhenchuan9r. I don’t believe so, but as far as I’m aware we haven’t yet used any Java 11 features so you’re welcome to fork the project and build the artifact yourself with jdk8.

**Comment by herodotus-cloud** [comment]
I just upgraded SAS from 0.2.3 to 0.3.0 today。Using SAS 0.3.0 under JDK 8 will cause compilation errors。It will prompt that the class file has the wrong version 55.0, which should be 52.0

**Comment by sjohnr** [comment]
> What is the reason for upgrading to java11? The currently used spring versions all support java8.
> 
> I think that the current version should support java 8, and then directly upgrade to java 17 when using spring 6

This is a good point. For my part, it wasn't intentional to deviate, I was mostly focused on the `buildSrc` directory of the Spring Security build which was using Java 11 and opted to apply that to the project with the 0.3.0 release. We can discuss this and come back with an answer.

**Comment by brunomendola** [comment]
Hi! I agree that this project should comply with the system requirements of the stable version of Spring Boot.

Thank you

**Comment by lltx** [comment]
I agree with @Hccake  @brunomendola ， It should be consistent with the spring boot ecology


<img width="626" alt="image" src="https://user-images.githubusercontent.com/50090230/171528299-918cee07-ad18-4eb4-8d7e-1946f37d1db1.png">

**Comment by sjohnr** [comment]
Thank you for your feedback everyone. I apologize for the inconvenience. I have opened gh-761 to address it! We will look to be as consistent with the rest of the Spring ecosystem as possible for future releases.
