### ISSUE TITLE
Allow ability to customize RegisteredClient during registration

### ISSUE THREAD

**Issue by rratliff** [spring-projects/spring-authorization-server#696]
**Expected Behavior**

The OIDC registration API calls the `RegisteredClientRepository` save method with a RegisteredClient object. I'd like the ability to have any custom claims on the registration request be propagated here.

**Current Behavior**
The `OidcClientRegistration` object contains all the claims (including custom claims) in the registration request, but these claims are dropped when the auth provider creates the `RegisteredClient` object to pass to the repository.

**Context**

The use case would be adding an extra claim during registration and then being able to access it later in the OAuth2TokenCustomizer as part of the `JwtEncodingContext`

**Comment by jgrandja** [comment]
@rratliff 

> I'd like the ability to have any custom claims on the registration request be propagated here

Can you provide more details on the custom claims you need propagated to the `RegisteredClient`?

Please provide the exact use case so I can better understand.

**Comment by rratliff** [comment]
I'm replacing a spring-security-oauth2 implementation. We had written our own register API and had a "subject" claim, which we later populated in the `sub` claim in the OAuth token. So the use case would be to capture the `subject` claim from the registration request so that it can be stored and later used during the token customization.

(I realize that this may be a slight deviation from OAuth standard in that `sub` means something specific in the token and probably should not be customizable.)

**Comment by jgrandja** [comment]
@rratliff 

> So the use case would be to capture the `subject` claim from the registration request so that it can be stored and later used during the token customization

If we provided an extension point, where would you store the `subject` claim for later use?

**Comment by jgrandja** [comment]
Thanks for the details @rratliff. We'll look at improving the customization / extension points soon.

**Comment by Kehrlann** [comment]
I can pick this one up.

**Comment by jgrandja** [comment]
@rratliff

If we provided [OidcClientRegistrationAuthenticationProvider.setRegisteredClientConverter(Converter<OidcClientRegistration, RegisteredClient>)](https://github.com/spring-projects/spring-authorization-server/blob/0.4.x/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/OidcClientRegistrationAuthenticationProvider.java#L87), would this work for your use case?

**Comment by rratliff** [comment]
Yes, that would work. Alternately it could be a constructor parameter. But a setter method would work as well.

**Comment by jgrandja** [comment]
@rratliff This is now resolved via 6dc3944.
