### ISSUE TITLE
There is a bug in the JPA usage guide code provided

### ISSUE THREAD

**Issue by bit-star** [spring-projects/spring-authorization-server#697]
**Describe the bug**

When converting objects, scopes are lost, resulting in the failure of the oidc client to obtain user information

Code location：docs/modules/guides/examples[JpaOAuth2AuthorizationService.toObject()] 

**To Reproduce**

Directly use the given JPA integration code to integrate the client oidc. After successful authentication, insufficient appears when obtaining user information_ Scope error

**Expected behavior**

if (entity.getAccessTokenValue() != null) {
	OAuth2AccessToken accessToken = new OAuth2AccessToken(
			OAuth2AccessToken.TokenType.BEARER,
			entity.getAccessTokenValue(),
			entity.getAccessTokenIssuedAt(),
			entity.getAccessTokenExpiresAt(),
              **_### Sets.newHashSet(entity.getAccessTokenScopes().split(","))_**);
	builder.token(accessToken, metadata -> metadata.putAll(parseMap(entity.getAccessTokenMetadata())));
}

**Comment by sjohnr** [comment]
Thanks @bit-star! If I get some time, I'll have to enhance the tests a bit to catch issues like that. For now, I pushed a fix so you can try it out.
