### ISSUE TITLE
Federated OAuth2 (enhancement proposal)

### ISSUE THREAD

**Issue by bob-walters** [spring-projects/spring-authorization-server#700]
**Expected Behavior**

The 0.2.3 release added support for federated authentication, but one deficiency in that solution is that the upstream access_token is discarded and cannot be conveyed in the final token response (JWT) even via the use of an AccessTokenCustomizer.  Only the idtoken attributes transfer through to the idtoken issued by the spring-authorization-server.  This has the downside that if the application actually needs the access_token to use the upstream resources, it is not available.

There are no standards that regards how an upstream token would be conveyed, so no standard behavior is proposed.  The proposal is that this be made possible, but still left up to an individual implementation to determine how the retained token is represented in the server's token response by using a AccessTokenCustomizer.

In the federated identity example, when the authorization endpoint is called for a federated IDP, it acquires the access and refresh tokens via reuse of the oauth2 client functionality in spring security, and uses the idtoken details acquired to create an OidcUser.  The upstream tokens are then discarded and the logic issues an authorization code, saving that authorization in the repo for the subsequent token call.   The token call does invoke a token customizer and response customizer, but by that time, the original access_token and refresh_token have been lost.  The proposal is that they are retained as attributes of the authorization saved with the authorization_code for subsequent use by the token endpoint.

This forked branch shows an example of this:
Branch: https://github.com/accesso/spring-authorization-server/pull/new/CORE-2422-contrib1
PR: https://github.com/spring-projects/spring-authorization-server/pull/701
(If the design of this looks good, let me know and I can add tests..)

An addition to the OAuth2AuthorizationCodeRequestAuthenticationProvider would detect if the source of Authentication at that point was an OAuth2AuthenticationToken instead of the normal UserPasswordAuthentication, and if so, save the Oauth tokens that have been acquired as part of the persistent Authorization object.

Note: Current proposed addition is not ideal in that it requires that the oauth2-client be a dependency, and
this is adding awareness of federation to the core handling of the provider.  Perhaps a visitor that can be injected
to add to the content of the saved Authorization object, based on the request?   That would be possible given
the current code?

**Current Behavior**

Currently the access_token and refresh_token acquired via the the use of the oauth2 client library by redirecting
to the standard client idp endpoint (to engage the client library behavior), and it in turn redirects back to the spring-auth-server's
authorization endpoint via browsr redirect once a security context has been established.  Upon redirecting back to the 
OAuth2AuthorizationCodeRequestProvider, the principal that is passed in to the authenticationAuthorizationRequest() method
(on the authentication object) will actually be OAuth2AuthorizedClient, and that method can use a

**Context**

The only justification for this request is that we have use cases where we really need to do federated OAuth2 rather than just federated OIDC.  I.e. the access_token needs to be retained.  The existing federated identity sample has code for both OIDC and OAuth2 (e.g. in the success handler) implying it was intended to support both, but the loss of the access_token in federated OAuth2 makes that scenario incomplete.  In our use cases we often do federated OAuth2 with the idtoken scope included so that we are authenticating and also acquiring an access_token for subsequent API calls an external resource server that is associated with the upstream services.

**Comment by sjohnr** [comment]
Hi @bob-walters, thanks for your interest and suggestion!

I didn't add this concept to the federated identity sample, because the id_token customization is all that was necessary and I don't think we had a use case that was simple to demonstrate that required what you're describing. But you're quite right that there's a gap in what we're demonstrating, and I'm open to suggestions for how we can improve that!

In the meantime however, you can actually access everything in the current sample without framework changes. You can start by autowiring the `OAuth2AuthorizationService` from Spring Security:

```java
@Bean
public OAuth2TokenCustomizer<JwtEncodingContext> idTokenCustomizer(OAuth2AuthorizedClientService authorizedClientService) {
	return new FederatedIdentityIdTokenCustomizer(authorizedClientService);
}
```

and add a constructor to the existing token customizer:

```java
private final OAuth2AuthorizedClientService authorizedClientService;

public FederatedIdentityIdTokenCustomizer(OAuth2AuthorizedClientService authorizedClientService) {
	this.authorizedClientService = authorizedClientService;
}
```

and finally obtain the access token in the `customize` method:

```java
OAuth2AuthenticationToken principal = context.getPrincipal();
OAuth2AuthorizedClient authorizedClient =
	this.authorizedClientService.loadAuthorizedClient(
		principal.getAuthorizedClientRegistrationId(),
		principal.getName());
OAuth2AccessToken accessToken = authorizedClient.getAccessToken();			
```

Note that I haven't had time to look at your branch yet (but will do so next week). I'd be curious if you were aware of this approach and whether it helps you.

**Comment by bob-walters** [comment]
Steve, thank you!   I had tried something close to what you suggested.   There may be one problem with what you're suggesting, but otherwise that should work.  The only problem I can see is that if you have a typical farm of servers where you are not guaranteed that the /authorization and /token calls will both be received by the same server, the call to loadAuthorizedClient() can come back with nothing.   If I've overlooked the fact that in a real service, that would be backed by a persistent store, then I'm wrong about this.    This point was the reason why (in the branch I offered) I made a point of saving the OAuth2AuthorizedClient in the Authorization that is saved with the issued authorization_code.  It was so that the /token endpoint would later have a guaranteed ability to retrieve it.  But that was only reason why I thought it had to be done in that way.  (And incidentally, I do dislike my branch because of that and because it forces a dependency on the spring-oauth-client library in the spring-authorization-server's module.)

**Comment by sjohnr** [comment]
You’re quite welcome, @bob-walters! Actually, you’re suspicion is correct regarding a persistent store. It isn’t generally a good practice to use an in memory store in production, but it won’t work at all in cases where you’re clustering and providing high availability. So once you back the service with a database it won’t be a problem any longer, and you should be good to go!

I’ll go ahead and close this for now, as I think we’ve hit on a working solution. If you have any other thoughts feel free to add more comments to this issue. Thanks for the feedback and quick response!

**Comment by bob-walters** [comment]
I just saw the piece that I was missing: the JdbcOAuth2AuthorizedClientService could be used instead of the InMemory variation to persist the client authorization info between the authorization and token calls.  I had overlooked the existence of that, and see what you mean now.  Thanks again - I'll switch my approach to use what you've suggested.

**Comment by Waylon-Firework** [comment]
Hi @bob-walters. I have read the issue But I haven't found any valid code. Is the reason why this ticket was closed because we don't plan to support the feature?

**Comment by Waylon-Firework** [comment]
Oh, there is a solution. Thank you @bob-walters @sjohnr .

<img width="1083" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/95599645/22b8017a-2408-4483-b8f8-2526e5ef4269">
