### ISSUE TITLE
Feature Request: ability to add AuthenticationConverters as well as providers via TokenEndpointConfigurer

### ISSUE THREAD

**Issue by bob-walters** [spring-projects/spring-authorization-server#702]
**Expected Behavior**

The spring-authorization-server could permit the containing application to extend the OAuth2 grant_types
that can be supported in accordance with the standard.  (Examples: device-based authentication, token exchanges, etc.)

It almost does this already: The OAuth2TokenEndpoint configurer permits custom authentication providers to be added
via its authenticationProvider() method.  However, the set of AuthenticationConverters which end up associated
with the token endpoint is currently hard-coded in the OAuth2TokenEndpointFilter and can't be set via the use
of the Con figurers.  A simple addition makes it possible to set that as well

A branch/PR which provides one way to overcome this is at:
Branch: https://github.com/accesso/spring-authorization-server/tree/CORE-2422-contrib2
PR: https://github.com/spring-projects/spring-authorization-server/pull/703

(if PR design looks good, let me know and I'll flesh it out / add tests.)

**Current Behavior**
Currently it isn't possible to set the list of AuthenticationConverters which are used with the OAuth2TokenEndpointFilter.
(A fixed list is embedded in the constructor.)

**Context**
With out some change to the core spring-authorization-server module, it is not possible to inject new AuthorizationConverters which interferes with the ability to add providers for new grant_types.

**Comment by jgrandja** [comment]
@bob-walters We're tracking this feature enhancement in gh-417. The ticket is assigned and is scheduled for `0.3.1`.

Just as an FYI, it's always best to reach out first (before creating a PR) to see if the feature request would be accepted or if the work is assigned / started. This way you won't waste any of your time.

I'm going to close this as a duplicate and will close the PR.

**Comment by bob-walters** [comment]
No problem, I hadn't noticed gh-417, and will adhere to your request to reach out first.
