### ISSUE TITLE
Dynamic Client Creation Sample

### ISSUE THREAD

**Issue by dilipdhankecha07** [spring-projects/spring-authorization-server#705]
How to use spring authorization server for dynamic client registration ?

**Comment by jgrandja** [comment]
@dilipdhankecha07 This will be documented in gh-672. Closing this as duplicate.

In the meantime, see the integration tests in [OidcClientRegistrationTests](https://github.com/spring-projects/spring-authorization-server/blob/f1a01597d9584e9887ddad322fa9bce768fcb927/oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OidcClientRegistrationTests.java#L102) for usage.
