### ISSUE TITLE
issue new refresh token every call to refresh access token

### ISSUE THREAD

**Issue by barneag** [spring-projects/spring-authorization-server#712]
Today Refresh token has a fixed time of expiration by default.
It would be nice to create mechanism for new expiration for refresh token,
every time we refresh access token.
thanks!

**Comment by sjohnr** [comment]
Hi @barneag, thanks for reaching out!

Have you seen `TokenSettings.Builder.reuseRefreshTokens(boolean)` and `TokenSettings.Builder.refreshTokenTimeToLive(Duration)`? With these two settings, you can specify a rotating refresh token that obtains a fresh expiration time of your choosing upon each use.

I believe it would not be best practice to simply extend the existing refresh token's lifetime (though again you can set a long lifetime if needed). See gh-297 for an example, which summarizes best practices for SPAs and the use of refresh tokens.

Do you have any additional thoughts on this?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by barneag** [comment]
Hey @sjohnr 
Thanks for the answer! just noticed thanks to you that we have the option to reuse the refresh token!
We will consider the 2 options, thanks again!
