### ISSUE TITLE
Add a sample for the jwt bearer authorization grant type

### ISSUE THREAD

**Issue by Shryne** [spring-projects/spring-authorization-server#746]
**Expected Behavior**
The project should state how to use the jwt bearer authorization grant type.

**Current Behavior**
Even though the `RegisteredClient` offers `JWT_BEARER` for `authorizationGrantType(...)`, there is no documentation or example how to actually implement this.

**Context**
I have tried to add a `OAuth2TokenCustomizer``, to manipulate the `OAuth2AuthorizationService` and to generate a custom token using the token generator (which won't work because half of the classes necessary for this are package private). 
The request to test wether something actually happened, was this:
```
POST /oauth2/token

headers:
assertion: ey...
scope: openid
grant_type: urn:ietf:params:oauth:grant-type:jwt-bearer
```
This will always lead to 401. 

A sample or some documentation would be nice.

**Comment by Shryne** [comment]
Here is some progress: 
First, the registered client needs some settings:
```kotlin
  @Bean
  fun registeredClient(): RegisteredClient =
      RegisteredClient.withId(UUID.randomUUID().toString())
          .clientId("clientId")
          .clientSecret("{noop}clientSecret")
          .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
          .clientAuthenticationMethod(ClientAuthenticationMethod.PRIVATE_KEY_JWT)
          .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
          .authorizationGrantType(AuthorizationGrantType.JWT_BEARER)
          .redirectUri("some url..."
          .scope(OidcScopes.OPENID)
          .clientSettings(
              ClientSettings
                  .builder()
                  .requireAuthorizationConsent(true)
                  .jwkSetUrl("jwk url...")
                  .tokenEndpointAuthenticationSigningAlgorithm(
                        SignatureAlgorithm.RS256 // or some other algorithm...
                  )
                  .build()
          )
          .build()
```
A client then needs to post on `/oauth2/token` with the following query parameters:
- `client_assertion_type`: The value for this query must be `urn:ietf:params:oauth:client-assertion-type:jwt-bearer`
- `client_assertion`: Contains the token to authenticate with
- `client_id`

The authentication happens in `JwtClientAssertionAuthenticationProvider`. It creates a JWT decoder and adds these custom validators to it:
```java
private static OAuth2TokenValidator<Jwt> createJwtValidator(RegisteredClient registeredClient) {
	String clientId = registeredClient.getClientId();
	return new DelegatingOAuth2TokenValidator<>(
			new JwtClaimValidator<>(JwtClaimNames.ISS, clientId::equals),
			new JwtClaimValidator<>(JwtClaimNames.SUB, clientId::equals),
			new JwtClaimValidator<>(JwtClaimNames.AUD, containsProviderAudience()),
			new JwtClaimValidator<>(JwtClaimNames.EXP, Objects::nonNull),
			new JwtTimestampValidator()
	);
}
```
Unfortunately, this stuff is hardcoded. It's impossible, to switch the validators or the decoder and for some reason, the validators insist on `issuer == sub == clientId`. This is very unfortunate, because my `jwtSetUrl` points to an external provider and tokens from that provider don't have the same issuer as the subject. Additionally, I have no idea, why the clientId must also be equal to these values.

I would like to have these validators removed. Alternatively, #643 would be fine.

**Comment by jgrandja** [comment]
@Shryne JWT Authorization Grant has not been implemented as of yet. It's been logged under gh-546. A sample and/or test  will be provided when the feature is implemented. Closing this as duplicate.
