### ISSUE TITLE
Support actuator metrics for /oauth2/** endpoints

### ISSUE THREAD

**Issue by vladimir-cirkovic** [spring-projects/spring-authorization-server#748]
**Expected Behavior**
oauth2 library exposes metrics like response time for /oauth/token /oauth/authorize and /oauth/check_token

**Current Behavior**
no metrics for those endpoints present on /actuator/prometheus out of the box

**Context**
It's nice to have, and also allow developers to see insides of each endpoint.

**Comment by jgrandja** [comment]
Thanks for the request @vladimir-cirkovic. I added an item in gh-673. Closing this as a duplicate.
