### ISSUE TITLE
spring-authorization-server sample error

### ISSUE THREAD

**Issue by azui007** [spring-projects/spring-authorization-server#758]
**Describe the bug**
Application run failed
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer

**To Reproduce**
I made an Sample of imitating the [default-authorizationserver.](https://github.com/spring-projects/spring-authorization-server/tree/main/samples/default-authorizationserver)
environment： JDK11
1，clone [Sample.](https://github.com/azui007/Authorization-Server-Demo.git)
2，run OauthApplication

**Expected behavior**
can start normally

**Sample**
 [Sample.](https://github.com/azui007/Authorization-Server-Demo.git)
![image](https://user-images.githubusercontent.com/9415011/170424147-c9b9326e-1487-4821-949c-7a099f049307.png)

**Comment by sjohnr** [comment]
Hi @azui007, welcome to the project!

Thank you for the sample! I reviewed it, and it looks as though you're importing `spring-webflux` and intending to build a reactive application. Spring Authorization Server does not support webflux, so you'll need to adjust your dependencies.

To get the default sample working in your own repository, you'll need to have the same dependencies as those listed in the default sample's [build.gradle](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/default-authorizationserver/samples-default-authorizationserver.gradle) file.

I'm going to close this issue as answered, but if you are still having trouble once you've adjusted the dependencies of your sample, feel free to add additional comments and I'll be happy to help.

**Comment by azui007** [comment]
> Hi @sjohnr 
it work for me 
thank you!
