### ISSUE TITLE
How to implement a custom authorization page？

### ISSUE THREAD

**Issue by dangcom123** [spring-projects/spring-authorization-server#772]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by sjohnr** [comment]
@dangcom123 thanks for your interest in the project!

Please add more details to your request, as it is not obvious to me what you're looking for with this title alone. Also, please clarify if you're requesting a new [how-to guide](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/how-to.html) or simply asking a question.

**Comment by dangcom123** [comment]
Hello, I want to customize the authorization page when using the authorization code mode. I trace the source code and find that the authorization page is spliced with strings in the OAuth2AuthorizationEndpointFilter and sent to the page through the response. How can I customize the authorization content?

**Comment by sjohnr** [comment]
Thanks @dangcom123. It sounds like you are looking to customize the authorization consent page.

You can configure a redirect to a custom consent page. You can view the [custom consent sample](https://github.com/spring-projects/spring-authorization-server/tree/main/samples/custom-consent-authorizationserver) which includes a full example as well as the [docs](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oauth2-authorization-endpoint).

I'm going to close this as answered but if you have more advanced requirements, you may consider adding a comment to gh-740.
