### ISSUE TITLE
Allow deletion of registered client at RegisteredClientRepository

### ISSUE THREAD

**Issue by gnom7** [spring-projects/spring-authorization-server#777]

**Comment by gnom7** [comment]
@jgrandja the use case is straightforward - we need an interface to delete registered clients to not rely on implementation (in-memory / jdbc / etc) and its details, please let me know if / what additional details are needed

**Comment by jgrandja** [comment]
The framework does not require `RegisteredClientRepository.delete()` so this would not be added. You can easily provide your own implementation that extends `RegisteredClientRepository` providing `delete()`. See the [reference documentation](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#registered-client-repository) on how to register your custom `RegisteredClientRepository`.
