### ISSUE TITLE
ClientSecretAuthenticationProvider does not check for expired client credentials and grants authentication

### ISSUE THREAD

**Issue by gnom7** [spring-projects/spring-authorization-server#778]

**Comment by jgrandja** [comment]
@gnom7 Closing this issue as invalid. Please log a new issue with details and if you feel this is a bug then please provide a test that reproduces the issue.

**Comment by jgrandja** [comment]
@gnom7 `RegisteredClient.clientSecretExpiresAt` was provided for custom implementations to make use of it if required. However, the framework does not use it at the moment so this would be a feature enhancement. Feel free to log a new issue as a feature enhancement, however, this will likely be lower on the priority as we have a few other tasks that we're planning for upcoming releases.
