### ISSUE TITLE
allow refresh_token types thru org.springframework.security.oauth2.server.authorization.token.JwtGenerator

### ISSUE THREAD

**Issue by andre-fxcm** [spring-projects/spring-authorization-server#783]
I'd like to do something like the following to customize refresh_tokens as JWT and leverage JwtGenerator to do it
```java
@Slf4j
@RequiredArgsConstructor
public class RefreshTokenGenerator implements OAuth2TokenGenerator<OAuth2RefreshToken> {
    private final JwtGenerator jwtGenerator;

    @Override
    public OAuth2RefreshToken generate(OAuth2TokenContext context) {
        Jwt encode = jwtGenerator.generate(context);
        return new OAuth2RefreshToken(encode.getTokenValue(), encode.getIssuedAt());
    }
}
```

But JwtGenerator doesnt allow "refresh_token" types thru its generate method. Any chance we can allow this possibility?
https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/token/JwtGenerator.java#L74-L82

**Comment by andre-fxcm** [comment]
possible solution
```java
@Slf4j
@RequiredArgsConstructor
public class RefreshTokenGenerator implements OAuth2TokenGenerator<OAuth2RefreshToken> {
    private final JwtGenerator jwtGenerator;

    @Override
    public OAuth2RefreshToken generate(OAuth2TokenContext context) {
        Jwt encode = jwtGenerator.buildJwt(context);
        return new OAuth2RefreshToken(encode.getTokenValue(), encode.getIssuedAt());
    }
}
```
https://github.com/spring-projects/spring-authorization-server/pull/784

**Comment by jgrandja** [comment]
@andre-fxcm Refresh tokens are typically opaque. Why do you need refresh tokens in Jwt format?

FYI, you can provide your own custom `OAuth2TokenGenerator<OAuth2RefreshToken>` that uses `JwtEncoder` instead of `JwtGenerator`. See [reference documentation](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-token-generator) on how to configure.

**Comment by andre-fxcm** [comment]
@jgrandja Hi, thanks for the feedback. 
I have use case as follows for jwt on the refresh_token:

When a user authenticates successfully, an operation happens on my side and that unique generated value is persisted as a claim into the refresh token.

Every time a new access token is created from that refresh token, that claim should statelessly transfer to the access token

Every time a new refresh token is generated from an existing refresh token, that claim should statelessly transfer to the new refresh token

That claim is valid until the refresh token is invalidated or expired, forcing authentication to happen again and a new unique generated value would be generated as a claim.

**Comment by jgrandja** [comment]
@andre-fxcm Thanks for providing your use case. This is non-standard behaviour and should be implemented as custom behaviour in the consuming application. Furthermore, the framework does not support self-contained (Jwt) refresh tokens at the moment and I'm not anticipating this support is needed. However, you can implement a custom `OAuth2TokenGenerator<OAuth2RefreshToken>` that generates a `Jwt` as the token value, as follows:

```java
public final class JwtRefreshTokenGenerator implements OAuth2TokenGenerator<OAuth2RefreshToken> {
	private final JwtEncoder jwtEncoder;
	private OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer;

	public JwtRefreshTokenGenerator(JwtEncoder jwtEncoder) {
		Assert.notNull(jwtEncoder, "jwtEncoder cannot be null");
		this.jwtEncoder = jwtEncoder;
	}

	@Nullable
	@Override
	public OAuth2RefreshToken generate(OAuth2TokenContext context) {
		if (context.getTokenType() == null ||
				!OAuth2TokenType.REFRESH_TOKEN.equals(context.getTokenType())) {
			return null;
		}

		String issuer = null;
		if (context.getProviderContext() != null) {
			issuer = context.getProviderContext().getIssuer();
		}
		RegisteredClient registeredClient = context.getRegisteredClient();

		Instant issuedAt = Instant.now();
		Instant expiresAt = issuedAt.plus(context.getRegisteredClient().getTokenSettings().getRefreshTokenTimeToLive());
		
		// @formatter:off
		JwtClaimsSet.Builder claimsBuilder = JwtClaimsSet.builder();
		if (StringUtils.hasText(issuer)) {
			claimsBuilder.issuer(issuer);
		}
		claimsBuilder
				.subject(context.getPrincipal().getName())
				.audience(Collections.singletonList(registeredClient.getClientId()))
				.issuedAt(issuedAt)
				.expiresAt(expiresAt);
		// @formatter:on

		JwsHeader.Builder headersBuilder = JwsHeader.with(SignatureAlgorithm.RS256);

		if (this.jwtCustomizer != null) {
			// @formatter:off
			JwtEncodingContext.Builder jwtContextBuilder = JwtEncodingContext.with(headersBuilder, claimsBuilder)
					.registeredClient(context.getRegisteredClient())
					.principal(context.getPrincipal())
					.providerContext(context.getProviderContext())
					.authorizedScopes(context.getAuthorizedScopes())
					.tokenType(context.getTokenType())
					.authorizationGrantType(context.getAuthorizationGrantType());
			if (context.getAuthorization() != null) {
				jwtContextBuilder.authorization(context.getAuthorization());
			}
			if (context.getAuthorizationGrant() != null) {
				jwtContextBuilder.authorizationGrant(context.getAuthorizationGrant());
			}
			// @formatter:on

			JwtEncodingContext jwtContext = jwtContextBuilder.build();
			this.jwtCustomizer.customize(jwtContext);
		}

		JwsHeader headers = headersBuilder.build();
		JwtClaimsSet claims = claimsBuilder.build();

		Jwt jwt = this.jwtEncoder.encode(JwtEncoderParameters.from(headers, claims));

		return new OAuth2RefreshToken(jwt.getTokenValue(), issuedAt, expiresAt);
	}

	public void setJwtCustomizer(OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer) {
		Assert.notNull(jwtCustomizer, "jwtCustomizer cannot be null");
		this.jwtCustomizer = jwtCustomizer;
	}

}
```

Then you can configure the `JwtRefreshTokenGenerator ` as mentioned in this [comment](https://github.com/spring-projects/spring-authorization-server/issues/783#issuecomment-1156173336).
