### ISSUE TITLE
Supports JDBC token checking

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [spring-projects/spring-authorization-server#791]
Add a function: after the token is checked successfully, check whether the token exists in the database

**Comment by jgrandja** [comment]
@xuxiaowei-com-cn I took a look at your PR in Spring Security and `OAuth2AuthorizationServiceJwtAuthenticationConverter` would not go into the core code base. Also, the Resource Server should not have direct access to `OAuth2AuthorizationService` as this component should be restricted to the Authorization Server only. It doesn't prevent you from configuring as such but it would be considered an anti-pattern.

FYI, in the future, please submit an issue providing all details before submitting a PR. This will avoid unnecessary work. We can discuss in the issue whether the enhancement or feature is needed or not.
