### ISSUE TITLE
Sample code or documentation for using federated-identity-authorizationserver / resource-server from SPA

### ISSUE THREAD

**Issue by justinhrobbins** [spring-projects/spring-authorization-server#799]
Currently there is a [samples](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) project that uses a Spring Boot server side application ([messages-client](https://github.com/spring-projects/spring-authorization-server/tree/main/samples/messages-client)) to interact with the sample federated-identity-authorizationserver and resource-server. This is really helpful. Thanks!

I _think_ another common use case might be to access a Spring federated-identity-authorizationserver and resource-server directly from a Javascript SPA. Indeed, it is really common to encounter web apps that allow Google login (OIDC) to access non-Google APIs. Providing some sample or documentation on how to do this would be really useful.

I understand providing sample code for a specific Javascript SPA front-end might be out of scope for a Spring project. If that's the case, could there be sample or documentation that generically explains how one might implement this feature? Maybe directly via REST calls (as the SPA front-end would do) without a specific example using React, Angular, etc.

I wasn't 100% if this sample documentation would be a valid feature request. Alternatively, I could create a StackOverflow question with more specific questions regarding my effort to do this in my own project*. However, I'm having a bit of difficulty getting started and could benefit from some guidance (hence the doc request).

*Clarification: When I say "my effort to do this in my own project" I'm referring to converting my existing React SPA + Spring oauth2-resource-server that uses Google OIDC to the federated example as recommended by @sjohnr [in this SO post](https://stackoverflow.com/questions/71254326/spring-boot-authorization-server-google-oauth2-openid-connect-should-work-with) a couple of months ago.

Thanks for your consideration and patience. Cheers!

**Comment by sjohnr** [comment]
@justinhrobbins, thanks for reaching out!

I don't believe there's anything different the client needs to do to integrate with the federated sample versus the default authorization server sample. The client should be unaware of whether the authorization server is federated or not. See [this branch](https://github.com/sjohnr/spring-authorization-server/tree/bff-demo/samples) (specifically angular-client and backend-for-frontend-client) and [this webinar](https://tanzu.vmware.com/content/webinars/mar-10-getting-started-with-spring-authorization-server) for a demonstration of integrating an Angular client with the default authorization server sample. React would be fairly similar. Unfortunately, I'm unable to find the time to keep that branch up to date, but I believe it is still extremely relevant.

As far as providing an official sample with a Javascript frontend, I'm not sure there's strong interest in maintaining anything like that at this time, given this project doesn't have the necessary tooling and support for keeping a javascript sub-project up to date. For that reason, I think I'm going to close this issue for now and hope that the links above are helpful to you. If you have other specific questions, please do open one or more stackoverflow questions and link them here, and I'll happily take a look.
