### ISSUE TITLE
redirect_uri validation

### ISSUE THREAD

**Issue by scott9999** [spring-projects/spring-authorization-server#808]
**Expected Behavior**
I have a use case where the redirect_uri is not used, but "/" is supplied, there does not appear to be a way to plugin in my own redirect_uri validation, classes such as DefaultRedirectUriOAuth2AuthenticationValidator are private.

**Comment by jgrandja** [comment]
@scott9999 You can configure `OAuth2AuthorizationCodeRequestAuthenticationProvider.setAuthenticationValidatorResolver()` to override the default validation for `redirect_uri`.

We need to document it's usage in the reference manual so I logged gh-858.

I'm going to close this as the above configuration allows overriding the default validation for `redirect_uri`.
