### ISSUE TITLE
when i use PKCE, i failed to get /well-known/openid-configuration  because of a cors error

### ISSUE THREAD

**Issue by limng06** [spring-projects/spring-authorization-server#809]
**Describe the bug**
i'm using pkce with vue  +  oidc-cllient-ts 

but  the corsFilter is not included in the filter chain

************************************************************

Request received for GET '/.well-known/openid-configuration':

org.apache.catalina.connector.RequestFacade@395a9811

servletPath:/.well-known/openid-configuration
pathInfo:null
headers: 
user-agent: PostmanRuntime/7.29.2
accept: */*
postman-token: b49536ef-3493-4157-b7a0-30a1c8138789
host: localhost:8080
accept-encoding: gzip, deflate, br
connection: keep-alive
cookie: JSESSIONID=5B9D8005A1DE4268AB06CE6CFA995F47

Security filter chain: [
  DisableEncodeUrlFilter
  WebAsyncManagerIntegrationFilter
  SecurityContextPersistenceFilter
  ProviderContextFilter
  HeaderWriterFilter
  CsrfFilter
  LogoutFilter
  OAuth2AuthorizationEndpointFilter
  OidcProviderConfigurationEndpointFilter
  NimbusJwkSetEndpointFilter
  OAuth2AuthorizationServerMetadataEndpointFilter
  OAuth2ClientAuthenticationFilter
  UsernamePasswordAuthenticationFilter
  DefaultLoginPageGeneratingFilter
  DefaultLogoutPageGeneratingFilter
  BearerTokenAuthenticationFilter
  RequestCacheAwareFilter
  SecurityContextHolderAwareRequestFilter
  AnonymousAuthenticationFilter
  SessionManagementFilter
  ExceptionTranslationFilter
  FilterSecurityInterceptor
  OAuth2TokenEndpointFilter
  OAuth2TokenIntrospectionEndpointFilter
  OAuth2TokenRevocationEndpointFilter
  OidcUserInfoEndpointFilter
]

************************************************************

**Comment by shanzhaozhen** [comment]
> **Describe the bug** i'm using pkce with vue + oidc-cllient-ts
> 
> but the corsFilter is not included in the filter chain
> 
> Request received for GET '/.well-known/openid-configuration':
> 
> org.apache.catalina.connector.RequestFacade@395a9811
> 
> servletPath:/.well-known/openid-configuration pathInfo:null headers: user-agent: PostmanRuntime/7.29.2 accept: _/_ postman-token: b49536ef-3493-4157-b7a0-30a1c8138789 host: localhost:8080 accept-encoding: gzip, deflate, br connection: keep-alive cookie: JSESSIONID=5B9D8005A1DE4268AB06CE6CFA995F47
> 
> Security filter chain: [ DisableEncodeUrlFilter WebAsyncManagerIntegrationFilter SecurityContextPersistenceFilter ProviderContextFilter HeaderWriterFilter CsrfFilter LogoutFilter OAuth2AuthorizationEndpointFilter OidcProviderConfigurationEndpointFilter NimbusJwkSetEndpointFilter OAuth2AuthorizationServerMetadataEndpointFilter OAuth2ClientAuthenticationFilter UsernamePasswordAuthenticationFilter DefaultLoginPageGeneratingFilter DefaultLogoutPageGeneratingFilter BearerTokenAuthenticationFilter RequestCacheAwareFilter SecurityContextHolderAwareRequestFilter AnonymousAuthenticationFilter SessionManagementFilter ExceptionTranslationFilter FilterSecurityInterceptor OAuth2TokenEndpointFilter OAuth2TokenIntrospectionEndpointFilter OAuth2TokenRevocationEndpointFilter OidcUserInfoEndpointFilter ]

Can you provide me with a demo to learn? Recently, I have also been learning about this integration, including front and back, thank you!

**Comment by muratdturk** [comment]
@jgrandja I have been seeing similar CORS error when I try to use openId option with Angular UI and not able to get .well-know/openid-configuration without CORS error 
![image](https://user-images.githubusercontent.com/46765837/213941982-1bd53e80-61e1-43fe-a3d5-138a497beded.png)

**Comment by muratdturk** [comment]
![image](https://user-images.githubusercontent.com/46765837/213942002-6cefe021-387c-49a8-b218-30938e4c1083.png)

**Comment by muratdturk** [comment]
Thank you so much @jgrandja, I updated my corsConfigurationSource method with the example from the link you shared. It works now. I was using it slightly different.  Much appreciated
