### ISSUE TITLE
Typo in https://spring.io/blog/2022/07/28/spring-authorization-server-is-going-1-0

### ISSUE THREAD

**Issue by DevDengChao** [spring-projects/spring-authorization-server#827]
> Spring Authorization Server 1.0 will be based on Spring Security 6.0, which will be based off of [Spring Framework 6.0](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) and will require a minimum of JDK 17 at runtime.

Maybe `require a minimum of JAVA 17 at runtime` or `require a minimum of JRE 17 at runtime` is better, as JDK is for developing.

**Comment by jgrandja** [comment]
Thank you @DevDengChao ! Updated to `Java 17`.
