### ISSUE TITLE
International support

### ISSUE THREAD

**Issue by chenzhenjia** [spring-projects/spring-authorization-server#830]
In spring security, use SpringSecurityMessageSource.getAccessor() to support internationalization. Can the spring-authorization-server project also use a similar method to support internationalization?

**Comment by jgrandja** [comment]
@chenzhenjia Spring Authorization Server is a low level framework that doesn't really have any content to internationalize. There is only one UI provided, the default consent page, but production applications would typically provide a custom consent page so there isn't much value with internationalizing the default consent page.

Can you provide more details on what content you want to internationalize?

**Comment by chenzhenjia** [comment]
@jgrandja Not the internationalization of the page, but the `description` internationalization of the` OAuth2Error`

**Comment by jgrandja** [comment]
@chenzhenjia Thanks for the clarification.

As mentioned, Spring Authorization Server is a framework solely focused on providing OAuth2 and OIDC features. Internationalization is not a feature we want to put our efforts into as we need to remain focused on building OAuth2/OIDC specific features. The consuming application is responsible for internationalization.

If you want to internationalize `OAuth2Error.description`, then you can configure a custom `AuthenticationFailureHandler` in the necessary `Filter` and then translate the framework provided `OAuth2Error.description` before returning the error response.

For example, for client authentication errors, you would configure a custom `AuthenticationFailureHandler` as follows:

```java
OAuth2AuthorizationServerConfigurer authorizationServerConfigurer =
		new OAuth2AuthorizationServerConfigurer();
authorizationServerConfigurer
		.clientAuthentication(clientAuthentication ->
				clientAuthentication.errorResponseHandler(authenticationFailureHandler));
```

The custom `authenticationFailureHandler` would then access the `OAuth2Error` via the passed in `AuthenticationException` and perform the translation before returning the error response.

See the default `AuthenticationFailureHandler` in `OAuth2ClientAuthenticationFilter` as an example:

https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/OAuth2ClientAuthenticationFilter.java#L171

I'm going to close this as we do not plan on providing internationalization support.

**Comment by chenzhenjia** [comment]
If the value of `description` is concatenated, `AuthenticationFailureHandler` cannot get the variable
![image](https://user-images.githubusercontent.com/11611967/185861815-2c15a7db-3402-4259-9da0-ed38e500e338.png)
