### ISSUE TITLE
Support for private-use URI scheme redirection

### ISSUE THREAD

**Issue by wpK** [spring-projects/spring-authorization-server#844]
**Expected Behavior**

For a redirectUri of `com.example.app:/oauth2redirect/example-provider` to validate.

**Current Behavior**

It does not validate. [OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L594](https://github.com/spring-projects/spring-authorization-server/blob/a5e6b032de0046f63ccba40ec6f56accc700ddf9/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java#L594) requires a redirectUri to have a host which is not required for private-use URI schemes.

**Context**

[Private-Use URI Scheme Redirection](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-01#section-10.3) allows private-use URI schemes for native apps.

**Proposed Solution**

```java
Boolean isValidPrivateUseScheme = host == null && port == -1 && userInfo == null && scheme != null && scheme.contains(".")
if ((!isValidPrivateUseScheme && host == null) || host.equals("localhost")) {
    // throw localhost error
}
```

Given [rfc7595](https://datatracker.ietf.org/doc/html/rfc7595#section-3.8) and the [currently limited URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) that contain a `.` , we could do something like the following to add more context:

```java
Boolean isPrivateUseScheme = scheme != null && scheme.contains(".")
if (isPrivateUseScheme && (host != null || port != -1 || userInfo != null)) {
    // throw invalid private use url scheme error
} else if (!isPrivateUseScheme && (host == null || host.equals("localhost"))) {
    // throw localhost error
}
```

**Comment by jgrandja** [comment]
@wpk There already exists the ability to override the default validation for `redirect_uri`.

Please see this [comment](https://github.com/spring-projects/spring-authorization-server/issues/808#issuecomment-1218111695) for details.

Closing this as a duplicate and will close the associated PR.
