### ISSUE TITLE
Can you provide the parameters of each endpoint

### ISSUE THREAD

**Issue by aokleon** [spring-projects/spring-authorization-server#849]
E.g：
 
![image](https://user-images.githubusercontent.com/62325709/183626519-a0216ed4-9bb9-4783-82c5-781fddafc030.png)

methods and params

thank!

**Comment by jgrandja** [comment]
@higodleon I don't understand your use case. Please provide more details.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
