### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by encyclopedi2a** [spring-projects/spring-authorization-server#860]
How to authenticate the user with LDAP for single page app. When connect with LDAP authorization server does not grant the token .
Furthermore how to customize the default login form to custom form based on organization theme.

**Comment by jgrandja** [comment]
@encyclopedi2a Spring Authorization Server does not implement authentication, however, it does integrate with an authentication sub-system through the configuration provided by Spring Security.

See the Spring Security docs on how to configure [formLogin()](https://docs.spring.io/spring-security/reference/6.0/servlet/authentication/passwords/form.html) and [LDAP](https://docs.spring.io/spring-security/reference/6.0/servlet/authentication/passwords/ldap.html).
