### ISSUE TITLE
Can you provide a way to customize the names of these OAUTH2 tables

### ISSUE THREAD

**Issue by luyanfeng** [spring-projects/spring-authorization-server#870]
Can you provide a way to customize the names of these OAUTH2 tables？

JdbcRegisteredClientRepository：
`	private static final String TABLE_NAME = "oauth2_registered_client";
`
JdbcOAuth2AuthorizationConsentService:
`private static final String TABLE_NAME = "oauth2_authorization_consent";`

JdbcOAuth2AuthorizationService:
`private static final String TABLE_NAME = "oauth2_authorization";`
and so on.

**Comment by lu-cheng** [comment]
There is a use case for JPA in the doc, and you can customize the table name through JPA. You can find samples here:
https://github.com/spring-projects/spring-authorization-server/tree/main/docs/src/docs/asciidoc/examples/src/main/java/sample/jpa

**Comment by luyanfeng** [comment]
> There is a use case for JPA in the doc, and you can customize the table name through JPA. You can find samples here: https://github.com/spring-projects/spring-authorization-server/tree/main/docs/src/docs/asciidoc/examples/src/main/java/sample/jpa

thank you.
