### ISSUE TITLE
Consider a lenient scope validation strategy in OAuth2ClientCredentialsAuthenticationProvider

### ISSUE THREAD

**Issue by yonyes** [spring-projects/spring-authorization-server#884]
**Expected Behavior**

When a token request includes scopes that part of them aren't permitted, return the new token with only the permitted scopes

**Current Behavior**

When a token request includes scopes that part of them aren't permitted, it raises an internal exception, and the request answer is 400:
`{
    "error": "invalid_scope"
}`

**Context**

It's not a rare scenario that permissions of clients are changed and the clients themselves are not always updated immediately (or at all). It makes sense to generate the token with the scopes it allowed instead of failing the request.

The relevant code is in the _OAuth2ClientCredentialsAuthenticationProvider.java_

`for (String requestedScope : clientCredentialsAuthentication.getScopes()) {
				if (!registeredClient.getScopes().contains(requestedScope)) {
					throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_SCOPE);
				}
			}
`

**Comment by jgrandja** [comment]
@yonyes

[Section 3.2.2.1 Access Token Scope](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-3.2.2.1) states the following:

> The authorization server MAY fully or **partially ignore** the scope
   requested by the client, based on the authorization server policy or
   the resource owner's instructions.

Based on this, we'll consider a more lenient validation strategy.

**Comment by jgrandja** [comment]
We should consider adding `OAuth2ClientCredentialsAuthenticationProvider.setAuthenticationValidator(Consumer<OAuth2ClientCredentialsAuthenticationContext> authenticationValidator)`, which would allow a consuming application to override the default `scope` validation.

The "authentication validator" feature exists in `OAuth2AuthorizationCodeRequestAuthenticationProvider. See [example](https://docs.spring.io/spring-authorization-server/docs/0.4.0-SNAPSHOT/reference/html/protocol-endpoints.html#oauth2-authorization-endpoint-customizing-authorization-request-validation).

**Comment by appchemist** [comment]
I want to take this issue, @jgrandja

I have a question.

When a token request includes scopes that part of them aren't permitted and a custom lenient scope validation is used, `OAuth2AuthorizationCodeRequestAuthenticationProvider` can generates token with scope containing unpermitted.
So How about generating token with only permitted scopes & requested scopes by default?

**Comment by jgrandja** [comment]
Thanks for your interest @appchemist.

As soon as this issue is scheduled for a milestone, I'll reach out to you.

We'll be planning the features for the `1.1` release soon but I'm not sure yet if this will go into that release.

**Comment by adamleantech** [comment]
I'd like to upvote this request, we have a use case similar to [this one](https://curity.io/resources/learn/scope-best-practices/#prefix-scopes) with prefix scopes that we'd like to support and it would be relatively simple with a more lenient or configurable scope validation strategy.  At the moment we're having to create quite an unpleasant workaround

**Comment by jgrandja** [comment]
@adamleantech Please upvote the main issue comment.

**Comment by jgrandja** [comment]
This is now resolved via gh-1377.

The default scope validation can now be customized using `OAuth2ClientCredentialsAuthenticationProvider.setAuthenticationValidator(Consumer<OAuth2ClientCredentialsAuthenticationContext> authenticationValidator)`.
