### ISSUE TITLE
Client Impersonating Resource Owner

### ISSUE THREAD

**Issue by lu-cheng** [spring-projects/spring-authorization-server#914]
AS did not handle [Client Impersonating Resource Owner.](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-06.html#client-impersonating-resource-owner)

**Comment by jgrandja** [comment]
@lu-cheng The description provided is not sufficient to investigate this further. Please provide details on your specific use case or this will get closed.

> If a client is able to choose its own client_id during registration with the authorization server, then there is a risk that it can register with the same sub value as a privileged user.

I do not see how this scenario can happen with the default configuration.

**Comment by lu-cheng** [comment]
Currently AS allows the client_id to be the same as the end user name, which may result in confusing access tokens.
> Where this cannot be avoided, authorization servers MUST provide other means for the resource server to distinguish between access tokens authorized by a resource owner from access tokens authorized by the client itself.
