### ISSUE TITLE
OidcUserInfo Change PhoneNumberVerified Field to Boolean

### ISSUE THREAD

**Issue by ramonmalcolm10** [spring-projects/spring-authorization-server#923]
**Describe the bug**
When setting the phoneNumberVerified field, it accept a String instead of a boolean. 

**To Reproduce**
`OidcUserInfo userInfo = OidcUserInfo.builder().phoneNumberVerified(String.valueOf(true)).build();`

**Expected behavior**
`OidcUserInfo userInfo = OidcUserInfo.builder().phoneNumberVerified(true).build();`

**Comment by jgrandja** [comment]
Thanks for the report @ramonmalcolm10. This is now resolved via 629e220c2f39e9512abab642a178d87b28d69b6d.
