### ISSUE TITLE
In the Authorization Code Grant, scope should be optional

### ISSUE THREAD

**Issue by Hccake** [spring-projects/spring-authorization-server#924]
According to [OAuth2.1 RFC 4.1.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-06#section-4.1.1), scope is optional in **Authorization Code Grant**，but now if you don't add scope parameter in request, exception will be thrown when user authorize.

See lines 162 - 173 of `OAuth2AuthorizationConsentAuthenticationProvider`
```java

		Set<GrantedAuthority> authorities = new HashSet<>();
		authorizationConsentBuilder.authorities(authorities::addAll);

		if (authorities.isEmpty()) {
			// Authorization consent denied (or revoked)
			if (currentAuthorizationConsent != null) {
				this.authorizationConsentService.remove(currentAuthorizationConsent);
			}
			this.authorizationService.remove(authorization);
			throwError(OAuth2ErrorCodes.ACCESS_DENIED, OAuth2ParameterNames.CLIENT_ID,
					authorizationConsentAuthentication, registeredClient, authorizationRequest);
		}
```

**Comment by Annaseron** [comment]
And I have one more question, what should i do if the client has multiple authorization grant types,client_credential grant and AC grant,and every grant type requires different scopes? The client are now shares scopes to all grant types,but i think it should be configured separately. Typically,the token are grant to different objects,client_credential may be grant to background servers for server-to-server calls, and the AC grant may be grant to logged user for server to userinfo endpoint call.

**Comment by jgrandja** [comment]
@Hccake `OAuth2AuthorizationConsentAuthenticationProvider` handles the "User Consent" flow and `OAuth2AuthorizationCodeRequestAuthenticationProvider` handles the "Authorization Request" flow. The `state` parameter you are referring to is in the "User Consent" flow, which is required by the internal implementation. The "User Consent" flow is left to the implementor as it is NOT detailed in the spec. Only the Authorization Request flow is detailed in the spec.

Please see `OAuth2AuthorizationCodeRequestAuthenticationValidator`, which is the default for `OAuth2AuthorizationCodeRequestAuthenticationProvider.authenticationValidator` and `scope` is optional.

**Comment by OrangeDog** [comment]
This is the same issue as https://github.com/spring-attic/spring-security-oauth/issues/1671

An empty scope in the authorization request should mean "all that the client allows", and an empty scope in the client registration should mean "anything the client asks for".
