### ISSUE TITLE
The samples are not working with org.springframework.boot:3.0.0-M5

### ISSUE THREAD

**Issue by tapasbose** [spring-projects/spring-authorization-server#926]
Hello,
The [samples](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) is not working with **org.springframework.boot:3.0.0-M5**. 
I have followed the instructions for running the default-authorizationserver, along with messages-resource and messages-client. It is working with **org.springframework.boot:3.0.0-M4**, which is defined in the gradle. When I am hitting the http://127.0.0.1:8080/ I can see and can login successfully.

![image](https://user-images.githubusercontent.com/1482557/195598649-14818949-5263-4f75-9e1e-2f5d1b6ac3d9.png)

But after changing the version to **org.springframework.boot:3.0.0-M5** and re-executing all the above applications when I am hitting http://127.0.0.1:8080/, I see:

![image](https://user-images.githubusercontent.com/1482557/195599315-49d86f50-dff4-4498-bf45-f07032165488.png)

and hitting either of the link messaging-client-oidc and messaging-client-authorization-code is navigating to Whitelabel Error Page:

![image](https://user-images.githubusercontent.com/1482557/195599740-6f780b42-1a5f-487f-adfa-4ef4019b2ec4.png)

Regards,
Tapas

**Comment by jgrandja** [comment]
Thanks for the report @tapasbose. This is now resolved via gh-935. Closing this as a duplicate.
