### ISSUE TITLE
Can't cast OAuth2TokenRevocationAuthenticationToken to OAuth2ClientAuthenticationToken

### ISSUE THREAD

**Issue by sjerman** [spring-projects/spring-authorization-server#942]
**Describe the bug**
Looks like wrong cast in OAuth2TokenRevocationAuthenticationProvider (using 0.3.1)

`

		OAuth2TokenRevocationAuthenticationToken tokenRevocationAuthentication =
				(OAuth2TokenRevocationAuthenticationToken) authentication;

		OAuth2ClientAuthenticationToken clientPrincipal =
				getAuthenticatedClientElseThrowInvalidClient(tokenRevocationAuthentication);
`

but `OAuth2AuthenticationProviderUtils.getAuthenticatedClientElseThrowInvalidClient`  attempts to cast OAuth2TokenRevocationAuthenticationToken to OAuth2ClientAuthenticationToken (they are separate implementations of AbstractAuthenticationToken

**To Reproduce**
 Try to revoke token ..

**Comment by jgrandja** [comment]
@sjerman This feature has been implemented a while back and no issues have been reported. The integration test [OAuth2TokenRevocationTests](https://github.com/spring-projects/spring-authorization-server/blob/2ba7bba28f3e5c38a7b3b611b8944d99701d77a3/oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/config/annotation/web/configurers/OAuth2TokenRevocationTests.java#L97) works as well.

Can you compare the configuration in `OAuth2TokenRevocationTests` to your configuration to ensure it's configured correctly.

**Comment by sjerman** [comment]
I'll check.

**Comment by sjerman** [comment]
OK, figured it. I was using an access code to authenticate not basic auth. Looks like it works now.
