### ISSUE TITLE
OAuth2AuthorizationServerConfiguration uses Spring Security 5 methods

### ISSUE THREAD

**Issue by ishlyakhtenkov** [spring-projects/spring-authorization-server#947]
**Describe the bug**
OAuth2AuthorizationServerConfiguration class uses Spring Security 5 methods instead of  Spring Security 6.
So, we can't use the project with Spring Boot 3, because it depends on jakarta classes, but Spring Security 5 uses javax.
For example: applyDefaultSecurity() method from OAuth2AuthorizationServerConfiguration class calls methods on HttpSecurity class that don't exist in HttpSecurity class of Spring Security 6.

**Comment by tkrah** [comment]
Afaik the latest 1.x milestone is spring boot 3 based - did you tried this? Which version did you used at all?

**Comment by ishlyakhtenkov** [comment]
I tried 1.0.0-M1 and 1.0.0-M2.
Now i use 1.0.0-SNAPSHOT. In this version it is OK.

**Comment by jgrandja** [comment]
@ishlyakhtenkov The `main` branch is compatible with Spring Security 6 (Spring Boot 3) and corresponds to the `1.0.0` releases.

The `0.4.x` branch is compatible with Spring Security 5 (Spring Boot 2.7.x) and corresponds to the `0.4.0` releases.
