### ISSUE TITLE
authorization-server 1.0RC1  客户端模式  /oauth2/token 接口返回值少字段

### ISSUE THREAD

**Issue by wangxianlong0408** [spring-projects/spring-authorization-server#957]
authorization-server 1.0RC1  客户端模式  /oauth2/token 接口返回值 无scopes字段了，请问如何配置才会有scopes字段？

**Comment by jgrandja** [comment]
@wangxianlong0408 Please comment in english as I do not understand the issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
