### ISSUE TITLE
Can we support a hook before/after check consent?

### ISSUE THREAD

**Issue by hezhongfeng** [spring-projects/spring-authorization-server#962]
I want to stop the authorization_code grant flow before/after check consent, can we support a hook?

Actually I want to check the relationship between client and user，if failed ,I want stop the authorization_code grant flow.

**Comment by jgrandja** [comment]
@hezhongfeng I don't understand your use case.

> I want to check the relationship between client and user

Can you be more specific for your use case so I can better understand.

**Comment by hezhongfeng** [comment]
I think I find a way `authorizationRequestConverter(AuthenticationConverter)` to check
