### ISSUE TITLE
Provide guidance for implementing Authorization Grant type

### ISSUE THREAD

**Issue by sandipchitale** [spring-projects/spring-authorization-server#966]
**Expected Behavior**

Help with outline of how to implement custom Authorization Grant type and more specifically Resource Owner Password Grant (ROPG).

**Current Behavior**

Lack of support for Resource Owner Password Grant .

**Context**

For BCP reasons the the Resource Owner Password Grant is not supported by Spring Authorization Server. I also there have been requests that have been closed regarding this. In this presentation:

https://www.youtube.com/watch?v=ksp8X6Pfbp8&list=PLgo7G9gw4FGx4BPS7Mh1NviwbCxGiyOS1

it was mentioned at [4:20](https://www.youtube.com/watch?v=ksp8X6Pfbp8&t=260s) the Resource Owner Password grant was mentioned and it was going to be shown how to implement it ( [4:45](https://www.youtube.com/watch?v=ksp8X6Pfbp8&t=285s) ). I guess there is a mention of it at [22:10](https://www.youtube.com/watch?v=ksp8X6Pfbp8&t=1330s) and at [27:45](https://www.youtube.com/watch?v=ksp8X6Pfbp8&t=1665s) by customizing tokenEndpoint customization but would like to understand how to implement it.

The older implementation of (now obsolete) OAuth2 library did support Resource Owner Password Grant and was used by many applications. The lack of Resource Owner Password Grant in Spring Authorization Server prevents the migration. I understand that for BCP reasons the Resource Owner Password Grant is to be discouraged. But for practical reasons of first migrating to Spring Authorization Server this is a road block. Some of the upcoming deprecations in Spring Security e.g. `WebSecurityConfigurerAdapter` may force the hand as well. Also because this affects the OAuth2 clients it may not be possible in some cases to force them to get rid of use of ROPG. I also understand that Spring Authorization Server does not want to appear to encourage contra-BCP implementations. But if we are willing to do the work, it will be very helpful to provide at least an outline of how one can go about implementing custom Authorization Grant type and even better specifically Resource Owner Password Grant. This could be addressed via a blog post if not through a How to entry.

**Comment by taolive** [comment]
> 
I think so, too!
