### ISSUE TITLE
User can publish package but cannot read

### ISSUE THREAD

**Issue by ckmoga** [spring-projects/spring-authorization-server#968]
**Describe the bug**
I have setup a CICD user with PAT. I am using gradle this use can publish packages without any problem.
But when the same user tries to pull these dependencies when building application, it throws 401.

In build.gradle
`maven {
			setUrl("https://maven.pkg.github.com/company/shared-dependency")
			credentials {
				username = gradle_user
				password = gradle_password
			}
		}`

Gradle build error
`> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.company.common:shared-dependency:1.21.
     Required by:
         project :
      > Could not resolve com.company.common:shared-dependency:1.21.
         > Could not get resource 'https://maven.pkg.github.com/company/test-dependency/com/company/common/shared-dependency/1.21/shared-dependency-1.21.pom'.
            > Could not GET 'https://maven.pkg.github.com/company/test-dependency/com/company/common/shared-dependency/1.21/shared-dependency-1.21.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.company.common:shared-dependency:1.21.
         > Could not get resource 'https://maven.pkg.github.com/company/shared-dependency/com/company/common/shared-dependency/1.21/shared-dependency-1.21.pom'.
            > Could not GET 'https://maven.pkg.github.com/company/shared-dependency/com/company/common/shared-dependency/1.21/shared-dependency-1.21.pom'. Received status code 401 from server: Unauthorized
`

Pls note at the moment I have the token locally in gradle.properties and will move to .gradle once I resolve the issue

**Comment by jgrandja** [comment]
The issue you have is not related to this project. Closing as invalid.
