### ISSUE TITLE
OIDC 2.0

### ISSUE THREAD

**Issue by barneag** [spring-projects/spring-authorization-server#969]
Hello Guys, 
We are using your awesome project for OAuth 2.0 on our cloud services.
We want to establish OIDC 2.0 and as far as i can see, you are supporting only OIDC 1.0.
Are you planning to implement OIDC 2.0 soon?
thanks.

**Comment by jgrandja** [comment]
Thanks @barneag !

> Are you planning to implement OIDC 2.0 soon?

Are you referring to OpenID Authentication 2.0 (which is obsolete)?

Can you provide a link to the specification that you are referring to?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
