### ISSUE TITLE
OAuth2TokenEndpointFilter throw exception on urn:ietf:params:oauth:grant-type:jwt-bearer grant type

### ISSUE THREAD

**Issue by barneag** [spring-projects/spring-authorization-server#970]
Hey, 
I'm trying to generate access token with:

1. **private_key_jwt** Authentication method
2. **urn:ietf:params:oauth:grant-type:jwt-bearer** grant type

But seems like `OAuth2TokenEndpointFilter` trying to convert only 3 grant types:
refresh_token, authorization_code, client_credentials

is the above grant type is not supported at all?

thanks.

**Comment by jgrandja** [comment]
Closing as duplicate of gh-546.
