### ISSUE TITLE
need xml docs 

### ISSUE THREAD

**Issue by duansheli** [spring-projects/spring-authorization-server#983]
**Expected Behavior**

does config only support java code ? 
want use xml config authorization-server 

**Current Behavior**

* spring-security
https://docs.spring.io/spring-security/reference/servlet/authentication/rememberme.html

![image](https://user-images.githubusercontent.com/8579595/203266917-3813b4d9-fa1b-48d2-9ca6-2eb7d736a20d.png)

* spring-authorization-server 
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html 

![image](https://user-images.githubusercontent.com/8579595/203267006-b600f1a5-5c46-4700-b66e-2cbc7e248fea.png)

**Comment by jgrandja** [comment]
@duansheli XML configuration is not supported and there are no plans for adding support..

**Comment by fkhantsi** [comment]
xml configuration is still supported by Spring, and this project is a spring project, not community. I would encourage you to reconsider.

This project replaces spring-security-oauth and that library did support xml configuration. Projects like mine, that are configured in xml and use spring-security-oauth, cannot upgrade without a complete rewrite of the security configuration.
