### ISSUE TITLE
when send request to /userinfo with idtoken, it does not work

### ISSUE THREAD

**Issue by wilsonlv** [spring-projects/spring-authorization-server#987]
**Describe the bug**
I have got idtoken, and I sent request to /userinfo with idtoken, it does not work

**To Reproduce**
1、get id token
![image](https://user-images.githubusercontent.com/17563749/203695059-c4828528-e5f6-4693-b55c-f108b5ab8f79.png)

2、send request to /userinfo with idtoken
![image](https://user-images.githubusercontent.com/17563749/203695126-7f6d2664-d76f-48ae-a0bd-b8110bd9838a.png)

3、I traced the code, when it went to this line, it returned null and throwed exception
![image](https://user-images.githubusercontent.com/17563749/203695286-204c4fe9-0df6-482d-ae66-bac04225215b.png)

**Expected behavior**
what confuses me is why the type is OAuth2TokenType.ACCESS_TOKEN instand of IDToken ?

**Comment by wilsonlv** [comment]
this version is 0.4.0

**Comment by wilsonlv** [comment]
this authorizationService is InMemoryOAuth2AuthorizationService, but when i have a bean as following, it works normal

`@Bean`
`    public OAuth2AuthorizationService authorizationService(JdbcTemplate jdbcTemplate,`
`                                                           RegisteredClientRepository registeredClientRepository) {`
`        return new JdbcOAuth2AuthorizationService(jdbcTemplate, registeredClientRepository);`
`    }`

**Comment by ramonmalcolm10** [comment]
You should be using the access_token.

**Comment by wilsonlv** [comment]
> You should be using the access_token.

all right, then i have one more question, what is the use of IDToken?

**Comment by jackxu2011** [comment]
> > You should be using the access_token.
> 
> all right, then i have one more question, what is the use of IDToken?

IDToken is used for sso,  it  likes to the Service Ticket in CAS

**Comment by ramonmalcolm10** [comment]
> > You should be using the access_token.
> 
> all right, then i have one more question, what is the use of IDToken?

You can find more details here https://oauth.net/id-tokens-vs-access-tokens/

**Comment by ramonmalcolm10** [comment]
> > You should be using the access_token.
> 
> all right, then i have one more question, what is the use of IDToken?

You can customize the IdToken and return the user info within that token and the client can decode token and retrieve the user info without needing to call the userinfo endpoint

**Comment by wilsonlv** [comment]
> > > You should be using the access_token.
> > 
> > 
> > all right, then i have one more question, what is the use of IDToken?
> 
> You can customize the IdToken and return the user info within that token and the client can decode token and retrieve the user info without needing to call the userinfo endpoint

great, your reply is very helpful to me, thank you very much !
