### ISSUE TITLE
enhancements in OAuth2Authorization class

### ISSUE THREAD

**Issue by publicocean0** [spring-projects/spring-authorization-server#991]
Hi studying a bit i saw that there are many enhancements/emprovments in the class  OAuth2Authorization:
1) the property "state" is inserted in attributes field but after is used for querying. It is better expose the state field in the main class
2) the field attributes is a map where are inserted objects these are directly serialized. In general for keeping the state in a application is deprecable to use serialization of entire classes.

**Comment by jgrandja** [comment]
@publicocean0 The `state` used in `attributes` is used temporarily during the authorization consent flow and removed after consent is provided, so it doesn't make sense to add a `state` property.

The current design of `OAuth2Authorization` provides the flexibility to store any type of authorization grant data so no changes are required at the moment.
