### ISSUE TITLE
Make RegisteredClient an interface

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [spring-projects/spring-authorization-server#992]
It would be useful if `RegisteredClient` was an interface with accessor methods to retrieve the properties rather than being a concrete class. This would allow you to extend it with additional methods/data and would allow you to use, for example, a database entity as the backing implementation rather than having to constantly convert between entity and `RegisteredClient`. The existing implementation can always be kept as a simple in-memory version. 

To add to the extensibility point - I'm working on an application at the moment where I'm writing a `OAuth2TokenCustomizer` and it would be very useful to simple cast the `RegisteredClient` to my domain entity's representation of the client which contains additional information which I would like add to the token. The current alternative is looking up the client in my database for a second time (as I've already done that to construct the `RegisterdClient`) which is inefficient and annoying.

**Comment by Sm0keySa1m0n** [comment]
Just realised this is a duplicate of #80.

I see it was started that `RegisteredClient` has a protected constructer allowing it to be extended although all its fields are private which means you can't actually reuse them so you'll end up overriding all the methods (including `equals`, `hashCode` and `toString`) anyway so surely it might as well become an interface?

I agree there probably shouldn't be a one-to-one mapping between domain and entity models, but making `RegisteredClient` an interface wouldn't reverse that as an interface isn't really a domain entity as its not a class and doesn't dictate what an entity is and how the data within it is represented (the entire purpose of an interface).

**Comment by sjohnr** [comment]
Hi @Sm0keySa1m0n,

> The current alternative is looking up the client in my database for a second time (as I've already done that to construct the `RegisterdClient`)

You might also consider using custom `clientSettings` to carry additional information.
