### ISSUE TITLE
Use Hibernate instead jdbc data manipulation

### ISSUE THREAD

**Issue by publicocean0** [spring-projects/spring-authorization-server#995]
**Expected Behavior**
the persistence would be designed for be generic for nosql and sql database. For sql database i suggest to realize a hibernate version permitting to configure easly with all sql db. I checked that using mariadb, for example, the DDL defined is not working. 

**Current Behavior**
anomalies using different sql databases. See issue for mariadb for example. 

**Context**
1) use hibernate for sql db. This overcome the anomalies for different db already found and difficult to follow . It is difficult to manage  all using a simple jdbc class. The extensions for managing complex structure doesnt permit to see easly in db the data.
2)  keep status of authorization using enumerations or basic data types, not complex serialized class.
3) i suggest to save tokens in a entity different from  the authorization class

**Comment by jgrandja** [comment]
@publicocean0 `JdbcOAuth2AuthorizationService` is a simplified JDBC implementation that MAY be used in production. However, the expectation is that the consuming application is responsible for implementing `OAuth2AuthorizationService` with whatever backing store of their choice.

This project cannot implement all flavours of persistence. Furthermore, persistence is not a concern for this project and instead is the concern of the consuming application. This projects sole focus is OAuth2 security.

We will not be providing any further implementations of `OAuth2AuthorizationService`, `OAuth2AuthorizationConsentService` and `RegisteredClientRepository`.

If you would like to implement JPA, please see the [How-to guide](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-jpa.html).
